### ISSUE TITLE
Mint Limited Edition Weapons

### ISSUE THREAD

**Issue by YiannisKastritis** [CryptoBlades/cryptoblades#1002]
Nick's idea about the mint of limited edition weapons. This requires some art from Zhang.

Nick's Pitch:
Ideally I would like to be able to pitch a couple of options to these partner project teams.
1. We mint a limited number of them and that's it (Maybe 5 for their team and community and 5 for our team and community)
2. We mint a limited number of them, but also there is a low percent chance that they will also be able to randomly forge one of these rare blades during the period of time that their project is featured on the treasury page
3. We mint a limited number of them, but we have a 24 or 48 hour window where there is a higher percent chance that they forge one of these exclusive weapons (I was thinking of a forging Friday type event that runs into the weekend).
4. Further down the line, I think it would be interesting to give these weapons some type of extra ability as well.  Nothing overpowered, but just something a little more enticing.

*I also think it would be interesting to have some of these weapons be exclusively one type of element at some point.  For example, Cryptomeda and Celestial both deal with space themes so it might be cool to have them be lightning (electricity).

When the time comes, we should discuss all these and take some final decisions to implement

**Comment by brian-man** [comment]
@kcper Already realized in a somewhat different form?
