### ISSUE TITLE
Reserve a wallet username

### ISSUE THREAD

**Issue by bilbolPrime** [CryptoBlades/cryptoblades#1008]
Upcoming CBK will allow assigning a username to wallet in exchange for gold.

Allow players to reserve username(s) to their address in exchange for $KING through market.
- Solidity contract in CB market place, reserve a string for X $KING
- You can reserve multiple in same address
- Solidity would enforce it's globally unique (only BSC can sell this item)
- No spaces or numeric, only characters
- Funny business (slurs etc..), you lose your $KING 
- Acceptable malfunctions (conflict with other reserved words) , you get gold credited to your wallet on launch, 1 $KING = 1 Gold and you can use ingame to change your nickname with that gold
- Why king on point 1, because 1 $KING = 1 gold always so no fluctuations to worry about

**Comment by brian-man** [comment]
@bilbolPrime @seiyria 
It would be nice if the first phase of this allowed people to reserve their Discord user names.  As an example, I'd really hate to have someone "squat" my discord name for their wallet just because they happened to invoke the contract[s] before I did.

**Comment by bilbolPrime** [comment]
Staff names will be reserved by default (kroge / Community manager / admins / mods / devs / volunteer devs), perhaps with a prefix even to make it official or just as is.
I am not sure how this can be accomplished for all discord usernames though :(

**Comment by seiyria** [comment]
Given how easy it is to change a discord username it's a lot of effort for something that can still be gamed.
