### ISSUE TITLE
Re design the Homepage of the CB website

### ISSUE THREAD

**Issue by YiannisKastritis** [CryptoBlades/cryptoblades#1013]
Homepage redesign. You can find all the graphics that you need here:
(https://xd.adobe.com/view/e102f906-bd15-44a0-8658-67b3b49e3f2e-b451/)

- You can navigate to the other designs using the pagination in that design link.
- It contains mobile and desktop version
- Please inform the dev not to develop the "Recruit Champions" section for now as that might change.
- There will be some other update later but more like content which we can handle while development is on-going.

**Comment by devinep52** [comment]
would be great to have a running total of number of total players, top earning characters (with dollar amounts) things like that for people to see "wow this is really hot lets jump in and try it"

**Comment by YiannisKastritis** [comment]
if it is doable, let me knowing so we can ask from Zhang to add it, unless Kevin can add it without Zhang's graphics if possible

**Comment by kevinunger** [comment]
@YiannisKastritis  I can add that without a new design. I'll could add that to the 'Game statistics'
