### ISSUE TITLE
Characters unselecting randomly

### ISSUE THREAD

**Issue by Sellie96** [CryptoBlades/cryptoblades#1020]
Occasionally when selecting a character other than your first one it keeps popping you back to your first one. This has been reported by many members of the community and Kroge on stream. I can't find any steps to replicate so will need a bit of investigation, but seemingly it is not finding the selected character and falling back to the first character. Ctrl + f5 resolves the issue.

**Comment by krisukox** [comment]
What is the priority of this issue?

**Comment by Sellie96** [comment]
Low as it can be fixed with a ctrl + f5 and has no impact on gameplay. But it is reasonably annoying.
