### ISSUE TITLE
Market shows wrong results  when searched for weapons after user lists a weapon

### ISSUE THREAD

**Issue by Nizzypal** [CryptoBlades/cryptoblades#106]
I forged 4 weapons and went to the market.
I listed 2, after which I tried to browse weapons.  Of course since i only listed two, before i searched for weapons, there were already the 2 being shown which was left that I forged that I didnt list.  When I click browse weapons, my UNlisted weapons didnt disappear and no new weapons appered.   I had to go to another page  and go back to market and then browse weapons again to the page to show the right weapons

**Comment by newb23** [comment]
I'll look at this while pursuing #246

**Comment by newb23** [comment]
Closed with changes to the market API usage.
