### ISSUE TITLE
"rewards available" showing on way more staking options than there are rewards

### ISSUE THREAD

**Issue by seiyria** [CryptoBlades/cryptoblades#1068]
![image](https://user-images.githubusercontent.com/763609/150646208-2c73a13c-79a9-47ca-8928-dfbfb3be2445.png)

there might need to be a new color set for:

- no rewards, I have rewards available in this pool
- no rewards, I have no rewards in this pool (currently: red)
- rewards. I have rewards in this pool.
- rewards. I do not have rewards in this pool (currently: green)

this would let users see if they have anything in the rewards

**Comment by krisukox** [comment]
How about gold background?

![cos](https://user-images.githubusercontent.com/38990293/150678768-f1997b0e-5eb0-49b3-a2d5-ce2a63ee2102.png)

- no rewards, I have rewards available in this pool (red with gold background)
- no rewards, I have no rewards in this pool (red)
- rewards. I have rewards in this pool. (green with gold background)
- rewards. I do not have rewards in this pool (green)

**Comment by seiyria** [comment]
We can try that!

**Comment by heki-ru** [comment]
I would also like to see the marks at top right instead of top left, but that's just personal preference
