### ISSUE TITLE
Stop forcing SKILL spend approvals if remaining allowance covers the spending

### ISSUE THREAD

**Issue by kcper** [CryptoBlades/cryptoblades#1119]
In Market (and probably few other places, needs a little investigation) there is a forced transaction to approve SKILL spend even if your allowance would cover that SKILL amount. We should check current allowance and don't ask for approval if there's enough to cover the payment.

**Comment by heki-ru** [comment]
This also happens in pvp every time skill spends needed, on entry and enemy rerolling for example
