### ISSUE TITLE
NFT renting

### ISSUE THREAD

**Issue by poshdan** [CryptoBlades/cryptoblades#1134]
As requested by Kroge:

- An escrow contract should be created that can hold characters, weapons etc (perhaps an extension to garrison)
- This contract would allow renting your NFTs to other people for certain activities. (primarily fights, maybe others later)
- The rented NFT would stay in the escrow, but delegated calls could be made on the contract's behalf by a third party.
- On claiming fight earnings, the owner of the NFT would get a % of the funds.
- The exact conditions on renting is not yet decided (if there is a recurring renting cost, if the owner has to manually allow a specific user for this task, if there is an upfront rent fee, how the rent duration is decided & enforced etc)

This could be a potential way to leverage free gas solutions for users, where we supply the gas that is used for these transactions, and the end user just needs to choose what to do.
A major requirement of this feature would be to have as little impact as possible on the existing contracts and their gas usage.

This ticket is due for further discussion, please get in contact on Discord if you are interested / have ideas on the execution.

**Comment by brian-man** [comment]
@poshdan What channel on discord?  Interesting area.
