### ISSUE TITLE
Treasury projects should auto-disable when funds are depleted

### ISSUE THREAD

**Issue by brian-man** [CryptoBlades/cryptoblades#1145]
Implementation strawman:
- add `internal` function `setInactiveIfDepleted()`
- invoke `setInactiveIfDepleted()` at the top and bottom of `claim()`
- (consider) add `require` to `setIsActive(..., true)` that ensures supply is non-zero

**Comment by brian-man** [comment]
The Tryhards treasury partner id should probably be retired.  It's been at zero supply for a few days.

Rather than requiring human intervention, shouldn't we just have the contracts automatically market themselves as inactive?

@devinep52 @poshdan

**Comment by poshdan** [comment]
Still relevant according to Taloner,
This would save some man hours at the cost of a small gas impact for users (i estimate 800 units for the if-check, which is tiny).
The last user to claim will have a somewhat higher cost but considering users normally wait days between claiming and these token entries are distributed over a month it doesn't amount to much impact.
