### ISSUE TITLE
Adding our Market in different chains(BSC/Poly/Avax) in dappradar

### ISSUE THREAD

**Issue by MrBaptista69** [CryptoBlades/cryptoblades#1148]
We need to send them some config for our market on the different chains(BSC/Poly/Avax) in dappradar's marketplace site

We need to follow their instructions from here:
https://github.com/dappradar/nft-sales-adapters

**Comment by ed3ath** [comment]
https://github.com/dappradar/nft-sales-adapters/pull/5
