### ISSUE TITLE
Changed the input field of character burning

### ISSUE THREAD

**Issue by kevinunger** [CryptoBlades/cryptoblades#1154]
The text field for the amount of souls needs to be an input field. Users need to use the slider currently, which makes it hard to input exact amounts. 
![image](https://user-images.githubusercontent.com/5601589/153101658-b6830753-001c-456a-b56e-e338a6b47ed4.png)

Also, maybe the 'use max' can be used to select the maximum amount of souls possible for the selected char.

**Comment by Steart** [comment]
It seems that this issue is already solved with the new UI upgrade?

**Comment by kevinunger** [comment]
@Steart yeah!
