### ISSUE TITLE
mass-salvage items into dust

### ISSUE THREAD

**Issue by seiyria** [CryptoBlades/cryptoblades#122]
dust comes in 5 colors, each representing 1-5 stars. items can be burned into dust, which can be used to reforge en masse. items will need to be able to be burned either 1 at a time or X items at a time (some kind of checkbox select for items to burn)

https://cryptoblades.hellonext.co/b/Suggestions/p/change-burn-of-reforge-into-a-claimable-item

dust can also be used for other things in the future, but fast reforging is a good one for now

**Comment by brian-man** [comment]
Note that the contract side of this is already underway here:
https://github.com/CryptoBlades/cryptoblades/issues/146

This issue is regarding the browser UI side of things.

**Comment by seiyria** [comment]
as a note, ui-wise, we have resolved to make 3 kinds of dust instead (lb, 4, 5). I'm not sure if that was happening initially or not, though.
