### ISSUE TITLE
Our nfts viewable on other marketplaces

### ISSUE THREAD

**Issue by kcper** [CryptoBlades/cryptoblades#1241]
Create a backend to store/update data of our nfts. There should be an API to fetch nft data in a correct format. I think we should use this metadata standard to support most of the marketplaces https://docs.opensea.io/docs/metadata-standards.
Some other reference here: https://eips.ethereum.org/EIPS/eip-721

**Comment by brian-man** [comment]
Note that this is already present in the contracts because of some recent work:
https://testapi.cryptoblades.io/nfts/view/bsc/cb-character/12345

But the `image` link in the json doesn't load:
http://testapi.cryptoblades.io/nfts/images/cb-character/chara-1.png

**Comment by brian-man** [comment]
> pushed the fix for this.

Cool
