### ISSUE TITLE
obtain config from new location

### ISSUE THREAD

**Issue by seiyria** [CryptoBlades/cryptoblades#1269]
https://github.com/CryptoBlades/config

https://config.cryptoblades.io/app-config.json

gitignore the old one

**Comment by Steart** [comment]
@seiyria Do you want this to be pulled once during for example the `npm run start:frontend` command?
Or do you want it to get pulled "realtime" from the given url?

**Comment by seiyria** [comment]
@Steart it should be obtained at build or install time like it is done in the API and marketplace project
