### ISSUE TITLE
Quests should show a confirmation/warning on submitting higher tier goods than required

### ISSUE THREAD

**Issue by poshdan** [CryptoBlades/cryptoblades#1280]
We recently made it possible to submit goods on a quest that are above the required star rating. This way some users could give 2 star junk on a 1star junk requiring quest and so on, if they so wished.

Unfortunately, inattentive users might accidentally submit something of much higher quality. We shuld let them know they are overpaying for the quest before letting them submit the transaction

**Comment by Chriserus** [comment]
As discussed in dms, for now we're adding a disclaimer and we can monitor the situation and if a confirmation is a must https://github.com/CryptoBlades/cryptoblades/pull/1285
