### ISSUE TITLE
Refactor: Move all contract calls from .vue files to store.ts

### ISSUE THREAD

**Issue by kevinunger** [CryptoBlades/cryptoblades#1283]
There are still some contract calls directyl made from our template files that need to be moved to the store.ts actions.

E.g. move that to store actions:
https://github.com/CryptoBlades/cryptoblades/blob/190be3deaba8801814c6db707752ef488178fde9/frontend/src/views/Blacksmith.vue#L601

The idea is to have all calls as reusable actions that can be dispatched and managed with vuex and be queued in a central place.

**Comment by kevinunger** [comment]
@Steart Are you still willing to do that? If not, please remove your self as assigned :-)

**Comment by Steart** [comment]
@kevinunger you may pick it up, I unassigned myself ;)
