### ISSUE TITLE
Widget for directing the player in other dexes

### ISSUE THREAD

**Issue by MrBaptista69** [CryptoBlades/cryptoblades#1288]
A widget to put on our website that just hooks directly into pancakeswap or apeswap contracts to swap tokens

**Comment by kevinunger** [comment]
from dc:
Can be embedded via iframe:
Pangolin
butterswap
poocoin
pancake
apeswap

poocoin is optimized for embedding. Apeswap might block embedding.

**Comment by Sellie96** [comment]
<iframe src="https://apeswap.finance/swap" height="800" width="1200" title="Custom Title" />

Code from Apeswap team for embedding
