### ISSUE TITLE
Getting an error message when I do combat.

### ISSUE THREAD

**Issue by MrBaptista69** [CryptoBlades/cryptoblades#1306]
I'm getting an error message when I do combat.  I didn't see it posted anywhere that this was happening, but I may have missed it.  Appreciate any insight here.

Error: Transaction has been reverted by the EVM: { "blockHash": "0x7215e73955c2ea563cf10e96ae3b3804237fceb4bef523780ec65f9bb6960b40", "blockNumber": 16569481, "contractAddress": null, "cumulativeGasUsed": 20507875, "from": "0x946c5747f56694506adadec2364531a91210b9a2", "gasUsed": 64058, "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "status": false, "to": "0x39bea96e13453ed52a734b6aceed4c41f57b2271", "transactionHash": "0xff778c31737f5d7e57c17553db1a4a539166d550167f7c6a59f59b27c1073984", "transactionIndex": 182, "type": "0x0", "events": {} }

**Comment by brian-man** [comment]
@MrBaptista69 Your weapon was busy in the PvP Arena.

**Comment by Sellie96** [comment]
Closing the issue was discussed in channel
