### ISSUE TITLE
Script for doing more than 10 land stakes at the same time

### ISSUE THREAD

**Issue by MrBaptista69** [CryptoBlades/cryptoblades#1327]
As far as the number of lands to stake at a time, it should be pretty high.  
For context, our largest purchaser bought 7608 lands.

**Comment by ed3ath** [comment]
`var state = document.getElementsByTagName('a')[0].__vue__.$store.state
var defaultOptions = { from: state.defaultAccount };

var landTiers = {
    '1': 'cbkLandT1',
    '2': 'cbkLandT2',
    '3': 'cbkLandT3'
}

async function getOwnedLandIdsWithTier() {
    var { CBKLand } = state.contracts()
    var landsIds =  await CBKLand.methods.getOwned(state.defaultAccount).call(defaultOptions);

    var landIdsWithTier = await Promise.all(landsIds.map(async (landId) =>
    {
        var land = await CBKLand.methods.get(landId).call(defaultOptions);
        return { id: landId, tier: land[0] };
    }));
    return landIdsWithTier;
}

function getStakingContracts (type) {
    return {
        StakingRewards: state.contracts().nftStaking[type].StakingRewards || null,
        StakingToken: state.contracts().nftStaking[type].StakingToken || null,
        RewardToken: state.contracts().SkillToken
    };
}

async function stake(id, type) {
    const { StakingRewards, StakingToken } = getStakingContracts(type);
    await StakingToken.methods.approve(StakingRewards.options.address, id).send({
        from: state.defaultAccount
    });

    await StakingRewards.methods.stake(id).send({
        from: state.defaultAccount,
    });
}

var lands;
var counter = 0;

async function init() {
    console.log("%cRunning land staker...", "color:blue; font-size:20px");
    lands = await getOwnedLandIdsWithTier();
    if (lands.length > 0) {
        await stakeIteration() ;
    } else {
        console.log("%cYou don't own any land!!", "color:red; font-size:20px");
    }
}

async function stakeIteration() {
    if (counter < lands.length) {
        await stake(lands[counter].id, landTiers[lands[counter].tier]);
        counter++;
        await stakeIteration();
    } else {
        console.log('%cFinished!', "color:green; font-size:20px");
    }
}

await init();`

minified version
`var state=document.getElementsByTagName('a')[0].__vue__.$store.state
var defaultOptions={from:state.defaultAccount};var landTiers={'1':'cbkLandT1','2':'cbkLandT2','3':'cbkLandT3'}
async function getOwnedLandIdsWithTier(){var{CBKLand}=state.contracts()
var landsIds=await CBKLand.methods.getOwned(state.defaultAccount).call(defaultOptions);var landIdsWithTier=await Promise.all(landsIds.map(async(landId)=>{var land=await CBKLand.methods.get(landId).call(defaultOptions);return{id:landId,tier:land[0]}}));return landIdsWithTier}
function getStakingContracts(type){return{StakingRewards:state.contracts().nftStaking[type].StakingRewards||null,StakingToken:state.contracts().nftStaking[type].StakingToken||null,RewardToken:state.contracts().SkillToken}}
async function stake(id,type){const{StakingRewards,StakingToken}=getStakingContracts(type);await StakingToken.methods.approve(StakingRewards.options.address,id).send({from:state.defaultAccount});await StakingRewards.methods.stake(id).send({from:state.defaultAccount,})}
var lands;var counter=0;async function init(){console.log("%cRunning land staker...","color:blue; font-size:20px");lands=await getOwnedLandIdsWithTier();if(lands.length>0){await stakeIteration()}else{console.log("%cYou don't own any land!!","color:red; font-size:20px")}}
async function stakeIteration(){if(counter<lands.length){await stake(lands[counter].id,landTiers[lands[counter].tier]);counter++;await stakeIteration()}else{console.log('%cFinished!',"color:green; font-size:20px")}}
await init()`

**Comment by ed3ath** [comment]
Minified version:
```var state=document.getElementsByTagName('a')[0].__vue__.$store.state
var defaultOptions={from:state.defaultAccount};var landTiers={'1':'cbkLandT1','2':'cbkLandT2','3':'cbkLandT3'}
async function getOwnedLandIdsWithTier(){var{CBKLand}=state.contracts()
var landsIds=await CBKLand.methods.getOwned(state.defaultAccount).call(defaultOptions);var landIdsWithTier=await Promise.all(landsIds.map(async(landId)=>{var land=await CBKLand.methods.get(landId).call(defaultOptions);return{id:landId,tier:land[0]}}));return landIdsWithTier}
function getStakingContracts(type){return{StakingRewards:state.contracts().nftStaking[type].StakingRewards||null,StakingToken:state.contracts().nftStaking[type].StakingToken||null,RewardToken:state.contracts().SkillToken}}
async function stake(id,type){const{StakingRewards,StakingToken}=getStakingContracts(type);await StakingToken.methods.approve(StakingRewards.options.address,id).send({from:state.defaultAccount});await StakingRewards.methods.stake(id).send({from:state.defaultAccount,})}
var lands;var counter=0;async function init(){console.log("%cRunning land staker...","color:blue; font-size:20px");lands=await getOwnedLandIdsWithTier();if(lands.length>0){await stakeIteration()}else{console.log("%cYou don't own any land!!","color:red; font-size:20px")}}
async function stakeIteration(){if(counter<lands.length){await stake(lands[counter].id,landTiers[lands[counter].tier]);counter++;await stakeIteration()}else{console.log('%cFinished!',"color:green; font-size:20px")}}
await init()
