### ISSUE TITLE
display xp payout on fights

### ISSUE THREAD

**Issue by seiyria** [CryptoBlades/cryptoblades#135]
probably at the bottom or on top or somewhere: +16XP (or whatever the value is now)

**Comment by kcper** [comment]
To clarify: the amount of xp reward in case of winning should be displayed next to the enemy

**Comment by Nizzypal** [comment]
done in pull request on branch Issue 135

**Comment by Nizzypal** [comment]
addressed by https://github.com/CryptoBlades/cryptoblades/pull/163 - closing...
