### ISSUE TITLE
When you go to Recruit on a new wallet, enter a referrer ID and they will get .1 In-Game-Only SKILL when you recruit

### ISSUE THREAD

**Issue by MrBaptista69** [CryptoBlades/cryptoblades#1351]
When you go to Recruit on a new wallet, enter a referrer ID and they will get .1 In-Game-Only SKILL when you recruit

**Comment by seiyria** [comment]
Didn't we discuss a long time ago that we weren't doing IGO ever again? Recruiting will also, similarly be a disaster because folks will recruit themselves ad infinitum. There is not a good way to do this.
