### ISSUE TITLE
NFT Skin Asset Equipment Piece

### ISSUE THREAD

**Issue by Sellie96** [CryptoBlades/cryptoblades#1370]
The Skin system requires a revamp to make them have more value while being different from a special NFT mint, this issue is a recorded document from discord of the features we wish skins to have.

Information from Discussion

Hard Blockers: 
- [ ] Equipment System

Soft Blockers:
- [ ] Mass Minting #1371 

Features of NFT Skins
- [ ] Skins to be a seperate NFT to the weapon / character.
- [ ] Skins can be traded seperately as they are their own NFT.
- [ ] Skins can be equipped onto the character as part of the Equipment System #TBD.
- [ ] Skins can be dequipped from the character as part of the Equipment System.
- [ ] While Equipped, skins will apply universally across all applications so must pull from.
- [ ] Skins equipped to characters can be sold together.
- [ ] Skins can be bridged to other chains both seperately and as part of another NFT.
- [ ] Skins must be able to be sold on the Bazaar.
- [ ] Skins must be able to be minted in the skill shop (Conditionally).
- [ ] Skins must be able to be minted both singularly and at mass by marketing for events #1371  .

**Comment by remocwenn** [comment]
Closed per Philip as the equipment system will make this outdated and unecessary
