### ISSUE TITLE
Add Enrex green carbon widget to CB application

### ISSUE THREAD

**Issue by Sellie96** [CryptoBlades/cryptoblades#1400]
// <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato"> <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Bebas%20Neue"> <div id='badget-hover-box'></div> <p name='39d3428e-48c2-40c7-a06f-8c185a2437cb' side='right' id='badget'><p id='badget-box'></p></p> <script src='https://assets.enrex.io/badget/badget.js'></script> //

Required: Hidden on mobile

Checked: Doesn't interfere with game UI

Potential issue: Interferes with ads

**Comment by kevinunger** [comment]
```
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato"> <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Bebas%20Neue"> <div id='badget-hover-box'></div> <p name='39d3428e-48c2-40c7-a06f-8c185a2437cb' side='right' id='badget'><p id='badget-box'></p></p> <script src='https://assets.enrex.io/badget/badget.js'></script>
```
