### ISSUE TITLE
Equipment manager

### ISSUE THREAD

**Issue by poshdan** [CryptoBlades/cryptoblades#1450]
Equipment manager is going to be a smart contract that will allow users to assign connections between NFTs and generate some precalculated values (mainly power) for use in many other places of the game, thus saving gas without adding constant overhead for each new element.
Design goals include generalizing the inputs (meaning, multiple types of NFTs could potentially go into a particular slot), and storing values efficiently (in a vars mapping) without making commitments to state variables.
In all likelyhood equipment is going to be "versioned", meaning it would require a re-calculation when we adjust the components, thus needing the user to re-run the equip check transaction. (this prevents potentially harmful outcomes when using new values and deprecating old ones)
We might need to put external NFTs into escrow as we cannot put a busy var on them to prevent transfer after equipping. May have an issue if the NFT contract prevents holding more than a certain amount in a single wallet.
It's possible we might need proxy contracts for calculating values per-nft type (similar to nft bridge) so as to avoid size limits on the equipment manager itself.

Example use case:
-user equips weapon, the fight power is calculated for each possible enemy element, and on fighting, only that precalculated value needs to be accessed, making fights cheaper, so long as you don't un/re equip frequently.
-since weapons and all other nfts are attached to the character, we don't need external steps to get values from those. You could have 10 equipped NFTs and to enter a raid or pvp arena, you only need to grab a few numbers from the character vars itself.

Somewhat related #1370

**Comment by ed3ath** [comment]
Things needed to clarify:

1. "You could have 10 equipped NFTs" - Does this mean you could equip 10 nfts of the same type (Ex. 10 weapons) or different?
2. "We might need to put external NFTs into escrow" - Can we implement this with CB's nfts aswell? (Lesser contract size)

**Comment by poshdan** [comment]
After some discussion, a number of things have been finalized, so here's a technical documentation:

-Dynamic number of equipment slots (we should be able to release more slots over time)
-Equipped items will be held in escrow (solves transfer/modification issues without bloating contracts with checks, has the downside that you need to unequip to apply dust on a weapon, for instance)
-Multiple types of NFTs could go into one slot. We'll specify supported addresses per slot (so we could have an external nft equipped as a weapon). And we will specify the method of calculations for that type of address (cb weapons going through weapons contract to get stats, cryptokitties going through our own proxy interface to get some numbers with whatever info we have available
-Stat calculation should never be left to external contracts not governed by the cryptoblades team - it's a security risk if they can upgrade their contract to break the game or add unfair numbers
-A version variable will have to track for each character the "era" of their equipment bonuses. If at some point we change the calculation algorithms, the old numbers will have to be redone per character. This will be a minor burden for the player, hopefully not something we'll have to do very often at all.
