### ISSUE TITLE
Chain Config variable for limiting dynamic transactions

### ISSUE THREAD

**Issue by Sellie96** [CryptoBlades/cryptoblades#1455]
Add a variable to the app config to enable / disable dynamic minting depending on chain.

Aurora does not allow for dynamic transactions so we will limit the transactions to 1 for 1 in dynamic cases. For example; 1 Weapon burned at a time. 1 Character burned at a time. 

Currently only applies to Aurora Chain due to their gas limitations.

Requirements:
- Variable added to app config.
- FE to only allow the selection of one at a time if the variable is true.
- FE Notification explaining why this is the case on this specific chain.

**Comment by Chriserus** [comment]
Done by @Sh37ma in #1521
