### ISSUE TITLE
Scrape historical fight data

### ISSUE THREAD

**Issue by crypto-smoke** [CryptoBlades/cryptoblades#149]
Leaderboard will need historical fight data. API will probably have an endpoint to accept scraped data and store it. 

Recommended data to store in the database:

- timestamp or block number
- transaction hash
- account address
- character ID
  - character level at that time 
- weapon ID
  - full weapon stats at that time
- enemy ID
- fight outcome data
  - victory boolean
  - enemy roll
  - player roll
  - xp gain
  - skill gain

**Comment by seiyria** [comment]
my only rec would be to also include who won explicitly so it can be queried, counted, and sorted on

**Comment by crypto-smoke** [comment]
updated initial post with that 👍

**Comment by seiyria** [comment]
done
