### ISSUE TITLE
Blacksmith forge prices not initialized on initial mount

### ISSUE THREAD

**Issue by byyyyyyyyy** [CryptoBlades/cryptoblades#1500]
Upon directly loading to blacksmith, some data we're not initialized even though they we're supposed to. 
Might be because the component mounts before the contracts we're initialized. 
![image](https://user-images.githubusercontent.com/88365848/173625272-e7a3c2f2-d825-4bc4-9c61-8d8f325bb42c.png)

**Comment by kevinunger** [comment]
@Spintacle123 Can you add a skeleton loader here as well, like in #1496 .
Just flip a bool after `updateMintWeaponFee()` and the check for that in L198, where you display a skeleton loader animation instead of show `0 SKILL`

**Comment by Spintacle123** [comment]
> 

noted. will do.
