### ISSUE TITLE
Create bot instances for SKALE network on Heroku (raid, pvp, etc)

### ISSUE THREAD

**Issue by poshdan** [CryptoBlades/cryptoblades#1518]
Pretty straightforward, you can copy almost everything from the other network's instances, you'll need the SKALE RPC url and the relevant contract addresses.

The two big ones to hit are the raid and pvp bots, but bridge is to be set up as well.

The bot wallets will need funding:
Raid 0x1e2203EC5C329155c442D780D104170886682DC6
Pvp 0xC24658012D08a8A575Aa140C7EE45e83c9100F73
The raid bot uses like 350k gas per 8 hour cycle, so fund according to that.
The pvp one is more unpredictable but is gonna be funded back by the contract, just needs some initial lubrication

**Comment by bilbolPrime** [comment]
@kcper can you please send some mainnet SKALE to those two wallets when possible plz

**Comment by bilbolPrime** [comment]
raid bot deployed to heroku but not turned on. Waiting for gameadmin role, funding and green light
