### ISSUE TITLE
Rework flow for active hero

### ISSUE THREAD

**Issue by seiyria** [CryptoBlades/cryptoblades#152]
Lots of complaints about it being in the right. Maybe we can try left side, horizontal list, under the currently active hero.

It would also be good to show (x/200) for their max stamina next to their name.

**Comment by Nizzypal** [comment]
Do we mean like this? @seiyria 
![image](https://user-images.githubusercontent.com/2307123/124134950-3957a100-da38-11eb-9684-fddea70d6be2.png)
this

**Comment by seiyria** [comment]
Yes, but it should also be horizontal, underneath, and show stamina. It looks claimed, though, so you'll want to coordinate this if you were going to help.

**Comment by Nizzypal** [comment]
so you mean the names  would  be side-by-side with stamina bars underneath  the names?
@seiyria

**Comment by seiyria** [comment]
There are a few ways to approach it. All of them could say: Lepeduin Naik Lv. 1 (200/200)

There could also be a little bar underneath them that visually showed how much stamina they had. 

I think the first one is the right approach though for now. Side by side, underneath it on the left. Just moving it and adding the new text.

**Comment by Steart** [comment]
Will make a PR for this issue tonight(Atleast for me it is night).

**Comment by Steart** [comment]
![Screenshot_20210702_031234](https://user-images.githubusercontent.com/41158626/124231872-25cc3900-db11-11eb-95a3-c1e87767e27f.png)
![Screenshot_20210702_031301](https://user-images.githubusercontent.com/41158626/124231875-2664cf80-db11-11eb-9f6a-c26b670c2766.png)
![Screenshot_20210702_031619](https://user-images.githubusercontent.com/41158626/124231876-2664cf80-db11-11eb-92da-bdb5c2d947e7.png)

This my progress until this far, only have to fix the problem with the seperate staminas.
