### ISSUE TITLE
1.1.5) Query params reset on router-link

### ISSUE THREAD

**Issue by kevinunger** [CryptoBlades/cryptoblades#1522]
to replicate:
- go to https://app.cryptoblades.io/#/?chain=BNB
- click any router link --> ?chain=BNB disappears 

possible cause:
- probably a bug with `checkChainAndParams()` in `App.vue`

Please fix that on `multi-wallet` branch or on main when `multi-wallet` is merged.

**Comment by jakehein** [comment]
Is this currently being tackled on any working branch, or is this issue still open?

**Comment by MrBaptista69** [comment]
Replaced with #1794

**Comment by Alex43ice** [comment]
****
