### ISSUE TITLE
List Cryptoblades on DeFi Llana

### ISSUE THREAD

**Issue by MrBaptista69** [CryptoBlades/cryptoblades#1566]
+What: List CryptoBlades on DeFi Llama

+How: Follow the directions laid out in the link below
https://docs.llama.fi/list-your-project/submit-a-project

+Where: This will be done in the DeFi Llama github repo linked below
https://github.com/DefiLlama/DefiLlama-Adapters for our eventual launch to KAVA

+Why: We were asked to register with DeFi Llama so we would show up on the KAVA chain per the KAVA team

+Priority: This is not a top priority , but should be looked after within a week.

**Comment by kcper** [comment]
https://github.com/DefiLlama/DefiLlama-Adapters/pull/3479
