### ISSUE TITLE
[BUG] - Admin Panel - Wrong Element gets minted

### ISSUE THREAD

**Issue by MrBaptista69** [CryptoBlades/cryptoblades#1574]
### Prerequisites

- [X] I have refreshed the chain and am still experiencing the bug
- [X] I have confirmed I am on the correct chain
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository

### Contact Details

CC - ENGLISHH

### What does this bug relate to

Incorrect Data

### Describe the bug

When selecting and element on the weapon giveaways the selected element doesn't match up to what's being minted

### Expected behavior

The element selected should mint the correct element.

### Current behavior

Water selection produces Earth
Earth Selection produces lightning
lightning selection produces water
Fire selection produces fire

### To Reproduce

go to admin panel
input address, input 1* weapon, Input chosen element
after I click mint I recieved the wrong element
Also happened after I minted a 5* giveaway weapon for events.

### Device

PC

### Browser

Chrome

**Comment by remocwenn** [comment]
Verify if this is still an issue.  Have Levitate see if this is still happening.

**Comment by MrBaptista69** [comment]
it has been reported that it works as intended. However, we will keep monitoring it and if it happens again, I will re-open the ticket
