### ISSUE TITLE
sFuel station for SKALE

### ISSUE THREAD

**Issue by MrBaptista69** [CryptoBlades/cryptoblades#1576]
The sFuel station will allow users to claim sFuel outside of our Discord and is medium priority.

sFuel Station
Mainnet: https://sfuel.mylilius.com/
Testnet: https://testnet.station.mylilius.com/
Documentation on setup: https://docs.mylilius.com/

**Comment by MrBaptista69** [comment]
I believe that there should be a discussion between SKALE and us(most precisely with the dev who will be assigned with the task) for more info or for helping us out, in Telegram.

**Comment by kcper** [comment]
Done, now waiting for getting added in the front-end.

**Comment by kcper** [comment]
Done https://sfuel.mylilius.com/
