### ISSUE TITLE
Background does not fit height

### ISSUE THREAD

**Issue by kevinunger** [CryptoBlades/cryptoblades#1593]
Quests:
Mounted:
![image](https://user-images.githubusercontent.com/5601589/185198884-b181dd58-d1ee-4ada-b9a9-a21330ab950c.png)
Loaded:
![image](https://user-images.githubusercontent.com/5601589/185199185-4c2deaeb-323c-470e-b455-cc42769e4294.png)

Bridge:
![image](https://user-images.githubusercontent.com/5601589/185199308-9939d012-bf46-4efd-a3e5-9c963d6ae5d3.png)

Blacksmith:
![image](https://user-images.githubusercontent.com/5601589/185199345-506e9a7d-f20d-47d8-9276-250c422f0917.png)

Leaderboard:
![image](https://user-images.githubusercontent.com/5601589/185199407-293ee4a0-3f79-4829-b6df-15b5043abeb8.png)

Note:
Maybe set display:flex on .app and flex:1 the content. Use a wrapper for the background images on each page. Width: clamp() the content.
There are also some overflow-x issues on most sites. Reason might be the amount of div nesting. Probably can be simplified to make life easier.

**Comment by jakehein** [comment]
@kevinunger can you be more specific what overflow-x issues are present? Maybe just an example so I know what exactly I should be searching for in this regard.

**Comment by kevinunger** [comment]
@jakehein 
The whole content container is overflowing on smaller screens. Somewhere a width is wrongly set. Maybe the .blank-slate class? It has width: calc(100vw - 36px); set. 
![image](https://user-images.githubusercontent.com/5601589/186629763-4d6869da-0146-4634-929e-c706bd64b86f.png)
