### ISSUE TITLE
Add indicator for amount of SFUEL on account

### ISSUE THREAD

**Issue by kevinunger** [CryptoBlades/cryptoblades#1600]
SFUEL can be claimed on https://sfuel.mylilius.com/
- [x] Add an indicator for the amount of SFUEL on the user account; like so:
![image](https://user-images.githubusercontent.com/5601589/186264490-96dc0197-33c4-4644-97d2-bfb7ee09ca20.png)
- [x] Link to https://sfuel.mylilius.com/ when clicking the (+)-sign
- [x] Update the chain instructions (en.json) to let user know that they can claim SFUEL on https://sfuel.mylilius.com/ (like here: https://github.com/CryptoBlades/cryptoblades/pull/1597)

Note:
- Add `FetchBalance` (or a smiliar name) as a vuex action in store.ts
- Dispatch it whenever fetchSkillBalance is called

https://github.com/CryptoBlades/cryptoblades/blob/81d677cb27fa881e599356e3c22d4ed421e4a4b9/frontend/src/store/store.ts#L1018-L1035

- Do not hardcode the native currency symbol. This can be taken from the config while checking for the chainId/net (use getConfigValue(...))
- Use the .getBalance function of web3 js and round to 4 decimal points

**Comment by pudgefury** [comment]
Could I handle this task?
