### ISSUE TITLE
Add the drawbridge as the option to buy SKILL on SKALE

### ISSUE THREAD

**Issue by kevinunger** [CryptoBlades/cryptoblades#1601]
![image](https://user-images.githubusercontent.com/5601589/186266402-22fa77be-b984-411e-a66c-df0f9116f7c6.png)

There is no way to buy SKILL directly on SKALE. We can link to our drawbridge, when a user tries to buy SKILL on SKALE.

- [ ] When clicking 'Buy SKILL' while connected to SKALE, link to our [drawbridge ](https://drawbridge.cryptoblades.io/)

**Comment by pudgefury** [comment]
Could I handle this task?
