### ISSUE TITLE
Feedback from Prom - Beta

### ISSUE THREAD

**Issue by MrBaptista69** [CryptoBlades/cryptoblades#1604]
- probably due to a time out where they now need to reroll an opponent, this should probably have some type of pop up so it is more clear
![image](https://user-images.githubusercontent.com/11393767/187427973-12937f4c-ed29-4947-831e-57ef98eb6708.png)

- they probably had a character/weapon double committed, we should have a more clear message pop up 
![image](https://user-images.githubusercontent.com/11393767/187428232-9018ee6e-f5f7-4296-a2de-6d63ccdbf1de.png)

- it is a good point that there should be a message that indicates the transfer has been completed
![image](https://user-images.githubusercontent.com/11393767/187428424-07d4f616-aebb-481c-bdc6-4e35fbcf4376.png)

**Comment by pudgefury** [comment]
Could I handle this task?

**Comment by remocwenn** [comment]
Split this into multiple issues (singular task units) following the template.
Verify that these are still issues.
Issues should be made into low priority.
