### ISSUE TITLE
Excessive reloading on quest page

### ISSUE THREAD

**Issue by poshdan** [CryptoBlades/cryptoblades#1639]
Since the UI overhaul (i think), the quest page keeps refreshing completely after almost every interaction with a quest: hitting submit, complete and even hitting cancel on a submit modal.
I understand that some users like to multitask, and this could be a way to make it foulproof where otherwise a desync in current network or wallet address could cause inconvenience, but I think a complete refresh is overkill.

How about this: On clicking any quest button, run a quick check on current network & address compared to a cached value in the app, and refresh the page if there is a mismatch. Otherwise do nothing. I'm open to hearing arguments against it or better suggestions, please contact on discord

**Comment by jakehein** [comment]
@poshdan Where do we cache the value of the current network and address?
