### ISSUE TITLE
Rework battle target ui

### ISSUE THREAD

**Issue by seiyria** [CryptoBlades/cryptoblades#165]
Move text onto the image like characters. Victort chance and xp gain for sure.

**Comment by Nizzypal** [comment]
![image](https://user-images.githubusercontent.com/2307123/124075949-74d37a80-d9fa-11eb-9150-938905c2afee.png)

@seiyria Is Victory Chance  to be  put there?

**Comment by seiyria** [comment]
Sorry. I meant to self assign this but forgot. I plan to take care of this myself today!

**Comment by Nizzypal** [comment]
ok
