### ISSUE TITLE
show all 4 characters in quick access menu, highlight the active one

### ISSUE THREAD

**Issue by seiyria** [CryptoBlades/cryptoblades#167]
https://cryptoblades.hellonext.co/b/Suggestions/p/highlight-selected-character-insted-of-removing-it

perhaps make it less opaque or a more defined background, but not a bright yellow outline

**Comment by Nizzypal** [comment]
This good?
![image](https://user-images.githubusercontent.com/2307123/124177188-bb5dbf00-da64-11eb-8777-cf31f43d977f.png)

**Comment by seiyria** [comment]
That looks fine for now.
