### ISSUE TITLE
[Feature] - notification center

### ISSUE THREAD

**Issue by seiyria** [CryptoBlades/cryptoblades#1672]
### Prerequisites

- [X] I checked to make sure that this feature has not already been filed
- [X] I'm reporting this information to the correct repository
- [X] I understand enough about this issue to complete a comprehensive document

### Describe the feature and its requirements

![image](https://user-images.githubusercontent.com/763609/193883685-1fadef8b-b96d-4680-8ef4-5c4b39f9c65e.png)

the goal here is to make a facebook notification center-styled area. we have an API available that currently generates pnotify popups in the top right, but this should be transformed into a more persistent location. the requirements are as follows:

- [x] show the last 10 notifications from the API, title and text only (that should be all the API has available)
- [x] track notification viewing for the last 10 notifications locally, so users can see what notifications have been clicked by them. 
	- [x] this status should update on click, as well as navigate the user to the specific blog post
	- [x] there should be a "mark all as read" button as well  
- [x] the notification panel should cover about half the screen vertically, then scroll

### Is your feature request related to an existing issue? Please describe.

no

### Is there anything stopping this feature being completed?

no

### Describe alternatives you've considered

we have a basic system in place that is functional, but is not a good long term solution

**Comment by jakehein** [comment]
Do we want updates added to the hamburger menu as well? And to verify, this is taking the place of this monstrosity, correct? 
![image](https://user-images.githubusercontent.com/32526235/193916764-9b34bc71-5f39-4857-8543-2c498c1bd9d9.png)
Also do we have a bell icon?

**Comment by seiyria** [comment]
Yes, it is replacing that.

Probably no to the sidebar.

No icon; we might have to grab one from font awesome or similar.

**Comment by jakehein** [comment]
We will likely want this to be exempt from the collaping nav-bar then, since it wouldn't be viewable on mobile if this isn't included in the #hambaga menu, as things currently stand. I have maintainability concerns about this regarding potential horizontal overflow. Cross that bridge when I get there I suppose though.
