### ISSUE TITLE
streak rewards for combat

### ISSUE THREAD

**Issue by seiyria** [CryptoBlades/cryptoblades#169]
https://cryptoblades.hellonext.co/b/Suggestions/p/rewards-for-a-string-of-unbeaten-fights

**Comment by Nizzypal** [comment]
@seiyria How bout this?

**Comment by seiyria** [comment]
if you think you can do it, go for it. I have no concept of estimating effort when it comes to contract related code.

**Comment by Nizzypal** [comment]
alrighty...

**Comment by Nizzypal** [comment]
Any details on how much xp?  Does  the reward grow with the streak  or is it a static amount?

**Comment by seiyria** [comment]
given that combat can be 100% win, this is probably a thing that compounds too much.
