### ISSUE TITLE
FE adjustements for Quests 

### ISSUE THREAD

**Issue by MrBaptista69** [CryptoBlades/cryptoblades#1700]
-create tabs on quest page that switch between showing wallet quests or pickable quests (only show "common tier", others are not implemented yet)
-the pickable quest tab should have a checkbox next to each quest, single selection between all, where you choose the next quest for the next character you skip or complete a quest with. Have a "random" option at the top, this should be the default. Perhaps add a button that shows you the list of random quests (same behavior as the available quests button, which might become redundant at this point)

Ideally, if we had few random quests, we could list those too next to the random checkbox, but this isn't very trivial to do.
The checkbox replaces the toggle below the skip/complete quest on the character quest modals

-reduce whitespace on wallet/pickable quest lists, maybe fit two columns of quests side-by-side on PC
-remove reputation icon for wallet quests (it's irrelevant)

**Comment by poshdan** [comment]
Consult with me on discord PoshDan#7875 if unsure about some aspects or discuss alternate solutions

**Comment by Chriserus** [comment]
And consult with me Chriserus#4523 if you have any questions regarding quests :D (and quests frontend)
