### ISSUE TITLE
Busy var prevents quest interaction

### ISSUE THREAD

**Issue by poshdan** [CryptoBlades/cryptoblades#1702]
<img width="874" alt="2022-10-20_12-20-28_chrome" src="https://user-images.githubusercontent.com/31659034/196923381-adfe0259-b8da-4bfa-9284-0b5aaba5ffaa.png">
This shouldn't be the case. The contract doesn't actually prevent interaction due to busy status, this is a frontend-only limitation (an unnecessary one).

**Comment by MrBaptista69** [comment]
Has been replaced with ticket #1791
