### ISSUE TITLE
[BUG] - Not showing SKILL  as an asset for all the players in the Drawbridge

### ISSUE THREAD

**Issue by MrBaptista69** [CryptoBlades/cryptoblades#1705]
### Prerequisites

- [X] I have refreshed the chain and am still experiencing the bug
- [X] I have confirmed I am on the correct chain
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository

### Contact Details

Levitate

### What does this bug relate to

Missing Features

### Describe the bug

DRAWBRIDGE ISSUE:
from BNB network ==> COINEX Network = No Asset Showing

Has been reported by many players

### Expected behavior

Show SKILL as an asset

### Current behavior

In all browsers, the SKILL is not showing as an asset(in Brave and Chrome has been tested)

### To Reproduce

Open up drawbridge, select chains and you cant select an asset

### Device

PC

### Browser

Chrome

### Additional Context

![image](https://user-images.githubusercontent.com/11393767/197011933-a4ddb915-d281-4327-af79-e1ef8edbf457.png)
![image](https://user-images.githubusercontent.com/11393767/197011969-ec02bac8-e582-429a-9efc-b96cae10894a.png)
![image](https://user-images.githubusercontent.com/11393767/197012199-64179846-e16f-4d63-b93b-27d309548403.png)

**Comment by kevinunger** [comment]
fixed with https://github.com/CryptoBlades/drawbridge/commit/8a97daf8ab663836cc947387d312ff5aed19ea6d
