### ISSUE TITLE
Increase Gas Offset $0.02 on BNB Chain

### ISSUE THREAD

**Issue by devinep52** [CryptoBlades/cryptoblades#1706]
### Prerequisites

- [X] I checked to make sure that this feature has not already been filed
- [X] I'm reporting this information to the correct repository
- [X] I understand enough about this issue to complete a comprehensive document

### Describe the feature and its requirements

Increase the Gas Offset by $0.02 so that all characters, Gen 1 and Gen 2 are profitable on BNB chain

### Is your feature request related to an existing issue? Please describe.

No

### Is there anything stopping this feature being completed?

No

### Describe alternatives you've considered

No

**Comment by kcper** [comment]
Done, vars[VAR_GAS_OFFSET_PER_FIGHT_MULTIPLIER] changed from 21000000000000000 to 23250000000000000.
