### ISSUE TITLE
[Feature] - Get amount of Gen 2 on each chain

### ISSUE THREAD

**Issue by MrBaptista69** [CryptoBlades/cryptoblades#1715]
### Prerequisites

- [X] I checked to make sure that this feature has not already been filed
- [X] I'm reporting this information to the correct repository
- [X] I understand enough about this issue to complete a comprehensive document

### Describe the feature and its requirements

-We need to know how many gen2 characters are on each chain so that we can start to make calculations based upon how much VALOR to be added to the multi-farms on each chain.  This can be a script just so we have some basic analytics for now on this data point. 

### Is your feature request related to an existing issue? Please describe.

Nope

### Is there anything stopping this feature being completed?

Nope

### Describe alternatives you've considered

None

**Comment by kcper** [comment]
bsc 10700
polygon 165
avax 2
aurora 0
skale 239
okex 2521
heco 387
coinex 7

**Comment by kcper** [comment]
Script pushed to taloner-scripts branch for future reference
