### ISSUE TITLE
[Feature] - Adding Eric in our team's page in all of our sites

### ISSUE THREAD

**Issue by MrBaptista69** [CryptoBlades/cryptoblades#1723]
### Prerequisites

- [X] I checked to make sure that this feature has not already been filed
- [X] I'm reporting this information to the correct repository
- [X] I understand enough about this issue to complete a comprehensive document

### Describe the feature and its requirements

We need to add Erik in team's page in all of our websites, CB, CBK, Riveted Games, etc

Erik Lagerway - CSO
![image](https://user-images.githubusercontent.com/11393767/197325156-2939ed82-0145-4db5-b679-be23e9d525ce.png)

### Is your feature request related to an existing issue? Please describe.

N/A

### Is there anything stopping this feature being completed?

N/A

### Describe alternatives you've considered

N/A

**Comment by kevinunger** [comment]
@MrBaptista69 Bolstyr landing page as well?

**Comment by MrBaptista69** [comment]
as far as I have been informed, to all the pages that include the team page

**Comment by kevinunger** [comment]
done added to
asension pad, cbk, cb, riveted and bolstyr
