### ISSUE TITLE
[Feature] - Add $.02/200 Stamina to Gas Offset On BNB Chain

### ISSUE THREAD

**Issue by devinep52** [CryptoBlades/cryptoblades#1725]
### Prerequisites

- [X] I checked to make sure that this feature has not already been filed
- [X] I'm reporting this information to the correct repository
- [X] I understand enough about this issue to complete a comprehensive document

### Describe the feature and its requirements

Add $.02/200 Stamina to Gas Offset On BNB Chain

### Is your feature request related to an existing issue? Please describe.

NO

### Is there anything stopping this feature being completed?

No

### Describe alternatives you've considered

Nada

**Comment by kcper** [comment]
Done yesterday.
