### ISSUE TITLE
[Feature] - Turn Off Bridge Fee BNB

### ISSUE THREAD

**Issue by devinep52** [CryptoBlades/cryptoblades#1730]
### Prerequisites

- [X] I checked to make sure that this feature has not already been filed
- [X] I'm reporting this information to the correct repository
- [X] I understand enough about this issue to complete a comprehensive document

### Describe the feature and its requirements

Turn Off Bridge Fee on BNB, and re-enable when the bonus BNB allotment is finished

### Is your feature request related to an existing issue? Please describe.

No

### Is there anything stopping this feature being completed?

No

### Describe alternatives you've considered

No

### Additional context

No

**Comment by kcper** [comment]
Done for characters and weapons.
