### ISSUE TITLE
[Feature] - 10,000 Valor Pool Expiring November 1 on BNB

### ISSUE THREAD

**Issue by devinep52** [CryptoBlades/cryptoblades#1731]
### Prerequisites

- [X] I checked to make sure that this feature has not already been filed
- [X] I'm reporting this information to the correct repository
- [X] I understand enough about this issue to complete a comprehensive document

### Describe the feature and its requirements

Create a 10,000 Valor Pool Expiring November 1 on BNB Chain

### Is your feature request related to an existing issue? Please describe.

no

### Is there anything stopping this feature being completed?

no

### Describe alternatives you've considered

no

**Comment by kcper** [comment]
Instructions provided to @remocwenn

**Comment by kcper** [comment]
Done.
![image](https://user-images.githubusercontent.com/9114200/198271610-68850263-5419-470c-ba0a-dabcc21bb8f2.png)
