### ISSUE TITLE
[BUG] - Design issue with the Ambassadors at the Bolstyr page

### ISSUE THREAD

**Issue by MrBaptista69** [CryptoBlades/cryptoblades#1733]
### Prerequisites

- [X] I have refreshed the chain and am still experiencing the bug
- [X] I have confirmed I am on the correct chain
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository

### Contact Details

Isabel

### What does this bug relate to

Design Issues

### Describe the bug

At the Bolstyr page, one of the ambassador's is multiple times.

### Expected behavior

Having the ambassador only once

### Current behavior

we have him 4 times

### To Reproduce

Visiting the Bolstyr page

### Device

PC

### Browser

Chrome

### Additional Context

![image](https://user-images.githubusercontent.com/11393767/198070193-fdee12c2-3bcc-4777-82f2-a84d5012a52a.png)

**Comment by kevinunger** [comment]
fixed
