### ISSUE TITLE
[Feature] - BNB Rewards Pool Refills - November 2022

### ISSUE THREAD

**Issue by remocwenn** [CryptoBlades/cryptoblades#1744]
### Prerequisites

- [X] I checked to make sure that this feature has not already been filed
- [X] I'm reporting this information to the correct repository
- [X] I understand enough about this issue to complete a comprehensive document

### Describe the feature and its requirements

The following tokens and their respective amounts are to be added to the BNB treasury at address 0x812Fa2f7d89e5d837450702bd51120920dccaA99

BNB Multi-farms:
Gen 1
   SKILL 28,000
   KING 10,000,000

Gen 2
   VALOR 120,000

### Is your feature request related to an existing issue? Please describe.

This is a process that repeated each time the multi-farm pools are depleated. 

### Is there anything stopping this feature being completed?

Taloner is to take care of the VALOR and Philip is to provide the necessary SKILL and KING

### Describe alternatives you've considered

N/A

### Additional context

This is only for BNB chain.  The other chains will need to be refilled in the coming days as well.

This spreadsheet was used to calcuate values for the refill: 
https://docs.google.com/spreadsheets/d/19sd8R93IE3PzV_nuS1udGJ_C-sRBpPhJSpGJzbxvlHY/edit?usp=sharing

**Comment by kcper** [comment]
![image](https://user-images.githubusercontent.com/9114200/199090391-c4fdb9a2-6bee-4a2f-86ba-44b7bdea71e8.png)
![image](https://user-images.githubusercontent.com/9114200/199090404-e4a976c2-f72e-44e7-bab7-57fdcbd3a64d.png)
