### ISSUE TITLE
[Feature] - Updated CryptoBlades Event Banner for BladesGiving

### ISSUE THREAD

**Issue by remocwenn** [CryptoBlades/cryptoblades#1755]
### Prerequisites

- [X] I checked to make sure that this feature has not already been filed
- [X] I'm reporting this information to the correct repository
- [X] I understand enough about this issue to complete a comprehensive document

### Describe the feature and its requirements

The OctoBlades banner needs to be removed and replaced with the BladesGiving banner.
![image](https://user-images.githubusercontent.com/90266559/199827044-e5d523b9-c9d2-4e82-9401-badb8c64e22c.png)
![BladesGiving Homepage Banner](https://user-images.githubusercontent.com/90266559/199827181-38f2071c-7fa7-4601-a0c0-fe3a689a30dc.png)

The location should remane the same on the site, but please use the following link for when people click on the banner:
https://app.cryptoblades.io/?utm_source=sitebanner&utm_medium=navban&utm_campaign=bnb#%2F%3Fchain=BSC

### Is your feature request related to an existing issue? Please describe.

No

### Is there anything stopping this feature being completed?

No

### Describe alternatives you've considered

No alternatives at this time.

### Additional context

N/A

**Comment by kevinunger** [comment]
Done with https://github.com/CryptoBlades/cryptoblades-landing-page/commit/d2bd07e0223ca3813e7127f7eca431123cbe178b & https://github.com/CryptoBlades/cryptoblades-landing-page/commit/58b651bee09b6145280b164f581db609ded1fe28

- swapped the banner
- changed the link
