### ISSUE TITLE
[BUG] - Deleting quest template with wrong tier parameter will delete the wrong quest

### ISSUE THREAD

**Issue by MrBaptista69** [CryptoBlades/cryptoblades#1768]
### Prerequisites

- [X] I have refreshed the chain and am still experiencing the bug
- [X] I have confirmed I am on the correct chain
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository

### What does this bug relate to

Incorrect Data

### Describe the bug

(This ticket replaces the ticket 1583)
Deleting quest template with wrong tier parameter will delete the wrong quest. 
Calling SimpleQuests.deleteQuestTemplate(tier,questID) with the wrong tier parameter will delete an unexpected quest from the given (false) tier.
This is technically "user error", but we ran into it while testing some quests, so it would be well worth preventing in the future.
Probably just need
require(questID == questTemplates[tier][questIndex])

But it would be also prudent to maybe zero-out the values for the quest if the last one in the array was the quest that we're deleting.

### Expected behavior

To not delete the wrong quest

### Current behavior

Deleting quest template with wrong tier parameter will delete the wrong quest

### To Reproduce

Deleting quest template with wrong tier parameter will delete the wrong quest

### Device

PC

### Browser

Chrome

**Comment by Chriserus** [comment]
If this is still the case, it should be corrected on admin panel side, contract shouldn't be adjusted imo, garbage data in, garbage data out.
