### ISSUE TITLE
[Feature] - Launch on Meter

### ISSUE THREAD

**Issue by MrBaptista69** [CryptoBlades/cryptoblades#1770]
### Prerequisites

- [X] I checked to make sure that this feature has not already been filed
- [X] I'm reporting this information to the correct repository
- [X] I understand enough about this issue to complete a comprehensive document

### Describe the feature and its requirements

Launching on Meter
Meter Website:
https://meter.io/

Developer Documents:
https://docs.meter.io/developer-documentation/introduction

### Is your feature request related to an existing issue? Please describe.

None

### Is there anything stopping this feature being completed?

None

### Describe alternatives you've considered

none

**Comment by kcper** [comment]
Deployed https://github.com/CryptoBlades/cryptoblades/commit/a7180afc8bfdc74a5450cc1c6362cafd627a0f26
Launch will happen via updating the config file.
