### ISSUE TITLE
[Feature] - CSC SKILL Rewards

### ISSUE THREAD

**Issue by remocwenn** [CryptoBlades/cryptoblades#1781]
### Prerequisites

- [X] I checked to make sure that this feature has not already been filed
- [X] I'm reporting this information to the correct repository
- [X] I understand enough about this issue to complete a comprehensive document

### Describe the feature and its requirements

Adding SKILL rewards on CoinEx Smart Chain
Amount: 300 SKILL for gen1 characters

### Is your feature request related to an existing issue? Please describe.

No

### Is there anything stopping this feature being completed?

No

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by MrBaptista69** [comment]
@kcper If it can be communicated with marketing once added, it is appreciated
