### ISSUE TITLE
[Feature] - Remove Seedify from platforms

### ISSUE THREAD

**Issue by YimitKEQ** [CryptoBlades/cryptoblades#1784]
### Prerequisites

- [X] I checked to make sure that this feature has not already been filed
- [X] I'm reporting this information to the correct repository
- [X] I understand enough about this issue to complete a comprehensive document

### Describe the feature and its requirements

Please remove any logo and/or affiliation visible with Seedify on any of out platforms.

https://cryptobladeskingdoms.io/

Bottom of the CBK page.
![image](https://user-images.githubusercontent.com/79701960/203086767-1fe5a057-5080-4536-8038-cddd0968dd29.png)

### Is your feature request related to an existing issue? Please describe.

No

### Is there anything stopping this feature being completed?

No

### Describe alternatives you've considered

None

**Comment by kevinunger** [comment]
- resolved with https://github.com/CryptoBlades/cbk-landing-page/commit/632ebc6fa720ee95d2c82658dd33ee918ee99d2d

**Comment by kevinunger** [comment]
![image](https://user-images.githubusercontent.com/5601589/203097896-6691e52a-742e-4e61-818c-8be22a1306c9.png)
