### ISSUE TITLE
[Feature] - Rebel Poker Domain/Land Page

### ISSUE THREAD

**Issue by MrBaptista69** [CryptoBlades/cryptoblades#1790]
### Prerequisites

- [X] I checked to make sure that this feature has not already been filed
- [X] I'm reporting this information to the correct repository
- [X] I understand enough about this issue to complete a comprehensive document

### Describe the feature and its requirements

We need to create a domain and an HTML Landing Page for the Rebel Poker. 
tavern.cryptoblades.io

### Is your feature request related to an existing issue? Please describe.

Nope

### Is there anything stopping this feature being completed?

None

### Describe alternatives you've considered

None

**Comment by kevinunger** [comment]
Is there a mockup / design?

**Comment by MrBaptista69** [comment]
https://cryptoblades.workinjupiter.club/
This is where they will be sent so I don't think it would have to be anything too complicated.  Nick has attached his pass at a concept.
![image](https://user-images.githubusercontent.com/11393767/203500668-c9afd776-5413-4f90-88ee-bd48254272b0.png)
Thats what the rebels said after we asked them if we need anything specific:
Hi there, nothing in specific. just need a higher res version of the cards for the landing page. 950x1317. Thanks.
I will wait more info from Nick regarding the hg res cards later today

**Comment by remocwenn** [comment]
React version 18.2.0 required per Rebel Poker team
