### ISSUE TITLE
[BUG] - Busy var prevents quest interaction

### ISSUE THREAD

**Issue by MrBaptista69** [CryptoBlades/cryptoblades#1791]
### Prerequisites

- [X] I have refreshed the chain and am still experiencing the bug
- [X] I have confirmed I am on the correct chain
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository

### Contact Details

PoshDan

### What does this bug relate to

Design Issues

### Describe the bug

Busy var prevents quest interaction

### Expected behavior

This shouldn't be the case. The contract doesn't actually prevent interaction due to busy status, this is a frontend-only limitation (an unnecessary one).
![image](https://user-images.githubusercontent.com/11393767/203501169-50d7d5c1-f186-43d2-a0e0-958d6ff9a0e0.png)

### Current behavior

Busy var prevents quest interaction

### To Reproduce

When character is in the arena

### Device

PC

### Browser

Chrome

**Comment by Chriserus** [comment]
The busy var prevents character from using stamina (skipping the quest, stamina submission), we did this one on purpose, if character is busy, you cannot do quests, period. The actual error would happen only when using stamina.
