### ISSUE TITLE
Metamask setup requires refreshing of page

### ISSUE THREAD

**Issue by crypto-smoke** [CryptoBlades/cryptoblades#180]
When setting up a fresh account, the website prompts to install metamask and then connect to BSC but then it doesn't change. It should then prompt to add SKILL token and then ask for approval to let metamask connect to the account. To trigger these last two steps you need to refresh the page again.

**Comment by jeffyzxc** [comment]
anyone working on this?

**Comment by seiyria** [comment]
Nope, all yours!
