### ISSUE TITLE
leaderboard

### ISSUE THREAD

**Issue by seiyria** [CryptoBlades/cryptoblades#181]
highest fight earnings last 24h
sum of fight earnings last 24h
recently sold characters
recently sold weapons
highest value weapon sales of all time
highest value character sales of all time
list of 5stars minted last 24h (+ their count)
list of 4stars minted last 24h (+ their count)
highest level characters
number of characters minted last 24h/week
number of weapons minted last 24h/week
number of weapons burned last 24h/week
number of 4 stars burned last week
number of 5 stars burned last week/ever

**Comment by crypto-smoke** [comment]
Here are the events we can populate the API with. Note that in addition to these fields, we should add the amount of gas used, the block number, and the block timestamp for easier sorting later. None of this data is too terrible to get so if we want to change formats or do a full re-import it wont be too bad. 

Fight outcome:
- Character ID
- Weapon ID
- Enemy ID
- Player Roll
- EnemyRoll
- XP Gain
- Skill Gain
- Owner address

New weapon minted:
- Weapon ID
- Owner address

Weapon reforged:
- Owner address
- Reforged item ID
- Burnt item ID
- New LB, 4B, 5B of sword after reforge

Character minted:
- Owner address
- ID

Character level up:
- Owner address
- Character ID
- Level

Market item listed:
- Seller address
- NFT address
- NFT ID
- Price seller wants

Market item sold:
- Buyer address
- Seller address
- NFT address
- NFT ID
- Price buyer paid 

Market listing cancelled:
- Seller address
- NFT address
- NFT ID

Market listing price change:
- Seller address
- NFT address
- NFT ID
- New price

**Comment by seiyria** [comment]
api should be functional for these https://github.com/CryptoBlades/cryptoblades-api
