### ISSUE TITLE
[Feature] - December SKILL Rewards Refill

### ISSUE THREAD

**Issue by remocwenn** [CryptoBlades/cryptoblades#1819]
### Prerequisites

- [X] I checked to make sure that this feature has not already been filed
- [X] I'm reporting this information to the correct repository
- [X] I understand enough about this issue to complete a comprehensive document

### Describe the feature and its requirements

Rewards need to be added to the following chains
     

- [ ] Polygon 700 SKILL
- [ ] Avax 200 SKILL
- [ ] SKALE 6000 SKILL
- [ ] Aurora 928 SKILL
- [ ] CSC 300 SKILL

### Is your feature request related to an existing issue? Please describe.

Yes
-[1781 CSC SKILL Rewards](https://github.com/CryptoBlades/cryptoblades/issues/1781) was a request for the initial rewards to be added to CSC.  After adding the CSC SKILL rewards as part of this issue, 1781 can be closed as it is redundant. 

-[1769 Reward Refills](https://github.com/CryptoBlades/cryptoblades/issues/1769) was the November rewards refill and that is where the values of the refills for Aurora, Polygon, Avax, and SKALE came from.  Becasue these November rewards were filled, 1769 should be closed.

### Is there anything stopping this feature being completed?

Not that I am aware of

### Describe alternatives you've considered

N/A

### Additional context

The time of these pools being refilled should be communicated with the marketing team.  From what I can see, 
     +Polygon will be empty on 12/08/2022
     +Avax will be empty on 12/08/2022
     +SKALE will be empty on 12/07/2022
     +Aurora will be empty on 12/09/2022
     +CSC is currently empty now

**Comment by kcper** [comment]
Refilled.
