### ISSUE TITLE
[BUG] - Drawbridge issue from Zendesk

### ISSUE THREAD

**Issue by MrBaptista69** [CryptoBlades/cryptoblades#1853]
### Prerequisites

- [ ] I have refreshed the chain and am still experiencing the bug
- [ ] I have confirmed I am on the correct chain
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository

### Contact Details

Solovey1981
mail to: solovey1981.8@gmail.com)

### What does this bug relate to

None of the above

### Describe the bug

How do I contact the support service since the Skill coins have not arrived through the DRAWBRIDGE? A game of CryptoBlades. Discord won't let me in, they can't confirm my number for a week((
Transaction Hash:
0x43b6ed79980cdf3fd7aa08b3c1f3af80332f7841e916bc5b13fdc8d4179a1a84
Wallet BSC:
0x38357e63bAc085C23DBa3778E8431400d5251334

Chain: SKALE

### Expected behavior

10

### Current behavior

0

### To Reproduce

send coins across the bridge

### Device

PC

### Browser

Chrome

### Additional Context

![image](https://user-images.githubusercontent.com/11393767/211377433-e33b8ec4-613f-4cf6-8aca-33adb04c9e75.png)

**Comment by remocwenn** [comment]
More SKILL is just needed on BNB side of the bridge.
