### ISSUE TITLE
using trust wallet instead of metamask never lets a user play the game

### ISSUE THREAD

**Issue by seiyria** [CryptoBlades/cryptoblades#187]
onboarding will need to be fixed to reflect this, some changes that are metamask specific will need to be changed to work with both

**Comment by newb23** [comment]
I assume this came from a complaint on someone running the mobile version through Trust Wallet? Or were they trying to use the site proper... with the Trust Wallet app?

**Comment by seiyria** [comment]
I've got no idea, honestly. You'll have to ask around - maybe someone else knows? I've never even heard of trust wallet.

**Comment by newb23** [comment]
Its a mobile only application, which is why I was looking for the clarification. :D I'll ask around the Discord.

**Comment by crypto-smoke** [comment]
I've seen at least one person on discord say they play the game fine using the trustwallet app and built in browser.

**Comment by newb23** [comment]
Thanks Smoke, I'll do some diggin'.

**Comment by newb23** [comment]
Closed with #256? Never did reproduce.
