### ISSUE TITLE
[BUG] - Infinite XP bug for Combat re-appeared

### ISSUE THREAD

**Issue by MrBaptista69** [CryptoBlades/cryptoblades#1873]
### Prerequisites

- [ ] I have refreshed the chain and am still experiencing the bug
- [ ] I have confirmed I am on the correct chain
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository

### Contact Details

Nick

### What does this bug relate to

Design Issues

### Describe the bug

The infinite bug from the combat is back

### Expected behavior

Not having it

### Current behavior

Showing the proper exp

### To Reproduce

At the combat page

### Device

PC

### Browser

Chrome

### Additional Context

![image](https://user-images.githubusercontent.com/11393767/217908818-a07e94fa-8a9d-4ae8-9bfa-09e9f0907fcb.png)

**Comment by Lesenus** [comment]
It's showing after attach weapon to the character and switch to combat without reload the page
