### ISSUE TITLE
market improvement: auctions

### ISSUE THREAD

**Issue by seiyria** [CryptoBlades/cryptoblades#188]
This is blocked by #617

**Comment by Nizzypal** [comment]
@seiyria Hey dude.   If this is contract-related code and you don't want to give this to another person, and provided the  needed code is already in for this to be worked on, i'd like to try out what I learned in contracts here...

**Comment by seiyria** [comment]
it is contract related, but there's nothing started on it. it would have to be done entirely from scratch.

**Comment by Nizzypal** [comment]
oh maybe too big for  me then....

**Comment by brian-man** [comment]
I drafted a contract proposal a couple weeks ago:
https://cryptoblades.hellonext.co/b/Suggestions/p/add-nftmarket-support-for-auctions

Add NFTMarket support for auctions

Current implementation (as of 2021/06/23)

Read
- getFinalPrice(tokenAddress, id)
- geListingIDs(tokenAddress)
- getListingIDsBySeller(tokenAddress, seller)
- getNumberOfListingsBySeller(tokenAddress, seller)
- getNumberOfListingsForToken(tokenAddress)
- getSellerOfNftID(tokenAddress, tokenId)
- getSellerPrice(tokenAddress, id)
- getTaxOnListing(tokenAddress, id)
Write
- addListing(tokenAddress, id, price)
- cancelListing(tokenAddress, id)
- changeListingPrice(tokenAddress, id, newPrice)
- purchaseListing(tokenAddress, id, maxPrice)


Proposed changes

Read
- add: getHighBid(tokenAddress, id)
- add: getBidIncrement(tokenAddress, id)
- modify: adjust getTaxOnListing to reflect current high bid
- (optional) modify: rename getFinalPrice to getFinalBuyoutPrice
- (optional) modify: rename getSellerPrice to getSellerBuyoutPrice
Write
- add: addListing(tokenAddress, id, openingPrice, buyoutPrice)
- add: changeListingPrice(tokenAddress, id, openingPrice, buyoutPrice)
   - Must include logic to properly handle conflict between new pricing and current high bid.
- add: bidOnListing(tokenAddress, id, bidPrice)
  - Reject if bidPrice < getHighBid(...) + getBidIncrement(...).
  - Must gracefully handle the case where getHighBid(...) + getBidIncrement(...) > buyoutPrice.
- (optional) modify: rename purchaseListing to buyOutListing
- (optional) add: addListing(tokenAddress, id, openingPrice, buyoutPrice, bidIncrement)
- (optional) add: changeListingPrice(tokenAddress, id, openingPrice, buyoutPrice, bidIncrement)

**Comment by seiyria** [comment]
with this, we should also add the ability to auto expire market listings after a week or two, to prevent flooding it
