### ISSUE TITLE
Allow private trades on market

### ISSUE THREAD

**Issue by crypto-smoke** [CryptoBlades/cryptoblades#190]
Some users want to sell only to a specific other user. Allow listing of items to only be purchased by a specific address. This will keep users safe by still going through the marketplace but they wont have to risk listing an item and having a third party grab it before the desired recipient can.

**Comment by seiyria** [comment]
if we do this, it does have to do tax like the market does - probably the same tax value. I'm in favor of this.

**Comment by kcper** [comment]
Potential implementation:
- listing an item for some specific address is straight forward, just add another input below the price for the address (fill with "optional" and tooltip explaining what it does
- for buying we might let the buyer just search the ID which only they will be able to see or get another tab like "Offers" with listings just for the buyer (first one probably better for now right?)

**Comment by crypto-smoke** [comment]
Anyone could search for ID's for things that are up for private sale, so that wouldn't work out well. If it's locked so only a specific address can buy then there's no way anyone other than the intended recipient could purchase it. 

And yeah I failed to mention in the initial comment but the tax should absolutely remain in place for these transactions 👍

**Comment by kcper** [comment]
So basically add something like targetBuyer property to the listing and filter the listings with that property specified on the frontend (only issue with that is that someone could buy the listing by finding it on chain and writing to the contract from bscscan or whatever). Otherwise we'd need to add logic to the contract function which is getting quite complicated already after pagination gets merged. How does that sound @seiyria?

**Comment by seiyria** [comment]
I think that's reasonable - specifying who its for and blocking purchase if that field exists makes sense. On top of that, it's minimal frontend work (imo) comparatively. You'll need a new field when listing (target buyer), and maybe a new filter ("for me"). I am in favor.

**Comment by kcper** [comment]
Sounds good.

**Comment by crypto-smoke** [comment]
> 
> 
> So basically add something like targetBuyer property to the listing and filter the listings with that property specified on the frontend (only issue with that is that someone could buy the listing by finding it on chain and writing to the contract from bscscan or whatever). 

Nope, if the contract finds that targetBuyer is not 0x00, then the transaction fails if the buyer address is not the one specified. Yes, you could find every private sale by interacting with the contract (or reading contract state direct from memory) but it wont matter because they cant fake being the correct buyer.

**Comment by kcper** [comment]
Ok I'll implement the handling of that in the contract, too.

**Comment by brian-man** [comment]
@kcper 
Recommendations (in addition to the new optional param on addListing):
1. Add changeListingBuyer method (similar to changeListingPrice and allow 0)
2. (Consider) changeListingBuyer should emit ListingBuyerChange event (for consistency reasons)

**Comment by kcper** [comment]
> @kcper
> Recommendations (in addition to the new optional param on addListing):
> 
> 1. Add changeListingBuyer method (similar to changeListingPrice and allow 0)
> 2. (Consider) changeListingBuyer should emit ListingBuyerChange event (for consistency reasons with ListingPriceChange)
> 3. (Consider) add buyer to NewListing event (for consistency with ListingBuyerChange)

Wait, you've seen the PR right? These things are already done.

**Comment by brian-man** [comment]
> > @kcper
> > Recommendations (in addition to the new optional param on addListing):
> > 
> > 1. Add changeListingBuyer method (similar to changeListingPrice and allow 0)
> > 2. (Consider) changeListingBuyer should emit ListingBuyerChange event (for consistency reasons with ListingPriceChange)
> > 3. (Consider) add buyer to NewListing event (for consistency with ListingBuyerChange)
> 
> Wait, you've seen the PR right? These things are already done.

Nope.  I must have missed it. I didn't see the link and this said "Needs Review" so I wasn't sure what state it was in.
