### ISSUE TITLE
[Feature] - Update the list of Blockchains on the main RT website

### ISSUE THREAD

**Issue by MrBaptista69** [CryptoBlades/cryptoblades#1909]
### Prerequisites

- [ ] I checked to make sure that this feature has not already been filed
- [ ] I'm reporting this information to the correct repository
- [X] I understand enough about this issue to complete a comprehensive document

### Describe the feature and its requirements

-There is a list of blockchains on the main RT website, but it looks like it has not been updated in some time (https://rivetedtechnology.com/)
     +CoinEx and Meter both missing
     +The images for the chains can be found at 
https://www.cryptoblades.io/_next/static/media/chains.d37dede3.webp?imwidth=1080 
https://www.cryptoblades.io/_next/static/media/meter-chain.937371e1.svg?imwidth=128
from the CB website.  If something else is needed, please ping me about it and I will pull the individual ones. 

### Is your feature request related to an existing issue? Please describe.

N/A

### Is there anything stopping this feature being completed?

N/A

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by remocwenn** [comment]
![CSC logo 270x60](https://user-images.githubusercontent.com/90266559/232800207-033519c5-0de7-46e0-9004-c2184e4995a4.png)
![Meter logo 270x60](https://user-images.githubusercontent.com/90266559/232800210-579fb417-bf3c-4eb5-9155-c1e73df863b2.png)
I have resized and grayscaled the two logos.
*For future reference: They are within a 270x60 window, grayscalse, brightness was set to 100, and contrast was set to 85.
