### ISSUE TITLE
Market should be accessible if the wallet doesn't have skill or NFTs

### ISSUE THREAD

**Issue by poshdan** [CryptoBlades/cryptoblades#191]
At the moment the "get started" popup will block the tabs (and thus the market)
Maybe someone wants to get started by buying their NFTs instead of minting, they would want to know what the current prices are before swapping some starter skill.
Also, some users will want to quit the game by selling off their assets, and may swap their wallet skill before their NFTs are sold on the market, so they need the ability to check on their listings and update the price.

**Comment by crypto-smoke** [comment]
Not sure what it would take, but if the message was just the content of the main page, but everything else still worked, I think that would be a solid step in the right direction.

**Comment by seiyria** [comment]
should also be able to view stake, portal, leaderboard

**Comment by newb23** [comment]
Closed with #256
