### ISSUE TITLE
Create estimate of earnings page based on current SKILL and BNB price

### ISSUE THREAD

**Issue by devinep52** [CryptoBlades/cryptoblades#192]
Based on template done by @Groshmak @USRanger and @Razul bot guy

**Comment by seiyria** [comment]
if this is coming in to an official capacity, it should be done entirely client side, supporting query params for specific data. it would load images on a canvas and write text, then you can create a "save image" button from there.

**Comment by Nizzypal** [comment]
Hey @seiyria do you mean save the image in the local pc of  the  user?

**Comment by seiyria** [comment]
you aren't required to do high priority ones - there are plenty of other issues to do! with this, I mean you should collate images on a canvas and have an option to save the image as a png.

**Comment by Nizzypal** [comment]
Ok...  yeah tried to look for other ones but almost all seem to be assigned already.   Ones i found that are avail I tagged ya...

**Comment by newb23** [comment]
Closed with #288
