### ISSUE TITLE
remove stamina refill functionality

### ISSUE THREAD

**Issue by seiyria** [CryptoBlades/cryptoblades#193]

**Comment by Nizzypal** [comment]
Hey @seiyria Is this a contract code?  I'd like to try out what I  learned here if you're  cool with it.

**Comment by brian-man** [comment]
@seiyria
If this is urgent, I can take this on if @Steart is not ready to jump in yet

**Comment by Steart** [comment]
> @seiyria
> If this is urgent, I can take this on if @Steart is not ready to jump in yet

You can take it, I won't be able to work in it very soon :(
