### ISSUE TITLE
Allow access to some pages without having SKILL in wallet

### ISSUE THREAD

**Issue by crypto-smoke** [CryptoBlades/cryptoblades#196]
Users should be able to access Market, Leaderboard, Stake, and Portal pages without having skill in wallet. Some need to check status of their marketplace items or may just want to browse the marketplace or check out the leaderbaord.

**Comment by kcper** [comment]
Kind of overlaps with https://github.com/CryptoBlades/cryptoblades/issues/191 - maybe delete the pervious one as it is in the scope of this one.
