### ISSUE TITLE
leaderboards: show 25

### ISSUE THREAD

**Issue by seiyria** [CryptoBlades/cryptoblades#197]

**Comment by kcper** [comment]
Looks like a change in https://github.com/CryptoBlades/cryptoblades-api/ right?

**Comment by seiyria** [comment]
yeah, I'll get to it a bit later.

**Comment by kcper** [comment]
Oh sure, I tend to miss that you assigned yourself already!

**Comment by seiyria** [comment]
@kcper no worries! I tend to focus more on the api and other ancillary things
