### ISSUE TITLE
Show actual gas spent in fight results

### ISSUE THREAD

**Issue by crypto-smoke** [CryptoBlades/cryptoblades#208]

**Comment by cpp-vortx** [comment]
is this being worked on?

**Comment by seiyria** [comment]
nope! all yours.

**Comment by cpp-vortx** [comment]
Alright, later I'm gonna take it with my personal git account, this is actually my corporate account

**Comment by caiquejjx** [comment]
Gonna start looking into this, can u assing me into the issue?

**Comment by seiyria** [comment]
assignments can't be made until you're part of the github org

**Comment by caiquejjx** [comment]
the gas spent should be shown in BNB right?

**Comment by seiyria** [comment]
@caiquejjx yes
