### ISSUE TITLE
User paid a higher price than expected for item

### ISSUE THREAD

**Issue by crypto-smoke** [CryptoBlades/cryptoblades#209]
A user reported paying more for a sword than they should have. I looked into it, and two minutes before their purchase transaction went through, the price was increased on the market for the item. Maybe there is some delay or other issue in the displayed price vs what price is sent through the wallet? Does the app check for the listing price before sending the purchase transaction? If so that could be the discrepancy between the displayed price (using >2 min old data) and the price the user paid because it fetched it right before sending it. 

[Price increase transaction](0x556098ad38b5e445bbad6c935fc48f1e0769b62bfde51a5727a038cc13fe8169)
[Purchase transaction](https://bscscan.com/tx/0x67469ab496abf7ed127d4fd405a8fe8587d93fe8b983d3894ffb524dd48efe7c)

**Comment by bilbolPrime** [comment]
I believe there is protection inside the contract
` require(finalPrice <= _maxPrice, "Buying price too low");`

However the problem maybe in the UI itself, it seems it gets the price after the button is pressed

`async purchaseNft() {
      this.marketOutcome = null;
      if(this.selectedNftId === null) return;

      const price = await this.lookupNftPrice(this.selectedNftId);
      if(!price) return;

      this.waitingMarketOutcome = true;

      const results: any = await this.purchaseMarketListing({
        nftContractAddr: this.contractAddress,
        tokenId: this.selectedNftId,
        maxPrice: price
      });

      const results2: any  = await this.fetchAllMarketNftIds({
        nftContractAddr: this.contractAddress
      });

      this.allSearchResults = results2;

      this.allSearchResults = Array.from(this.allSearchResults).filter((x: any) => x.id !== this.selectedNftId);

      this.waitingMarketOutcome = false;
      this.marketOutcome = 'Successfully purchased '
        +this.activeType+' '+results.nftID+' for '+this.convertWeiToSkill(results.price)+' SKILL'
          +' from '+results.seller;
    }`

Doesn't this render any price the user sees obsolete? You can see 5 skill but when you hit the button the UI retrieves the newer price and sends that as the max price to the contract.

This seems to be a UI fix. Can I take a hit at it? (if my analysis is correct)
