### ISSUE TITLE
$dialog.alert not working

### ISSUE THREAD

**Issue by bilbolPrime** [CryptoBlades/cryptoblades#215]
There is an issue with dialog when used to alert.
It does not render properly.

![image](https://user-images.githubusercontent.com/25177987/125199248-f7b3cb00-e26d-11eb-9229-207deb137966.png)

**Comment by seiyria** [comment]
we're using it wrong. turns out all the things I did were mixing up the entire API: https://www.npmjs.com/package/bootstrap-vue-dialog
