### ISSUE TITLE
Wax portal improvements

### ISSUE THREAD

**Issue by seiyria** [CryptoBlades/cryptoblades#217]
Add estimated amount of BNB gotten based on the wax number input

Also show the amount of wax in the wax wallet

Also require 5 skill to use the portal

**Comment by newb23** [comment]
- [ ] Add estimated amount of BNB gotten based on the wax number input
- [ ] Also show the amount of wax in the wax wallet
- [ ] Input is converted to a big number and/or restricted to an 8 decimal number

**Comment by newb23** [comment]
Closing this and reopened for singular remaining issue as #245
