### ISSUE TITLE
optimize 3d models so they can be used

### ISSUE THREAD

**Issue by seiyria** [CryptoBlades/cryptoblades#23]

**Comment by seiyria** [comment]
hello yes this is dog

**Comment by seiyria** [comment]
hello yes this is dog

**Comment by blackstar1440** [comment]
Hi! I would love to help to optimized the 3D models and make one if needed :)
Is there a Unity/UE build? Or can I just send the .fbx files (I don't want to mess up the codes :D)? 

Btw, I'm a professional 3D Environment Artist. My expertise is creating environments and optimizing/fixing 3D assets. I'm not into characters but I can try if needed :)

**Comment by blackstar1440** [comment]
Alright! I'll play around with threejs and see what can I do to make it better. Thanks
