### ISSUE TITLE
navbar needs to be cleaned up significantly

### ISSUE THREAD

**Issue by seiyria** [CryptoBlades/cryptoblades#236]
ingame skill and normal skill take up too much space. in game skill should really get moved.

additionally, some routes can probably get moved out of the nav bar because they're a bit less important, such as leaderboards.

details TBD

**Comment by bilbolPrime** [comment]
For in game skill, I felt it's best to just merge them together and show the details in a tool tip. Saves the player some mind math in case they are using both in game and real skill to buy an item. I don't think there will be much rounding headaches.
![image](https://user-images.githubusercontent.com/25177987/126031267-78949d82-edaf-49d6-bea3-7ef684250559.png)

![image](https://user-images.githubusercontent.com/25177987/126030609-64292a96-c5dc-4338-b853-07d9928f01fc.png)
On Hover:
![image](https://user-images.githubusercontent.com/25177987/126030619-e10ce1ee-819c-4f11-898b-b2bb75c86578.png)
![image](https://user-images.githubusercontent.com/25177987/126031291-ea231037-23e5-419c-b536-d378760fb40e.png)

For the leaderboard, I just moved it to the options menu
![image](https://user-images.githubusercontent.com/25177987/126030941-4da4bfe5-0718-40b9-9ce9-4fade7e0ab64.png)
![image](https://user-images.githubusercontent.com/25177987/126031306-4a8b87bc-6664-45e8-acd8-527618fd0b61.png)

Code on branch: 236-navbar-clean-up
Let me know if you have any comments or need anything more before opening a PR
