### ISSUE TITLE
WAX bridge should consider game-only funds when checking if BSC wallet has minimum amount of SKILL

### ISSUE THREAD

**Issue by raymond-h** [CryptoBlades/cryptoblades#237]
The function `getTotalSkillOwnedBy` in the `CryptoBlades` contract (`cryptoblades.sol`) should include the user's game-only funds on top of unclaimed rewards and user's wallet.

**Comment by newb23** [comment]
Was the purpose for this frontend? As in, they need the 5 SKILL before they can use the Portal?

**Comment by raymond-h** [comment]
> 
> 
> Was the purpose for this frontend? As in, they need the 5 SKILL before they can use the Portal?

Both frontend and the bot, though ATM only the bot uses this function AFAIK.
