### ISSUE TITLE
Better mobile support # 2

### ISSUE THREAD

**Issue by Nizzypal** [CryptoBlades/cryptoblades#238]
Some irregularities on iOS (iphone)

1) Rewards drop  down makes it hard for user to see fight result.   It takes abit of  scrolling down
![image](https://user-images.githubusercontent.com/2307123/125327151-a6501e00-e2f7-11eb-90dd-ad3f24eaf09c.png)

2) Victory Results not centered
![image](https://user-images.githubusercontent.com/2307123/125327226-bbc54800-e2f7-11eb-83aa-c44982f30405.png)

3) Highlight in names gone difficult to know which one is active 
![image](https://user-images.githubusercontent.com/2307123/125327356-e0212480-e2f7-11eb-8c5f-2cb063a50480.png)

4) Maybe this supersedes #1 but  here the column contents are not aligned
![image](https://user-images.githubusercontent.com/2307123/125327442-f6c77b80-e2f7-11eb-8f07-963c47d91d7a.png)

**Comment by seiyria** [comment]
These should be posted in #26
