### ISSUE TITLE
Make pages match up with designs better

### ISSUE THREAD

**Issue by seiyria** [CryptoBlades/cryptoblades#24]
https://drive.google.com/drive/folders/1LA6XWGrza1avMks2x0h3gIUT5wkSUm5x

**Comment by wintersummermint** [comment]
<img width="1666" alt="Screen Shot 2021-07-10 at 9 03 25 PM" src="https://user-images.githubusercontent.com/9636557/125164019-9682ed80-e1c2-11eb-9930-75872576ee2d.png">

Just letting know, Started Progress for this one....
