### ISSUE TITLE
Better mobile support

### ISSUE THREAD

**Issue by seiyria** [CryptoBlades/cryptoblades#26]
Requires bootstrap

Will need good pwa support to start

**Comment by Nizzypal** [comment]
I have some optimizations that I can see but maybe you guys ahave specific things that you want addressed?  @seiyria

**Comment by seiyria** [comment]
we want every page to be responsive for starters. after that, we'll see where what we need.

**Comment by Nizzypal** [comment]
@seiyria 

You guys ok with this?
![image](https://user-images.githubusercontent.com/2307123/124644213-dbb3c200-de46-11eb-9882-5dd5d31b96b3.png)

**Comment by seiyria** [comment]
sure

**Comment by Nizzypal** [comment]
![image](https://user-images.githubusercontent.com/2307123/124674104-f4d06900-de6e-11eb-8b00-ba65bc00d241.png)

![image](https://user-images.githubusercontent.com/2307123/124674144-0b76c000-de6f-11eb-9ae6-00ca7d28b8f3.png)

**Comment by brian-man** [comment]
@YimitKEQ @Nyawmeowww Update (no changes since November)?

**Comment by Nyawmeowww** [comment]
Same case with the other issues. This is tagged unintentionally

**Comment by Sellie96** [comment]
Will be resolved with the new UI
