### ISSUE TITLE
Create API endpoint for circulating supply

### ISSUE THREAD

**Issue by crypto-smoke** [CryptoBlades/cryptoblades#267]
Endpoint should return a float value equal to the total supply of SKILL (1mil) minus the amount in the multisig wallet. This endpoint can then be submitted to coingecko and coin marketcap to update their stats for SKILL.

**Comment by seiyria** [comment]
this one is free game - I have no idea how it works.

**Comment by crypto-smoke** [comment]
Call function `balanceOf` for address `0x66BF6a6dC49939cbC356fF8e988ec4Da350ea414` on the contract located at `0x154a9f9cbd3449ad22fdae23044319d6ef2a1fab` and subtract that from 1 million SKILL tokens total. 

If you want to be fancy, also subtract by the balance of the burn address `0x000000000000000000000000000000000000dead` which is negligible but not zero :)

Also the contract address itself has been sent [88 skill](https://bscscan.com/token/0x154a9f9cbd3449ad22fdae23044319d6ef2a1fab?a=0x154A9F9cbd3449AD22FDaE23044319D6eF2a1Fab) as of now that should be considered removed from circulation...

**Comment by brian-man** [comment]
@crypto-smoke @seiyria @kcper It's not clear to me where this method belongs.  IIRC, there was some mention in Discord of Skill token/contract not being something that is likely to be modified.

**Comment by seiyria** [comment]
@brian-man I would put this in the API so it can be queried. Possibly some other stats like #holders and such.

**Comment by crypto-smoke** [comment]
This needs to be done as an HTTP API for Coingecko and CMC to utilize it

**Comment by seiyria** [comment]
this is done. it doesn't have real data, but it's done.
