### ISSUE TITLE
Multi-language support

### ISSUE THREAD

**Issue by crypto-smoke** [CryptoBlades/cryptoblades#271]
It would be great if all text/warnings/errors were translated into various language for the player base. A potential example implementation could be a JSON map for all website text which is in itself in a map with language as the key.

**Comment by seiyria** [comment]
the aforementioned json map is a good way to do i18n, and there's probably a vue i18n library. I can help someone implement this. I think this is a good idea.

**Comment by viruspowaa** [comment]
I think I can try to do this improvement ! I find this https://lokalise.com/blog/vue-i18n/#Performing_Simple_Translations, it using this vue library : https://kazupon.github.io/vue-i18n/started.html#html
It's ok for you ? I can try to do the same thing ! And I start with french traduction because I am (If you hadn't noticed because of my great English)

**Comment by seiyria** [comment]
@viruspowaa that looks fantastic - but we're not going to use their company product, we'll have the json files all in here ourselves. go for it!

**Comment by viruspowaa** [comment]
Yes of course ! We do it with our own json file with all language ! Ok I go for it !

**Comment by viruspowaa** [comment]
I can do the Spanish and Portuguese traduction by my own too. I will contact some people on the discord to have a traductor in each Country chanel

**Comment by seiyria** [comment]
That'd be great! I just want to make sure, first, that we ship something that works. :D

**Comment by DrGabo** [comment]
Dont worry guys i can do Spanish ;)

**Comment by viruspowaa** [comment]
https://user-images.githubusercontent.com/1824055/127493373-5fb2713e-d2b2-4193-aaa1-82f90860eb90.mp4

**Comment by viruspowaa** [comment]
Ok, dropdown is in option an translation work great ! I save language option in localstorage to save the user choice

**Comment by viruspowaa** [comment]
If someone want to participate in translation of cryptoblades App ! Plz follow the actual structure 
![image](https://user-images.githubusercontent.com/1824055/127535403-30679212-de63-4dd4-bd58-994dbee9afc8.png)

**Comment by viruspowaa** [comment]
I will be busy next few weeks so I can't advance on it. If someone want to continue after me

**Comment by kevinunger** [comment]
If nobody is currently working on that, I'll grab it. I just started adding more localization string and doing the [component interpolation](https://kazupon.github.io/vue-i18n/guide/interpolation.html#basic-usage). I'll add the german language file.

**Comment by kevinunger** [comment]
This is way more work than anticipated. Adding localization strings is tedious and takes time. 
This might take me 1-2 weeks to finish. My goal is to provide a good framework for us and translators to easily add new languages and new Strings.
 I'm not sure what the future workflow looks like when a dev adds new frontend code that contains translatable texts. Does the dev itself add the localization string to each individual file and a translator will translate that later or will there be a translating issue, where someone (or me) adds the localization strings while finding people to translate? I'll add English as the fallback language, in case some string is missing in one of the languages.

**Comment by seiyria** [comment]
@kevinunger the dev will have to add each string to the file. We'll have to be picky about PRs from now on but I think it'll be fine when everyone knows what's going on

**Comment by kevinunger** [comment]
@seiyria Got it. Is there a best-practice/workflow wiki somewhere for the devs? We probably need to add a localization how-to, because adding these strings is sometimes not straight-forward. E.g. When having something like this: 
```      
Earn <span class="bonus-text">{{getNextMilestoneBonus(currentCharacter.level)}}%</span> more per battle at<be>
```      
instead of doing it like this:
```
{{$t('EarningsCalculator.earn')}} 
<span class="bonus-text">{{getNextMilestoneBonus(currentCharacter.level)}}%</span> 
{{$t('EarningsCalculator.earnMoreText')}}
```      

IMO it's way better doing it like this:
```      
<i18n path="EarningsCalculator.milestoneBonus" tag="label">
          <span class="bonus-text">{{getNextMilestoneBonus(currentCharacter.level)}}%</span>
</i18n>
```
with:
```
"EarningsCalculator":{
	...
	"milestoneBonus":"Earn {0} more per battle at"
	...
}
```

**Comment by seiyria** [comment]
There is no wiki, so the best bet is for other people reading and reviewing the code.

**Comment by kevinunger** [comment]
Progress:

Setup i18n strings:

- [x ] App
- [x ] Options
- [x ] Plaza
- [x ] Blacksmith
- [ ] Combat
- [ ] Market
- [ ] Stake

Translate to:

- [ ] German
- [ ] French
- [ ] Spanish
- [ ] Portugese

- [ ] Tagalog / Filipino ?
- [ ] Russian
- [ ] Hindi
- [ ] Mandarin Chinese
- [ ] Arabic

**Comment by viruspowaa** [comment]
I'm back !! The current progress is up to date ? I can continue to dev ? @kevinunger do you push all your work ?

**Comment by brian-man** [comment]
@kevinunger Should this issue be considered "done" (completed)? Or do you want it open while there exists a language on Earth that we don't have a translation for yet? ;)

**Comment by seiyria** [comment]
it's done as the support is there
