### ISSUE TITLE
sell history interface

### ISSUE THREAD

**Issue by seiyria** [CryptoBlades/cryptoblades#293]
a button, when clicked, opens a modal with a log of all the weapons you sold, their id, name, and price sold for.

**Comment by seiyria** [comment]
API Call: `/static/market/transactions/:accountId`: https://github.com/CryptoBlades/cryptoblades-api

**Comment by Nyawmeowww** [comment]
I got the design going with Issue #293

![image](https://user-images.githubusercontent.com/31758395/126690798-f0c9a6c7-8685-42fd-9caf-a6a706e5dbb2.png)


![image](https://user-images.githubusercontent.com/31758395/126690691-ce2352d8-b806-47f8-97df-57cdbcd1f14b.png)

**Comment by Nyawmeowww** [comment]
Done with the initial mock-ups on Transaction History Interface. I'll update the code and design later.

Things done:
* Sell History Interface (Weapons and Characters)

Things to do:
* Adjust the UI to declog the screen of too many buttons (UX) re: Transaction History
* Responsive UI
* Design adjustments


![image](https://user-images.githubusercontent.com/31758395/126858062-c268e0bb-7118-4ab7-99b9-be410ef8369d.png)
![image](https://user-images.githubusercontent.com/31758395/126858033-64dd4af6-081b-452f-bd72-a592b658393f.png)
![image](https://user-images.githubusercontent.com/31758395/126858083-565247b9-db55-46e1-acba-f484eeb7417e.png)
![image](https://user-images.githubusercontent.com/31758395/126858101-c85e1410-a936-4178-9e38-aaa5a59ae2ed.png)

**Comment by Nyawmeowww** [comment]
**Things done:**
* Responsive UI
* Design adjustments

_Notes:_ 
_* The link on the No Sold Weapon/s or Character/s Modal is this: https://cryptoblades.gitbook.io/wiki/market/marketplace#list-nfts_
_* The modal supports sorting by clicking the headers of the column they want to sort. See Characters Sold Modal sorted by ID (Ascending)_


### MOBILE VIEW

**Buttons of "List NFTs" tab"**
![image](https://user-images.githubusercontent.com/31758395/126873292-ce7ccec6-ea95-4a56-93be-40826fad89eb.png)

**Tooltip for "Weapons Sold"**
![image](https://user-images.githubusercontent.com/31758395/126873418-a1e70ea1-e778-40cc-a272-539147266db7.png)

**Tooltip for "Characters Sold"**
![image](https://user-images.githubusercontent.com/31758395/126873428-1158ecbf-33dd-4719-923e-da97519fa5af.png)

**Weapons Sold Modal**
![image](https://user-images.githubusercontent.com/31758395/126873521-2ab88a03-5b22-4459-9b0c-ba431468b810.png)

**Characters Sold Modal**
![image](https://user-images.githubusercontent.com/31758395/126873618-8ed9eadc-a8cc-4fae-8a1c-4486a785e80e.png)

**Weapons Sold Modal - No Sold Weapons**
![image](https://user-images.githubusercontent.com/31758395/126873683-676ee495-a746-41ef-bdee-0501def776a5.png)

**Characters Sold Modal - No Sold Characters**
![image](https://user-images.githubusercontent.com/31758395/126873705-628ca60f-3487-4d72-91d0-282756052755.png)

**Weapons Sold Modal sorted by ID (Descending)**
![image](https://user-images.githubusercontent.com/31758395/126873977-7398dda7-9b88-47f9-b94f-ed166dbddb77.png)


**Characters Sold Modal sorted by ID (Ascending)**
![image](https://user-images.githubusercontent.com/31758395/126873826-232609d1-6c78-40a2-bd44-2a6d70e974cb.png)


### WEB VIEW

**Buttons of "List NFTs" tab"**
![image](https://user-images.githubusercontent.com/31758395/126873897-3f29fd17-8d59-4549-b5ea-927b715f195b.png)

**Tooltip for "Weapons Sold"**
![image](https://user-images.githubusercontent.com/31758395/126873905-6a837d79-dce5-4a01-983c-9ec247423708.png)

**Tooltip for "Characters Sold"**
![image](https://user-images.githubusercontent.com/31758395/126873987-6ac89e03-7d2c-4a69-b7e4-ba8d151a06e5.png)

**Weapons Sold Modal**
![image](https://user-images.githubusercontent.com/31758395/126873992-35113e30-91c3-4b57-b7aa-01d6443ccded.png)

**Characters Sold Modal**
![image](https://user-images.githubusercontent.com/31758395/126873998-2822c54e-fe6d-41c8-91db-90a7c926ac65.png)

**Weapons Sold Modal - No Sold Weapons**
![image](https://user-images.githubusercontent.com/31758395/126874013-70111315-da7f-4b27-b6c0-f3b8f374ca41.png)

**Characters Sold Modal - No Sold Characters**
![image](https://user-images.githubusercontent.com/31758395/126874019-949a40cd-06c7-468a-967d-7f500da35841.png)

**Weapons Sold Modal sorted by ID (Descending)**
![image](https://user-images.githubusercontent.com/31758395/126874070-e8b5477e-2a8f-405c-8d1a-2d840644b29e.png)

**Characters Sold Modal sorted by ID (Ascending)**
![image](https://user-images.githubusercontent.com/31758395/126874083-84741cd9-62b0-4b9a-a30e-200b57018073.png)
