### ISSUE TITLE
ingame skill should be usable on the market

### ISSUE THREAD

**Issue by seiyria** [CryptoBlades/cryptoblades#295]

**Comment by brian-man** [comment]
@seiyria 
Isn't this a duplicate of https://github.com/CryptoBlades/cryptoblades/issues/282?

**Comment by seiyria** [comment]
thanks, I'm an idiot

**Comment by newb23** [comment]
Sorry for necroing this issue, but #282 deals with unclaimed vs in-game. Are we wanting both types to be usable on the market?

**Comment by seiyria** [comment]
based on the last week I don't think so.
