### ISSUE TITLE
Patch notes in-frontend

### ISSUE THREAD

**Issue by poshdan** [CryptoBlades/cryptoblades#301]
Some users may not want to get their list of changes through social media.
We could add a view that hooks the medium posts in, or something like that. Perhaps a version string in frontend that we could use to show a little alert when an update arrives.

**Comment by seiyria** [comment]
We can do this fairly easily by parsing the xml that comes from the RSS feed. There's a good library for it: `rss-parser` with an example here in this repo https://github.com/LandOfTheRair/LandOfTheRair

**Comment by seiyria** [comment]
medium does not let us do so nicely, we'd either need to host a proxy or move somewhere that does and crosspost to medium: https://medium.com/coffee-driven-dev/adding-a-list-of-medium-posts-to-your-personal-website-b2988b63e60f
