### ISSUE TITLE
be able to mark stake options as deprecated so no one can stake on them, include a warning

### ISSUE THREAD

**Issue by seiyria** [CryptoBlades/cryptoblades#303]

**Comment by bilbolPrime** [comment]
Is this a pure UI change? some badge on the stake option and a warning prompt for confirmation or does it need contract changes.

**Comment by seiyria** [comment]
This will be ui only and hopefully not have to happen often. It should only apply to the current (old) contract

**Comment by bilbolPrime** [comment]
I can't work on this today and I only have the time during weekends. So if anyone wants a hit at this it's up for grabs.
If issue still free next week, will pick it up.
