### ISSUE TITLE
new option to nickname wallet

### ISSUE THREAD

**Issue by seiyria** [CryptoBlades/cryptoblades#320]
https://cryptoblades.hellonext.co/b/Suggestions/p/nickname-to-your-wallet-address-recognize-ppl-on-leaderboard

- [ ] Should be an option in the option dropdown
- [ ] Should allow for up to 15 characters
- [ ] Need to figure out a way to prevent people from being knobs ([this](https://github.com/seiyria/censor-sensor) _can_ help, but doesn't stop people from calling contracts directly) - alternatively, let them name whatever they want, but refuse to display it on the frontend using the same library.

**Comment by seiyria** [comment]
This could _also_ be done on the API level, thus it won't cost anything. Will want thoughts on this.

**Comment by Nyawmeowww** [comment]
It seems llike we don't have an API specifically for this one. However, based on the API documentation, I think we can pattern the process of getting the account address from `/leaderboard/fight/add` to create a new API that stores the account address and their corresponding "nickname" for their wallets.

### User Profile
- GET  `/static/user/:accountAddress` - get wallet nickname
- POST `/static/user` - pass `accountAddress`, `nickname` - insert wallet nickname
- PUT `/static/user` - pass `accountAddress`, `nickname` - update wallet nickname

**Comment by seiyria** [comment]
We absolutely could do this with the API, but the current question is if we should. People really like using the Blockchain so we may want to consider putting it on chain.

**Comment by Nyawmeowww** [comment]
Alright, perhaps I can do the initial Ui work. We can keep it open, so when the time comes that we decided whether to put it on API or onchain. There's minimal work. What do you think?

**Comment by seiyria** [comment]
I'm admittedly not a huge fan of starting work and leaving it open for long periods of time. It ends up with merge conflicts and other issues if left too long. Let's tackle this when we make a determination. I think we'll end up backing it with Blockchain.

**Comment by Nyawmeowww** [comment]
Aight
