### ISSUE TITLE
improve early withdrawal explanations/etc

### ISSUE THREAD

**Issue by seiyria** [CryptoBlades/cryptoblades#321]
https://cryptoblades.hellonext.co/b/Suggestions/p/beginner-friendly-more-explantions-about-early-withdrawal

**Comment by miles003** [comment]
![image](https://user-images.githubusercontent.com/51500655/126447897-4d97d676-81ae-446d-9a3a-4d576730af31.png)
is this acceptable?

**Comment by seiyria** [comment]
I think this looks great!

**Comment by miles003** [comment]
i did a little bit improvement, what do you think about this one? much cleaner isn't? 
![image](https://user-images.githubusercontent.com/51500655/126483862-bf264b08-fc39-4c31-9e3a-d9a4898fbb1d.png)

**Comment by seiyria** [comment]
I think the first one is a bit better - the second one would be fine if it were numbered, as if "these are the steps that happen"

**Comment by Nyawmeowww** [comment]
Also, i suggest editing the Title text to something else. "Withdraw" or anything that explain the context of the process.

**Comment by miles003** [comment]
here's the latest 
![image](https://user-images.githubusercontent.com/51500655/126484834-74497ecf-d829-42ab-a45a-54f3666283ee.png)

**Comment by seiyria** [comment]
lookin good!
