### ISSUE TITLE
Allow hyperlinking to a market page

### ISSUE THREAD

**Issue by crypto-smoke** [CryptoBlades/cryptoblades#329]
Allow hyperlinking to a specific sellers items, or a specific item. Users can post these links in chat 👍

**Comment by seiyria** [comment]
How this works:

store query params in the URL for sharing. if present, load to those specific presets. create a "share" button that copies the current url to clipboard using clipboard.js

**Comment by bilbolPrime** [comment]
I'll take a hit at this next weekend if it's still here but it seems to be very similar to #330 so maybe FilipBartos should take over if he has the time / interest as he got that one pretty much done.

**Comment by Sellie96** [comment]
NFT lookup same idea / Search by ID in bazaar. Closed
