### ISSUE TITLE
Allow hyperlinking to a specific weapon or character or (future nft)

### ISSUE THREAD

**Issue by crypto-smoke** [CryptoBlades/cryptoblades#330]
Have a page that displays a weapon or character card like it is in the game, that can be directly linked to. Users can brag and show off their NFTs.

**Comment by seiyria** [comment]
same implementation as #329

**Comment by brian-man** [comment]
@Sellie96 Is anybody active on this one?

**Comment by Sellie96** [comment]
@brian-man the functionality is still there it was missed off of the new nav ui. Chris has already done the work to add it back to the menu.
