### ISSUE TITLE
If item price is 0, remove or otherwise mark it as sold

### ISSUE THREAD

**Issue by crypto-smoke** [CryptoBlades/cryptoblades#332]
Due to the delay between the database being updated and getting to the user, you will see items on the market with a price of 0. This price is fetched from the contract, which means that item was sold or delisted. If an item price is 0 we should not display it or put an overlay on it marking it sold. Maybe a big red X with SOLD or something.

**Comment by viruspowaa** [comment]
I take it !! Let me do it 👍

**Comment by viruspowaa** [comment]
@seiyria if it's ok for you for Characters, I can do same for Weapon ?

**Comment by seiyria** [comment]
Yes @viruspowaa I'd want them both in the same pr!

**Comment by viruspowaa** [comment]
Ok ok, I do it now !!
