### ISSUE TITLE
Add item search by name to marketplace

### ISSUE THREAD

**Issue by crypto-smoke** [CryptoBlades/cryptoblades#339]
Need to add the data to the API/DB first of course

**Comment by seiyria** [comment]
We could do this, as they're generated client side... but what would searching by name do? The names have no correlation to anything.

**Comment by crypto-smoke** [comment]
Users could search for characters with special/unique names. Or refer to their items being sold by name instead of ID.

**Comment by crypto-smoke** [comment]
Moving to hellonext where I should have put it initially
