### ISSUE TITLE
remove advanced ui toggle option, make all advanced ui options visible normally

### ISSUE THREAD

**Issue by seiyria** [CryptoBlades/cryptoblades#342]

**Comment by alistairstpierre** [comment]
I'll give this one a go!

**Comment by seiyria** [comment]
I actually just merged a PR for this @alistairstpierre - sorry!

**Comment by vthomas13** [comment]
@crypto-smoke what is the timeframe on this?

**Comment by seiyria** [comment]
@vthomas13 this is already done.

**Comment by vthomas13** [comment]
@seiyria yeah, I just saw movement on the board to "payment in progress". Do I need to give an address or anything?
