### ISSUE TITLE
Update the "Welcome ..." pop-up modal

### ISSUE THREAD

**Issue by Nyawmeowww** [CryptoBlades/cryptoblades#348]
I think the pop-up modal should fetch the dynamic value (based on the most recent price)

![image](https://user-images.githubusercontent.com/31758395/126411426-61d0c4d2-830f-4121-a895-aa2ebe49f2c9.png)

**Comment by Nyawmeowww** [comment]
I have updated the dynamic value of the recruit cost. I'm still not sure on what value to put on the BNB for gas and BNB for the first few battles.
![image](https://user-images.githubusercontent.com/31758395/126546265-a48ea85b-17f6-49df-8968-418a8ce5a4a7.png)

**Comment by seiyria** [comment]
Having at least one of them be dynamic is a good start. We can worry about the BNB one later. That cost has been static IIRC for a long time, so it should be fine.
