### ISSUE TITLE
Pagination bug

### ISSUE THREAD

**Issue by Nyawmeowww** [CryptoBlades/cryptoblades#349]
Pagination visual and functional bug. In the first few seconds of the video , I switched to page 2 of "Earth" and then changed the filter of Element Type to "Fire". The page it fetched is prolly still 1 without resetting the page number (indicated in the video page number is 2) or page is 2 and it doesn't load the other pages.

--it stops working (or takes time to work) when you switch between different combination of filters--

https://user-images.githubusercontent.com/31758395/126416761-6ab070ad-ea39-4ca3-81ab-2ccb30e457a2.mp4

**Comment by brian-man** [comment]
Looks like @pohika did this change.
