### ISSUE TITLE
add holders, liquidity, active players in the stats for the page

### ISSUE THREAD

**Issue by seiyria** [CryptoBlades/cryptoblades#351]
this information needs to be captured by the API first

**Comment by kram111092** [comment]
when the api is available can i get this?

**Comment by seiyria** [comment]
api is available but this is for the landing page

**Comment by kram111092** [comment]
where I can find the landing page on frontend? and what is the api for this?

**Comment by seiyria** [comment]
this is in a bit of a holding pattern and we'll have more later, but I think this is supposed to be assigned to someone, sorry

**Comment by kram111092** [comment]
ok np :)

**Comment by hellojigoy** [comment]
This is noted .. just got back from vacation .. will work on the static design tomorrow ..

**Comment by newb23** [comment]
What is the current status on this issue?

**Comment by Sellie96** [comment]
Closing. Some of this information was added to the landing page
