### ISSUE TITLE
PVE004: improved loginc in removerewardweapon

### ISSUE THREAD

**Issue by seiyria** [CryptoBlades/cryptoblades#373]
![image](https://user-images.githubusercontent.com/763609/126534254-19dec50e-9d84-4ae8-9d81-1b60c50547c2.png)

**Comment by raymond-h** [comment]
I think the actually appropriate thing would've been to use `EnumerableSet.UintSet` from OpenZeppelin to store the weapon drops, but the suggested fix suffices for now.
