### ISSUE TITLE
PVE005: Unnecessary restriction in waxbridge::receive()

### ISSUE THREAD

**Issue by seiyria** [CryptoBlades/cryptoblades#374]
![image](https://user-images.githubusercontent.com/763609/126534317-88af9bde-8a4b-41ba-b56d-bedf62883d77.png)

**Comment by raymond-h** [comment]
The "unnecessary restriction" was actually deliberately done to prevent people from accidentally sending their BNB to the `WaxBridge` contract.

While it is sort of out-of-the-blue that the change was done to this contract and not others, the other contracts actually don't need it as contracts cannot receive BNB at all by default.
