### ISSUE TITLE
PVE006: Sanity checks for system/function parameters

### ISSUE THREAD

**Issue by seiyria** [CryptoBlades/cryptoblades#375]
![image](https://user-images.githubusercontent.com/763609/126534355-e523e81b-178e-4b73-9b7e-c1b84981532b.png)

**Comment by brian-man** [comment]
@kroge @seiyria 
Recommendation on upper/lower limits for these methods?

**Comment by seiyria** [comment]
burnPoint: min of 1, max of 5
lowStar: min of 1, max of 5
fourStar: min of 1, max of 2
fiveStar: min of 1, max of 2
reforgeFee: min of 100, max of 500
staminaCost: min of 20, max of 200
xpGain: min of 16, max of 48

**Comment by brian-man** [comment]
> burnPoint: min of 1, max of 5
> lowStar: min of 1, max of 5
> fourStar: min of 1, max of 2
> fiveStar: min of 1, max of 2
> reforgeFee: min of 100, max of 500
> staminaCost: min of 20, max of 200
> xpGain: min of 16, max of 48

Some of these ranges would reject the values specified in migrateTo_e55d8c5().

I'll adjust the ranges to be inclusive of the current values.
