### ISSUE TITLE
on small resolutions, combat page is a bit busted after choosing a weapon

### ISSUE THREAD

**Issue by seiyria** [CryptoBlades/cryptoblades#385]
![image](https://user-images.githubusercontent.com/763609/126552005-4d9ab658-78dc-4998-a4e5-d6748a441b29.png)

can't unselect, the filters are tiny

**Comment by kcper** [comment]
Note that you can't unselect, because you only have one weapon. And there's also this thing `<div v-if="selectedWeaponId" class="weapon-icon-wrapper">` which sucks for id 0

**Comment by seiyria** [comment]
ah yes, of course.

**Comment by miles003** [comment]
![image](https://user-images.githubusercontent.com/51500655/126583814-1d1457b8-5285-4d06-8cbe-36d6f2cdbc40.png)
Fix this how about this one

**Comment by thirte3n** [comment]
Is this the right issue or should I make another one for this?

![image](https://user-images.githubusercontent.com/46955326/126636223-ac97f9ea-4a9a-4fdb-83da-7cd0fe692f8c.png)

**Comment by seiyria** [comment]
For that one @ertsybot is working on that. This issue in particular pertains to the left side, probably due to me having an id 0 weapon, thus breaking it a bit. It's realistically not a big deal.

**Comment by seiyria** [comment]
Oh, unless you mean to make the issue to report the bug, in which case yeah. I'll do that.

**Comment by miles003** [comment]
ok so someone already working on this, i`m gonna find another issue

**Comment by seiyria** [comment]
@miles003 someone is not working on the id 0 left-side being broken, but it's low priority because it only affects id 0, which no players have
