### ISSUE TITLE
Overlapping text on mobile view when you run out of stamina on combat

### ISSUE THREAD

**Issue by kram111092** [CryptoBlades/cryptoblades#388]
![201225620_898112141060143_3554494060834633492_n](https://user-images.githubusercontent.com/38468134/126567506-4ee6a8e9-8a5f-4dfe-b774-40844aed4e05.jpg)

**Comment by alistairstpierre** [comment]
There's a lot of issues with sizing on mobile atm it seems. It's very messy! Looks like some CSS wizardry is needed. I'll fix this one.

**Comment by kram111092** [comment]
Thanks!
