### ISSUE TITLE
Separated combat and market filters

### ISSUE THREAD

**Issue by Giovanny-DS** [CryptoBlades/cryptoblades#394]
for better user experiencie, this filters should'nt go together. 

**Player should not:**
-have to clear filters in combat after exploring the market.
-have to re-fill the filters in market after a combat

**Comment by seiyria** [comment]
to solve this: pass in a variable to the grid that determines what the "type" of filters is, then prepend that key to localstorage

**Comment by Giovanny-DS** [comment]
i'll work on this
