### ISSUE TITLE
Stamina and Xp bar overflow in marketplace and plaza for characters

### ISSUE THREAD

**Issue by kamda-cyrial** [CryptoBlades/cryptoblades#397]
![image](https://user-images.githubusercontent.com/42605286/126583641-526c637e-e885-4fa4-9f7b-b8b994a6f281.png)

![image](https://user-images.githubusercontent.com/42605286/126583767-bfab1890-1fc8-4c14-9755-0fa4f18e484e.png)

**Comment by alistairstpierre** [comment]
Looks fine on mine, how do you recreate the issue?

**Comment by kamda-cyrial** [comment]
I was able to replicate the issue by reducing the default font-size on my other browser profiles, as by default, the issue is not present. I use the brave browser, and by changing my font-size to small, the problem appeared, and by changing the font-size to medium, the problem disappeared.

**Comment by seiyria** [comment]
This is due to browser settings so I'm not inclined to believe it's up to us to fix it.
