### ISSUE TITLE
Combat Screen - Responsive UI for desktop and mobile

### ISSUE THREAD

**Issue by Nyawmeowww** [CryptoBlades/cryptoblades#416]
Enemy Cards are now overflowing on a 1920x1080 Screen Resolution

![image](https://user-images.githubusercontent.com/31758395/126691457-ac727fb7-b8a7-4b08-8d75-f5700ddcf43b.png)

![image](https://user-images.githubusercontent.com/31758395/126691515-d4985b0f-9f58-4712-b1bf-5fbdd904c996.png)

**Comment by alistairstpierre** [comment]
Problem or just zoom out a little?

**Comment by seiyria** [comment]
this is a problem, it should be adjusted

**Comment by alistairstpierre** [comment]
I'll take a look!

**Comment by alistairstpierre** [comment]
Figured it out but after looking through all the UI I think I'll just redo the entire combat page, it's a bit messy atm.

**Comment by alistairstpierre** [comment]
Finishing up for the day but pretty close! Will finish it tomorrow.
