### ISSUE TITLE
Sold Card Revamp

### ISSUE THREAD

**Issue by Nyawmeowww** [CryptoBlades/cryptoblades#419]
Remove the sold button from the card, if the NFT is marked as sold.

![image](https://user-images.githubusercontent.com/31758395/126728548-cfcc3af2-10bc-4ced-adda-8ec5d17b009a.png)

**Comment by Nyawmeowww** [comment]
![image](https://user-images.githubusercontent.com/31758395/126729978-28551bbb-f70c-4812-a9c1-0e36c25ad101.png)

**Comment by viruspowaa** [comment]
Why don't say this when I fix #332 ? Somebody say to hide "price" and rename the "purchase" button on discord

**Comment by Nyawmeowww** [comment]
It was just raised earlier, to revise the button.
