### ISSUE TITLE
Add feature that allows users to input a number X day's worth of gas(BNB) to swap SKILL for

### ISSUE THREAD

**Issue by newb23** [CryptoBlades/cryptoblades#420]
Per Kroge: 
Hi priority ticket, requires solidity, partial claiming
Suggest how much to claim for gas or something

Even better, a slider , "how many days of gas should you like to claim" "Earn passive income from staking to maximize your rewards!"

**Comment by brian-man** [comment]
@newb23 Don't we need a skill/bnb exchange rate oracle?

**Comment by brian-man** [comment]
... or at least a "preferred" exchange/router to ask the question.

**Comment by brian-man** [comment]
@devinep52 Do you still consider this a "high priority ticket" (5 months have passed)?
