### ISSUE TITLE
store stats on characters

### ISSUE THREAD

**Issue by seiyria** [CryptoBlades/cryptoblades#423]
current stats:

- fights won
- fights lost

we _need_ to do this to unload hero score from the api

**Comment by denzanitized93** [comment]
![image](https://user-images.githubusercontent.com/63095831/127531664-4505838b-f308-4a15-838b-556c3c4a9cd6.png)
@seiyria 
how bout this?
changed char id display below the char ui. (centered or left aligned)

**Comment by seiyria** [comment]
@denzanitized93 there will be more stats than that, and there's a solidity component to this as well. the display needs to be somewhere else for them. someone suggested "flipping the card over" to see them.

**Comment by brian-man** [comment]
@seiyria How do you feel about starting statistics on some contract version and then only worrying about those values? (Ignoring older fights.)

@crypto-smoke Any thoughts on how hard it would be to pile up the data before block X for a onetime "addhistoricalfightdata(()" call to each character?

**Comment by seiyria** [comment]
@brian-man definitely the intention. We were planning on making a trinket that allows your stats to be tracked for combat (and maybe required for everything else)

It's not hard to get the historical data, but the problem is that it can be lied about.

**Comment by brian-man** [comment]
Update: We just had a discussion in the PVP sub-thread about PVP stats. Out of that discussion I think we want the following adjustments:

(1) move the PVE stats to a new stats.sol
(2) add mapping characterId -> bracket -> (wins, losses) for PVP

bracket is sort of like levelling tiers (1-10, 11-20, etc.)

I'll update this PR when I get a chance.
