### ISSUE TITLE
Issues with numbers after fights, showing rewards as zero

### ISSUE THREAD

**Issue by crypto-smoke** [CryptoBlades/cryptoblades#427]
![image](https://user-images.githubusercontent.com/86024507/126796073-e9623ab9-49d1-4b30-9083-53133a4c9084.png)

**Comment by kronos1014** [comment]
hi can help my earnings suddenly reset to zero. last activity done was battle 1 win 1 lose and forge weapon

**Comment by BBkez** [comment]
i have the exactly same problem. I achived 0.25 skill but suddenly they turn to 0.

**Comment by testingstuff1234** [comment]
I have had this issue repeatedly. I gain skill rewards but if I claim XP then my skill reward goes to zero as well as my XP. If I claim the skill reward it doesn't affect my XP. I have lost a fair amount of skill due to this as well.
Hoping the devs can fix this and refund us what we lost.

**Comment by seiyria** [comment]
I and others can't reproduce this and also I've been told it's fixed. Also, it looks like it's a display error, not that you actually lost the skill.

**Comment by Giovanny-DS** [comment]
> I and others can't reproduce this and also I've been told it's fixed. Also, it looks like it's a display error, not that you actually lost the skill.

what about making a round. to get rid of the decimals. before using ToBN

**Comment by seiyria** [comment]
@Giovanny-DS if you think it will work go for it.

**Comment by Giovanny-DS** [comment]
i'll grab this. them to start testing.

**Comment by newb23** [comment]
Issue was closed with #511.
