### ISSUE TITLE
pvp

### ISSUE THREAD

**Issue by seiyria** [CryptoBlades/cryptoblades#428]
get assigned random opponents like battling. You only know their trait, not their weapon, likely chances are accurate, but you actually put up the skill first into escrow, and as long as you have funds in escrow, you can keep receiving battles passively, and you can either remove yourself from the pvp pool manually, or you get kicked out when your SKILL is drained, so you are battling and being battled against. there is a percentage (10, configurable?) that goes to the game contract from the results of the fights. also the entry fee to pvp is directly correlated to your winnings in battle. so stronger chars put up more

**Comment by crypto-smoke** [comment]
ay skill to list character in the arena. players you are matched with will never change, unless they are removed from arena (deterministic based on your char + wpn).  This way if you dont have any good options, your only choice is to fight and lose or withdraw from the arena. The listing cost discourages back and forth listing to get new enemies

**Comment by crypto-smoke** [comment]
Log fight stats so we can rank players against eachother in PvP. Only count fights that the player initiated themselves.

**Comment by Nyawmeowww** [comment]
-initiate frontend progress at 0%-

**Comment by Nyawmeowww** [comment]
Attaching initial document reference for PvP mode

[PvP Mode - Version 1.0.docx](https://github.com/CryptoBlades/cryptoblades/files/6881515/PvP.Mode.-.Version.1.0.docx)

**Comment by viruspowaa** [comment]
@Nyawmeowww I create the branch on official github, you can work on it

**Comment by QSETT** [comment]
Hello, I am not a developer or anything - just CB player. I have read your PvP mode Version 1.0 document and I think see one big issue that can create a huge disadvantage for new players. I am talking about this : •	4 enemies will be matched based on your level

I think enemies should be matched not only based on LVL but also weapon that you staked into PvP
If enemies will be matched only based on LvL players that have already good weapons will forge low level characters, give them good weapon, and they will destroy PvP experience for new players.

This is just  a suggestion from a player.

Thanks

**Comment by QSETT** [comment]
Or maybe limit weapon * that you can stake with certain character levels? That will also create an extra use case for low * weapons other than reforging.

1-11 - max weapon staked in PvP 1*
11-21 - max weapon staked in PvP 2*
21-31 - max weapon staked in PvP 3*
31-41 - max weapon staked in PvP 4*
41+  - min  weapon staked in PvP 5*

??

**Comment by Nyawmeowww** [comment]
Hi @QSETT, this space is reserved for devs to track issues and new features. If you have suggestions post it on cryptoblades.hellonext.co. Also, that document is v1.0 😄

**Comment by Nyawmeowww** [comment]
removing viruspowaa. he's currently assigned to translations

**Comment by seiyria** [comment]
@Nyawmeowww more than one person can be assigned to an issue at a time

**Comment by seiyria** [comment]
@Nyawmeowww can you get a PR up for this so other folks can contribute more easily?

**Comment by Nyawmeowww** [comment]
Aight. Will do
