### ISSUE TITLE
Fight logs

### ISSUE THREAD

**Issue by ed3ath** [CryptoBlades/cryptoblades#439]
This displays the latest fight results. Character and id, weapon id (can also do displays weapon stats on hover), fight won, exp gained, skills gained, your roll vs enemy roll.

Just use the API to query the fight results

`https://api.cryptoblades.io/static/fights/:accountAddress`

**Comment by bilbolPrime** [comment]
I am not sure if I am going to do this one but does this API support paging?
I called my address and got 871 fights.
API should support paging or at least limited to last 50 fights or something

**Comment by Nyawmeowww** [comment]
I agree with bilbol, assuming we are going to acquire more players and pvp coming. The API pagination will improve API performance.

**Comment by seiyria** [comment]
@rhisis are you able to add paging? I have an example in the API. If not, I can do it.

**Comment by ed3ath** [comment]
pagination was added to fight logs endpoint

**Comment by seiyria** [comment]
@ed3ath I can't remember, did the frontend also consume that change?

**Comment by ed3ath** [comment]
no, i only did the api part. I'm not good in frontend

**Comment by jeffyzxc** [comment]
anyone working on this?

**Comment by seiyria** [comment]
No but we need to move some stuff into the scraper first.
