### ISSUE TITLE
Missing Character - Mobile View

### ISSUE THREAD

**Issue by Nyawmeowww** [CryptoBlades/cryptoblades#442]
A user reported that the character that he/she bought can't be seen in Plaza.

Number of characters expected: 2
Number of character seen: 1

![image](https://user-images.githubusercontent.com/31758395/126856442-b6003bc4-d593-4d7c-a8e4-b2852a87a558.png)

**Comment by seiyria** [comment]
According to this, they only have 1 character. Likely, the market transaction has yet to go through.

**Comment by Nyawmeowww** [comment]
Transaction Hash for reference: 0x810d0f6c4d9146c9951429fece8c1ebd2204d2a56c234260a2d5c803c1cf9e84

**Comment by Nyawmeowww** [comment]
Based on the user's verbatim, he/she have waited for an hour or so.

![image](https://user-images.githubusercontent.com/31758395/126856499-ab54e1aa-dfaf-44eb-9e98-c1dcf44f9011.png)

**Comment by vdaisson** [comment]
The hash is for SKILL spend approval, not the market transaction itself. There is no market txn after that.
Most likely the character was already sold at the time and they got the 0.2+ gas fee error message afterwards.

**Comment by seiyria** [comment]
Closing as this seems to be resolved.
