### ISSUE TITLE
"Fight" button in Combat screen requires more user input to be clicked when Fight result is up.

### ISSUE THREAD

**Issue by MrStaahp** [CryptoBlades/cryptoblades#443]
Quality of life suggestions for easier combat. Combat Result banner taking up a huge space when it's up forcing users to scroll down to access Fight button and see fight probabilities. Also occurs when character info is hidden.

This photo was taken using a 1920x1080 display.
![UIissue](https://user-images.githubusercontent.com/87888190/126857550-9ca6cbf6-0054-4e44-ab54-1d8742a77485.JPG)

Added a small mockup suggestion below:
![UISuggestion](https://user-images.githubusercontent.com/87888190/126857476-99a5edae-6ece-468a-9536-fb418c9ca3da.png)

Seiyra already suggested a modal Fight Result banner than the one seen on the picture above this to accomodate Mobile users.

**Comment by Giovanny-DS** [comment]
if we are going to make a separated modal for results I can work on this @seiyria

**Comment by seiyria** [comment]
@Giovanny-DS go for it!
