### ISSUE TITLE
Change Price Computation

### ISSUE THREAD

**Issue by Nyawmeowww** [CryptoBlades/cryptoblades#451]
Change price should also display the expected price to be paid by the buyer.

![image](https://user-images.githubusercontent.com/31758395/126887811-331cc504-3ce3-4478-9688-15c2cbdc5f0a.png)

**Comment by bilbolPrime** [comment]
Tried to reproduce on latest master and it shows the buyer price
![image](https://user-images.githubusercontent.com/25177987/126900706-95d2db69-3d6b-42fb-ad3a-e646f41a0e9a.png)

This was an issue but I believe someone had fixed it. Can you please confirm you're on the latest main branch or steps to reproduce.

**Comment by Nyawmeowww** [comment]
Ahhh that's on prod xD. Maybe someone fixed it

**Comment by Nyawmeowww** [comment]
After retrying and clearing cache issue still persists on prod.

![image](https://user-images.githubusercontent.com/31758395/126904178-67b09902-7d22-471c-a9a1-8f85b8053813.png)

**Comment by seiyria** [comment]
this is not pushed to prod. if it works in dev, it will be pushed to prod.
