### ISSUE TITLE
Fight buttons should be hidden after weapon runs out of durability

### ISSUE THREAD

**Issue by bilbolPrime** [CryptoBlades/cryptoblades#454]
You can still fight and if you do you get a nasty exception. Not sure if you pay gas though.
![image](https://user-images.githubusercontent.com/25177987/126893208-5e55ef20-a114-4a27-8d00-0425d89fba98.png)
![image](https://user-images.githubusercontent.com/25177987/126893215-7fe5a269-aaa0-41c9-a31f-8bb1e72bee07.png)

**Comment by denzanitized93** [comment]
Can I work with this issue? @seiyria

**Comment by seiyria** [comment]
@denzanitized93 all yours

**Comment by denzanitized93** [comment]
#502
