### ISSUE TITLE
Fight gas fee suggested is too high

### ISSUE THREAD

**Issue by poshdan** [CryptoBlades/cryptoblades#460]
A fight shows up as 0.0025 gas fee cost (due to our hardcoding), but in reality only consumes maybe 0.00072.
This causes some concern with users who don't realise that detail, and they might run into errors trying to change the numbers around, or if they are really low on funds.

It might be nice to lower that suggested value a bit to ~0.001, or a bit higher at 0.0015 to be super safe against future updates that dilute gas usage a fair bit.

EDIT: Actually the 0.00072 figure is from fights when the user already has a claimed value set, so the first cost after a claim will be somewhat higher than that. If someone could get me a figure on that, that'd be great and we can figure out what to set the suggested limit at

**Comment by poshdan** [comment]
update: in the latest deployment fight costs have increased by 15% from ~0.00072 to ~0.00082 BNB so I guess all bets are off on this issue.

**Comment by brian-man** [comment]
@poshdan How about 0.001 as a starting point?

**Comment by brian-man** [comment]
@poshdan Reminding as suggested.
