### ISSUE TITLE
improve victory results modal

### ISSUE THREAD

**Issue by seiyria** [CryptoBlades/cryptoblades#463]
https://cryptoblades.hellonext.co/b/Suggestions/p/overhauled-victory-section-focused-on-earnings

**Comment by jeffyzxc** [comment]
Where I can find this asset? 

![image](https://user-images.githubusercontent.com/25240940/129439542-00d526bd-e558-439d-b31f-439c0dbf3428.png)

**Comment by jeffyzxc** [comment]
Also, do we have endpoint for oracle skill price? or should i just use this https://api.coingecko.com/api/v3/simple/price?ids=cryptoblades,binancecoin&vs_currencies=usd?

**Comment by seiyria** [comment]
We have endpoints for a lot of this data but it is not currently live. You should use the live price from coingecko.

For the art asset, talk to Groshmak.
