### ISSUE TITLE
Marketplace is unusable because SOLD items

### ISSUE THREAD

**Issue by malvakian** [CryptoBlades/cryptoblades#464]
Please remove SOLD items in this list, see below image
![image](https://user-images.githubusercontent.com/307743/127015598-288721df-e872-4744-b81a-3bd381c08804.png)

**Comment by crypto-smoke** [comment]
This is not the place for bug reports.

IF YOU ARE A USER, DO NOT OPEN ISSUES AGAINST THIS REPOSITORY. OPEN THE ISSUE ON HELLONEXT INSTEAD: https://cryptoblades.hellonext.co/

**Comment by crypto-smoke** [comment]
Also, we are aware and are working on it.

**Comment by malvakian** [comment]
Thank you for your quick response and sorry about it.
