### ISSUE TITLE
Sort by Price is broken

### ISSUE THREAD

**Issue by testingstuff1234** [CryptoBlades/cryptoblades#475]
Sorting by price does not in fact sort by price. When selecting Low -> High, some mid-range prices are shown on page 1 before the price gets lower on the next few pages. Then it goes back up to the highest prices on the last page.

**Comment by seiyria** [comment]
if you're reporting something please add a picture so it can be verified. ideally an API call as well.

**Comment by bilbolPrime** [comment]
Sorting low to high price, 5 * swords , last page

https://api.cryptoblades.io/static/market/weapon?element=&minStars=5&maxStars=5&sortBy=price&sortDir=1&pageSize=60&pageNum=20

![image](https://user-images.githubusercontent.com/25177987/127177619-f74631e5-4cbf-41c8-b626-228df7b6dd58.png)

**Comment by seiyria** [comment]
API response is correct, we just don't have the data coming in from the scraper fast enough, so this can happen.
