### ISSUE TITLE
Restrict API calls only to cryptoblades.io

### ISSUE THREAD

**Issue by seiyria** [CryptoBlades/cryptoblades#478]
Needs to be some sort of auth that works only for requests from the app. Cors doesn't stop servers. 

Potential ideas: validate metamask tokens on the server (spoofable), require an API key (tedious, also spoofable), check user agent (spoofable)

**Comment by cpp-vortx** [comment]
isn't worth to use req.ip and check against cryptoblades.io IP?

**Comment by seiyria** [comment]
the ip refers likely to netlifys servers, of which there are many
