### ISSUE TITLE
Characters Lost

### ISSUE THREAD

**Issue by Fingerdedo** [CryptoBlades/cryptoblades#488]
Yesterday i put 5 characters on the market, 12 hour later that characters are not reflected in my list, i cant modify price becouse i cant see it and the SKILLS are not reflected as an sell.

**Comment by seiyria** [comment]
BSC is congested, we know about this. Do not open issues on github without prior approval. This is what that big, annoying text that you deleted said.

**Comment by Fingerdedo** [comment]
First, learn to treat people without that asshole behavior that you have as a collaborator.
And the second, if you do not know how to accept the critics and bugs of your game, learn to program better, do maintenance and hire better servers before launch nothing.
