### ISSUE TITLE
transak integration

### ISSUE THREAD

**Issue by seiyria** [CryptoBlades/cryptoblades#490]
https://www.notion.so/Integrate-Transak-f43cbb5dc7fa4d068a044ef9589879bf

will be used to buy bnb

**Comment by EduardoGomez951020** [comment]
Sharip I'll take it

**Comment by EduardoGomez951020** [comment]
Please add me to org.


![transak integration ](https://user-images.githubusercontent.com/28773860/130180505-7cd89ebd-5c9b-4cbf-a301-af88523b7257.jpeg)

**Comment by seiyria** [comment]
@EduardoGomez951020 I add people after their first contributionb is merged and I think this is your first still
