### ISSUE TITLE
50% increase in earned win funds if it all goes to IGO

### ISSUE THREAD

**Issue by seiyria** [CryptoBlades/cryptoblades#493]
there should be a modal before you fight that says "do you want to earn 50% more when you fight? if so, it will all go to your in game only wallet!" [yes] [no]

there also needs to be solidity work to make this work

the modal should have options for "dont ask me again" defaulting to the yes or no option chosen

the option should be stored on the options page with a 3 choice: ask, never, always (using bootstrap vue button groups as a radio)

**Comment by newb23** [comment]
This issue may also need to be closed with the phase out of IGO.

**Comment by brian-man** [comment]
> This issue may also need to be closed with the phase out of IGO.
Agreed.
@devinep52 @poshdan @seiyria Should we just abort this idea?

**Comment by seiyria** [comment]
Yeah
