### ISSUE TITLE
Character buy-back program

### ISSUE THREAD

**Issue by crypto-smoke** [CryptoBlades/cryptoblades#499]
character buy-back based on earnings formula. what we pay is based on earnings + premium (for us)

**Comment by brian-man** [comment]
I'd like some details on this because I think there's something compelling to do with the NFTMarket here.

**Comment by brian-man** [comment]
Follow-up to the above comment...

I think this could be implemented directly on the NFTMarket.  More specifically, if the seller lists the character below a certain price (adjusted for the character level and unclaimed xp), the market would just "burn" the character and put the seller directly from the game supply.

Much lower effort (I think) than doing it as a completely separate feature.

So this would mean:
1. update addListing to have some character-specific "pay immediately and burn" logic
2. update changeListingPrice to have similar new logic as well
3. find a mechanism (during queries?) to automatically resolve "old" listings and mark them as "Sold"

The third will nicely clear out old listings, lowering the "becoming ancient" load on the market.
