### ISSUE TITLE
Frontend support for weapon burn dust

### ISSUE THREAD

**Issue by brian-man** [CryptoBlades/cryptoblades#509]
The following frontend work is needed:

- [ ] Wallet UI for LB/4B/5B dust.
    - This uses getDustSupplies in Weapons contract.
    - Use "Lesser" (LB), "Greater" (4B), and "Powerful" (5B) as the initial names.
- [ ] UI to reforge a weapon using dust instead of a burn weapon.
    - This uses reforgeWeaponWithDust in CryptoBlades contract.
- [ ] UI to burn 1 weapon (accumulate dust).
    - This uses burnWeapon in CryptoBlades contract.
- [ ] UI to burn multiple weapons via multi-select.
    - This uses burnWeapons in CryptoBlades contract.

**Comment by brian-man** [comment]
@seiyria Item "A" needs guidance from CB devs on naming for the 3 dusts.

**Comment by seiyria** [comment]
lesser, greater, powerful

we can changes names in the ui later, it doesn't matter

**Comment by brian-man** [comment]
> lesser, greater, powerful
Thanks.  Updated the description.
