### ISSUE TITLE
"Invalid secret" error in /static/market

### ISSUE THREAD

**Issue by puleva4ever** [CryptoBlades/cryptoblades#516]
After some page changes in the market the following error is thrown.

URL
`https://api.cryptoblades.io/static/market/weapon?element=earth&minStars=2&maxStars=2&sortBy=price&sortDir=1&pageSize=60&pageNum=10`

Error
`{
    "error": "Invalid secret. See cryptoblades/cryptoblades-api documentation for how this works."
}`

Api readme reads the following, so I guess it shouldn't be happening.
`All routes that are not /static take secret as a header - Authorization: Bearer <secret>. This must match API_SECRET (if set) or the request will fail.`

My guess looking at the `server.js` is that the throttle error is being misshandled.

**Comment by seiyria** [comment]
The problem is that the rate limiter checks if you have a secret to bypass the rate limiter. Otherwise you're rate limited. This is intentional although the error could be more explanatory.

**Comment by seiyria** [comment]
behavior fixed.
