### ISSUE TITLE
Fail with error 'Ownable: caller is not the owner'

### ISSUE THREAD

**Issue by Daniil-9374** [CryptoBlades/cryptoblades#518]
I built it with Ganache on local computer successfully. When I am trying to deploy it on bsc test network. I've got this issue. 

  > confirmation number: 5 (block: 11017580)
   > confirmation number: 6 (block: 11017581)
   > confirmation number: 8 (block: 11017583)
   > confirmation number: 9 (block: 11017584)
   > confirmation number: 10 (block: 11017585)

   > Saving migration to chain.
   > Saving artifacts
   -------------------------------------
   > Total cost:          0.21331674 ETH

9_development+bsctestnet_after_game_setup.js
============================================

   > Saving migration to chain.
   -------------------------------------
   > Total cost:                   0 ETH

10_update_game.js
=================

StatusError: Transaction: 0x910dde9a0ff58211a1d3e36db3592730da3a02c4a32a3d88cf39646dc60fab84 exited with an error (status 0).
    at F:\Game\cryptoblades\node_modules\@openzeppelin\truffle-upgrades\src\upgrade-proxy.ts:64:30
    at upgradeProxy (F:\Game\cryptoblades\node_modules\@openzeppelin\truffle-upgrades\src\upgrade-proxy.ts:31:9)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at module.exports (F:\Game\cryptoblades\migrations\10_update_game.js:8:3)

![image](https://user-images.githubusercontent.com/73422442/127527624-4fadc2fd-1cc4-4db6-ad33-c1799da9fee3.png)

**Comment by hodlbe** [comment]
Is this when upgrading? Were you able to solve the problem?
