### ISSUE TITLE
desktop client

### ISSUE THREAD

**Issue by seiyria** [CryptoBlades/cryptoblades#521]
https://github.com/SwapyNetwork/electron-metamask-boilerplate

**Comment by jeffyzxc** [comment]
woah this is cool! Anyone working on this?

**Comment by seiyria** [comment]
No, if you think you can do it feel free, but I have high expectations for this.

**Comment by newb23** [comment]
@seiyria, the underlying project you referenced has been discontinued. I assume the desire for an app is still there, but, might need another solution.

**Comment by seiyria** [comment]
Excellent. It might still be a good basis to work with, assuming the maintainer just didn't want to look at it, rather than having a lot of outdated stuff.

The desire is there but it's extremely low and super unimportant.
