### ISSUE TITLE
Error with texts and new stamina system

### ISSUE THREAD

**Issue by Giovanny-DS** [CryptoBlades/cryptoblades#527]
Text in combat does not display well.

![image](https://user-images.githubusercontent.com/61195397/127586646-fbffa44b-2e61-4fe5-91a8-8c2d4accb2fd.png)
![image](https://user-images.githubusercontent.com/61195397/127586688-d4591509-1992-41a3-bd1c-a48d9439b8ee.png)
-----------------------------------------------------------------
i'm able to select 200 stamina and fight even when I don't have enough

![image](https://user-images.githubusercontent.com/61195397/127586711-ef4fab4c-4237-4fa3-b2b0-a8e63ad0735c.png)

the fight does charge the fee. and it ends on this error

![image](https://user-images.githubusercontent.com/61195397/127586607-07d04844-0b6d-449c-b292-f3f0dd4d0481.png)

**Comment by seiyria** [comment]
fixed by #536
