### ISSUE TITLE
Character Minting Bug

### ISSUE THREAD

**Issue by Nyawmeowww** [CryptoBlades/cryptoblades#532]
There's currently a bug during character minting that blocks players. The issue is assumed to be caused by insufficient gas. Please refer to the video attached.

https://user-images.githubusercontent.com/31758395/127629307-c75fbddb-f794-40e9-bf3a-14568c85d625.mp4

**Comment by brian-man** [comment]
The video appears to be from this account:
https://www.bscscan.com/address/0x0ca04998725dc43940ed233886734ada16b4e5e7

**Comment by brian-man** [comment]
@raymond-h @poshdan
Any idea why the `requestPayFromPlayer` modifier on `mintCharacter` was removed in the 523 PR?
https://github.com/CryptoBlades/cryptoblades/pull/523/files

**Comment by leovct** [comment]
I don't know if it is related but I experienced the same type of issue when trying to buy an item from the marketplace.
I had around 0.04 BNB and 1 SKILL in my wallet and the item was worth 0.4 SKILL (and it was not already sold) so it should have worked. Unfortunately, it did not so I had to transfer some BNB to my wallet in order to buy the item.

**Comment by Nyawmeowww** [comment]
Hi we know there are issues and we use this tracker to monitor them, so please refrain from commenting if your not a dev. Thanks!

**Comment by brian-man** [comment]
I think this requires a contract change because mintCharacter should use (and thus adjust approval) for tokenRewards but not inGameOnlyFunds whereas the function below includes both.

```
    function getSkillNeededFromUserWallet(address playerAddress, uint256 skillNeeded)
        public
        view
        returns (uint256 skillNeededFromUserWallet) {

        (,, skillNeededFromUserWallet) = getSkillToSubtract(
            inGameOnlyFunds[playerAddress],
            tokenRewards[playerAddress],
            skillNeeded
        );
    }
```
