### ISSUE TITLE
Prevent players from selecting a higher stamina cost for a fight than they have available

### ISSUE THREAD

**Issue by crypto-smoke** [CryptoBlades/cryptoblades#535]
Some players are selecting 200 stamina cost for a fight despite not having 200 stamina and are wasting gas with failed transactions.

**Comment by 0xroy** [comment]
How about this? I remove the available options depending on the Character Stamina
![Issue#535](https://user-images.githubusercontent.com/87876521/127660729-24264a59-264f-4e38-a84b-ef75d3df58e3.png)

**Comment by crypto-smoke** [comment]
that sounds good to me

**Comment by seiyria** [comment]
lgtm
