### ISSUE TITLE
Adjust gasOffset to be flexible and more accurate

### ISSUE THREAD

**Issue by crypto-smoke** [CryptoBlades/cryptoblades#537]
Currently gas offset is more or less fixed until updated, and it is tied to USD price of SKILL which doesnt make a lot of sense. I suggest using chainlinks BNB/USD oracle _ our SKILL/USD oracle to determine the correct gas offset to return to the player. The variable setting on the contract should be changed to current cost in bnb to do a fight transaction, and using the two oracles we can detrmine how much skill to return for that.

**Comment by brian-man** [comment]
@crypto-smoke Same as https://github.com/CryptoBlades/cryptoblades/issues/543?

**Comment by brian-man** [comment]
@seiyria @devinep52 @poshdan I'd like to convert this issue to just removing gasOffset references from frontend and deprecating in the contract ("unused" but kept in contract for proxy reasons, etc.).

Any objections/concerns with that direction?
