### ISSUE TITLE
Automatic payout adjustment

### ISSUE THREAD

**Issue by brian-man** [CryptoBlades/cryptoblades#543]
Proposal:
1. keep price oracle
2. introduce supply oracle
3. choose payout based on supply oracle, but limit it on the upside by price oracle

kroge comment from Discord:
Provide spreadsheets we can play with and simulations based on current user payouts so we can see how it compares, what it looks like at different supply, at different price, etc.

**Comment by brian-man** [comment]
Elevator pitch:

I made a suggestion (I forget where) that the payouts should be "connected automatically" (similar to oracle linkage the market price) to the reserve supply of Skill.  As skill gets thin in reserve, payouts shrink.  They get better when reserve grows.

This means that in some cases fights will not be profitable; but in exchange you ensure they never reach zero payout.

With this system in place, the "crisis" is "it's not profitable today" vs. "we're running out of supply".

Keeping "earning" active is easy.  Keeping it profitable (i.e. above cost) is hard.

But here's the thing.

If you have what I described, then when it's not profitable features and player decisions will change that or they won't.

If they don't then the result is some players will exit.  Very similar to crypto miners powering off when it's not profitable.

As more players exit, the remaining ones get more profit.  So you reach a steady state where the population aligns with the value provided.

As the game gets more enjoyable (separate from financial), players will arrive and stay even if it's breakeven or a slight loss.  Essentially it converts into a subscription model, just not explicitly.

The earners are paid by the enjoyers.

If you want to get a little meta, you can directly connect features for enjoyers to value provided by earners.

This is essentially what happens when forgers create weapons, apply burn points and then list on the market.  They're banking that someone will pay more than the crafting cost to get the result incl. the effort of reforging.

**Comment by brian-man** [comment]
Some thoughts from Groshmak in Discord:

Your thinking is correct imo. As the supply dwindles the payouts need to be reduced significantly.

We could distinguish the health of the contract in red, orange and green zones, which determine an incrasingly higher reduction in SKILL payouts.

Inflow and Outflow velocity needs to be considered as well and is more important than price.

If for whatever reason the speed of contract drain suddenly increases by an unhealthy amount, there should be some slight brake mechanisms in place  regardless of contract health.

The oracle payout increase should decrease as the contract enters certain zones.

The more difficult task, like you mentioned, is to determine at what point you can increase payouts again.  And that mostly depends on the  ratio in which the contract fills up.

Example: We had to cut the rewards in half of what the oracle would pay out normally. That means we would need at least a constant 50% higher skill inflow of what we have right now, to get earnings back to oracle lvl and to maintain the current contract supply. 

But that leaves a lot of room for errors. I think the inflow has to  be up to 50% higher than the outflow to establish a good reserve for the foreseeable future. 

A prolonged outflow that is higher than the inflow is signalising that something is going wrong. Even a 5% reduction in 1 day is deadly if the devs are unable to get players to invest more into the ecosystem.

So in essence: I think we need:

1. Supply Oracle with different zones that reduce/increase payouts based on price, supply and speed of drainage (brake/reduction zones)
2. Monitoring system that measures the "Health" of inflow & outflow
3. A commonly acknowledged range in which inflow percentage and outflow percentage ratio is considered healthy/unhealthy

**Comment by cavinpabua** [comment]
**The variables `fightBaseline` and `fightGasOffset`** 
the above variables especially `fightGasOffset` does not really offset the price of BNB really well. 2 weeks ago it was just 0.0007 BNB per fight which is directly connected to operations inside the `fight()` function, then a couple of days ago it became 0.0008 which only means that `fight()` function might have had some added operations making it cost more gas. But, I don't think the price of BNB was considered as it is rising and falling too. 

What I'm suggesting is to look again into the `fight()` function and check if we can do something about it. 
Also, `fightGasOffset` must be adjusted well to compensate the price of BNB by maybe +10-15% so players can be happy about having positive profits even on level 1

**Comment by brian-man** [comment]
@seiyria @devinep52 @poshdan 
Since the project went a different way, I guess just abandon this (close and archive)?

**Comment by seiyria** [comment]
Yeah that makes sense
