### ISSUE TITLE
Failed transaction shows the fight result modal again

### ISSUE THREAD

**Issue by bilbolPrime** [CryptoBlades/cryptoblades#549]
When a transaction fails, the last fight result shows probably leading to some "i didn't get my skill" complaints.

![image](https://user-images.githubusercontent.com/25177987/127763098-0b78f272-f766-4c73-a4a5-9337bf0715a4.png)

**Comment by denzanitized93** [comment]
@bilbolPrime is there a possibility that both fight result and error occur at the same time in response object?

**Comment by bilbolPrime** [comment]
> 
> 
> @bilbolPrime is there a possibility that both fight result and error occur at the same time in response object?

Unlikely as the failed transaction was after the first transaction by quite some time.

An easy way to reproduce this is to open the fight confirmation twice. Accept the first one. Wait for fight to be over, close the modal. Accept second transaction => it shows again.

You can use one of the methods described in #548 or #441 to get such a scenario.

**Comment by sinisbad123** [comment]
@denzanitized93 @bilbolPrime I actually made a fix for this.

We just need to check if there is an error being returned after the request, if there is, then we don't need to trigger the showing of the modal.

Not sure what to do in order to raise a PR against this repo though

**Comment by seiyria** [comment]
@sinisbad123 you need to fork, make a branch on your fork, push to the fork, then send us a PR

**Comment by sinisbad123** [comment]
@seiyria ayt, got it! I'll raise one in a bit!

**Comment by sinisbad123** [comment]
@seiyria raised a PR! Lemme know if there are any impact areas within the PR itself!
