### ISSUE TITLE
MarketPlace UI Revamp

### ISSUE THREAD

**Issue by wintersummermint** [CryptoBlades/cryptoblades#556]
![image](https://user-images.githubusercontent.com/9636557/127791388-3e47d6c2-3af0-4184-99cb-eed895202e25.png)

https://xd.adobe.com/view/76c59f47-4324-4c98-8c68-f492dace162c-2396/screen/c1852e5c-7792-46ed-87ae-9be0439bdc61/specs/

We can split up work by sections on this page 

- [x] - Navbar design top
- [x] - Market Filter left sidebar
- [x] - Banner and Sort section 
- [x] - Weapon Listings 

Not part of Mockup currently :
- [ ] - Sell Page 
- [ ] - My Listing 
- [ ] - Transaction History 

What's current in the codebase :

- [ ] - Scaffolding vuejs with routes for each page
- [ ] - Outline Divider for each sections 

Needs help with :

- [ ] wiring up Api calls to Frontend UI 
- [ ] wallet connection 
- [ ] rendering list items from API

**Comment by wintersummermint** [comment]
Hey @seiyria ertsy brought up a good question whether this is is external page or internal marketplace that i will just revamp the ui right now?

**Comment by seiyria** [comment]
@wintersummermint this is internal. We do not have all of the possible filters for weapons, but feel free to do what you can. The rest can be added later.

**Comment by mrlamzz** [comment]
**Design:** https://xd.adobe.com/view/2cf6edda-5a62-4bab-950a-2d9bfff2fefe-79a5/screen/c1852e5c-7792-46ed-87ae-9be0439bdc61/

Hi @wintersummermint, if you are asking if this needs to be developed on a separate subdomain, as per my discussion with Kroge, I recommended that it needs to be a separate installation like it's gonna reside to marketplace.cryptoblades.io, and he agreed and approved.

**Reasons why it needs to be on a separate installation:**
- Performance
- Security
- Can launch when it is done and no need to wait for the game's updated UI.
- Versatility
- SEO Purposes

...however @seiyria has the last say for this.

**Note:**
- This marketplace will be a combination of CryptoBlades marketplace and Open Marketplace (meaning to say, other NFTs can also be sold here with BNB with the option to pay with SKILLs as well)
- I still have to design how the Open Market will look. I also have to design how the list view will look.
- Mobile is on To-Do on my list as well after I finalize the desktop with the Open Market.

**Comment by seiyria** [comment]
I will confirm. If it is to be a separate project, I will start a new repository for it.

**Comment by seiyria** [comment]
https://github.com/CryptoBlades/marketplace over here is where the project will live. when there is a deployable version, we will get it on netlify. @wintersummermint are you comfortable scaffolding a vue typescript project using vue cli?

**Comment by wintersummermint** [comment]
Yes , will run new vue cli project on it

**Comment by seiyria** [comment]
@wintersummermint in that case it's all yours. I'll check in to see that it's generated with our projects preferred settings so it's easier for others to work on the project, but other than that have at it.

**Comment by wintersummermint** [comment]
![cnI4DarFFG](https://user-images.githubusercontent.com/9636557/128663725-e8a55103-9ea9-462a-b346-3a3d6bbd4950.gif)

Resuming more items today, banner and weapon items list

**Comment by jeffyzxc** [comment]
Happy to help on Weapon Listings

**Comment by keepwell-ivan** [comment]
I would gladly help on the revamp. let me know how thanks :)

**Comment by jnebab** [comment]
I would gladly want to volunteer on the listings too.

**Comment by wintersummermint** [comment]
Hey Everyone, if you want to contribute please check for progress and cards can be worked on : https://github.com/CryptoBlades/marketplace/projects/1

**Comment by Sellie96** [comment]
Bazaar has been completed
