### ISSUE TITLE
Staking problem

### ISSUE THREAD

**Issue by bubbles2328** [CryptoBlades/cryptoblades#558]
Hi please i need help on claiming my stake skill. My skill is gone after i claim the rewards. What to do.

**Comment by thepauldv** [comment]
Have you tried the unstaking? In the unstake tab, you have to click the wallet on how much you staked. And then below there will be an unstake button after the 7 days lock is done. Hope this helps.

<img width="399" alt="Screen Shot 2021-08-02 at 8 15 28 PM" src="https://user-images.githubusercontent.com/65590310/127860832-d233966a-a616-4b2d-837c-125bc2b6c6eb.png">

**Comment by seiyria** [comment]
tech support does not go on github. this is your only warning.
