### ISSUE TITLE
min/max price filter for market

### ISSUE THREAD

**Issue by seiyria** [CryptoBlades/cryptoblades#560]
update: this seems to need to factor in the tax, and it currently doesn't.

**Comment by KevinAlbrecht** [comment]
Hi, if no one if working on it I would like to take it

**Comment by seiyria** [comment]
you're welcome to take it, but please keep in mind - one thing at a time. also, there isn't API for this. I will start that next.

**Comment by KevinAlbrecht** [comment]
You are right, I identified 3 tasks :
 - [front]I think it's clear, updating the weaponGrid.vue for the new filters, pass data until the httpGet (pointing to the `app.get('/static/market/weapon',` route.
- [Api], I thought adding a "price" property to the redis query was sufficient (the same as the min/max stars, so only {$gte $lte})
- [Abi], update the `getNumberOfWeaponListings` function to accept the price filter. I dunno much about solidity but I can learn.

Tell me if it is ok for you and if I can try the Api and/or the Abi tasks too ( I'm finishing the front right now )

**Comment by seiyria** [comment]
API is done. there needs to be no solidity work at this time as everything hits the API, except look up by id. There is now a price filter, you can see the docs for it over on the api repo

**Comment by KevinAlbrecht** [comment]
I think this feature need another task to be fully operational, it seems the price filters doesn't consider the current market fees.
I initially created an issue about it, It may not be the right process so please find the hellonext ticket below

[Hellonext ticket](https://cryptoblades.hellonext.co/b/feedback/p/bug-market-min-max-price-filters-doesn-t-seems-to-consider-the-market-fees)

[The too_quickly_created issue](https://github.com/CryptoBlades/cryptoblades/issues/639)

**Comment by seiyria** [comment]
It might. The API probably needs to consider the price + 10%. I'm not sure where the problem is there, though, if it's in the scraper or what.

**Comment by jeffyzxc** [comment]
Could we also add filter by power, int and etcetera.

**Comment by seiyria** [comment]
@jeffyzxc that is off topic for this issue and also unlikely to come any time soon.

**Comment by brian-man** [comment]
@seiyria Who should be assigned as owner? Last update on this was in September.

**Comment by Sellie96** [comment]
Bazaar already has this implemented. Closing
