### ISSUE TITLE
choose weapon element on forge

### ISSUE THREAD

**Issue by seiyria** [CryptoBlades/cryptoblades#562]
blocked by #538 and #529

this should allow you to, for a markup of 100% (total of 2x), choose the element you mint with. the new flow is:

1. hit forge button
2. see popup of "random" (with the cost below it, current price), then each of the elements (with the cost below them, 2x current price)
3. choose forge element or random, then hit a button to confirm

this will need to wait for the 10x forge to be merged because it will need to be factored in there as well.

**Comment by 0xroy** [comment]
Maybe something like this with a hover over the lements at the beginning and after selecting one it stays trandformed? 
Also I was thinking maybe have a questionmark png for the random or some more fancy font.
![image](https://user-images.githubusercontent.com/87876521/127998507-48f03d2c-b2b3-454c-92c2-353a81edad5b.png)

**Comment by seiyria** [comment]
I would use the question mark icon.

However if you were to do this, the choices should be one row, not two. Something like

Random fire water thunder earth
X skill | y skill

Forge
