### ISSUE TITLE
Blacksmith/Reforge UI Revamp

### ISSUE THREAD

**Issue by Sellie96** [CryptoBlades/cryptoblades#567]
The current Reforge menu is cluttered and unintuitive. This is to resolve the UI making the process much more simple for a user.
• No longer two duplicated lists.
• Make much more clear which weapon will be the one being buffed and which weapon will be burnt.
• Show the bonus the weapon will give when burnt.
• Unhide the Reforge button. Add a tooltip to explain the process.

**Comment by seiyria** [comment]
Uhhh?

**Comment by NFarnell** [comment]
Just adding for what Tourist said needed working on. Is this not the correct process? @seiyria

**Comment by seiyria** [comment]
The process is fine, but there needs to be more in the issue, specifically what the goal is, especially for a nebulous title like this. A mockup, a list, or anything would help so when we go to look at the inevitable PR we can see what the actual goal is.

**Comment by NFarnell** [comment]
Apologies. I'll make sure to include more detail now and in the future.

**Comment by seiyria** [comment]
Thanks! That helps a ton.

**Comment by NFarnell** [comment]
Attached Proposals
![Proposal2](https://user-images.githubusercontent.com/60218956/128018303-c3dbe40a-3937-4f1c-af33-68ff7e9a7b1e.png)
![Proposal1](https://user-images.githubusercontent.com/60218956/128018310-dce4ad6e-5f6f-4ff5-8a8e-dca32d6a8d43.png)
