### ISSUE TITLE
Claiming Skills reward problem

### ISSUE THREAD

**Issue by kyleichijo15** [CryptoBlades/cryptoblades#568]
after I early claimed the skills with 14% tax and it was confirmed in bscscan it did not registered as skills in my assets metamask wallet.
Metamask Address as proof: 0x75fd980B8e9aE4fAFB644FEA0C5Da82D95Fa743B

**Comment by Nyawmeowww** [comment]
I'm pretty sure you read the Issue Template

IF YOU ARE A USER, DO NOT OPEN ISSUES AGAINST THIS REPOSITORY. OPEN THE ISSUE ON HELLONEXT INSTEAD: https://cryptoblades.hellonext.co/

PLEASE DELETE THIS AND THE ABOVE TEXT BEFORE OPENING AN ISSUE
