### ISSUE TITLE
Earning Calculator Fix

### ISSUE THREAD

**Issue by blacklss** [CryptoBlades/cryptoblades#569]
Fix the earning calculator, at the moment it calculates and discounts the gas fee rate of all battles. Make a method that you might choose to battle 40x 80x 120x 160x 200x, this would avoid community FUD and prints as negative marketing.

Should also consider showing the gains in $ after each battles

**Comment by jeffyzxc** [comment]
Do we have UI for this?

**Comment by KennyUTN** [comment]
Yes, coming up today probably

**Comment by jeffyzxc** [comment]
Oh aight!
