### ISSUE TITLE
Weapons Enchantment

### ISSUE THREAD

**Issue by blacklss** [CryptoBlades/cryptoblades#570]
Enchantment weapons | armors would solve some Skill Sinks 

Make a Enchantment item to buy and do some math to improve the battle rewards with the risc of loosing/breaking the weapon.

+1-3 = 100% 
+4 = 66.67%
+5 = 33.34% 
+6 = 25.0% 
+7 = 20% 
+8 = 16.67 % 
+9 = 14.29% 
+10 = 12.5% 
+11 = 11.12% 
+12 = 10% 
+13 = 9.10% 
+14 = 8.34% 
+15 = 7.7% 
+16 = 7.15% 
+17 = 6.67% 
+18= 6.25%
+19 = 5.89% 
20 = 5.56% 

The game needs some extra gaming experience to survive.

**Comment by seiyria** [comment]
this belongs in hellonext
