### ISSUE TITLE
Cross domain exists

### ISSUE THREAD

**Issue by 2457123264** [CryptoBlades/cryptoblades#572]
https://api.cryptoblades.io/static/notifications
![image](https://user-images.githubusercontent.com/29721235/127982347-7a74a43f-6b49-4c20-b9b7-43262d1b519e.png)

**Comment by Nyawmeowww** [comment]
Im pretty sure you've read the template you just deleted.

IF YOU ARE A USER, DO NOT OPEN ISSUES AGAINST THIS REPOSITORY. OPEN THE ISSUE ON HELLONEXT INSTEAD: https://cryptoblades.hellonext.co/

PLEASE DELETE THIS AND THE ABOVE TEXT BEFORE OPENING AN ISSUE
