### ISSUE TITLE
Cross domain exists

### ISSUE THREAD

**Issue by 2457123264** [CryptoBlades/cryptoblades#573]
The interface is cross domain and cannot be called locally
Like static/market/character
![image](https://user-images.githubusercontent.com/29721235/127989129-6d378ff7-e95f-4c08-a44d-2b79ff105d8f.png)

**Comment by Nyawmeowww** [comment]
Hi! For the second time around, read the template carefully. It's on all caps already.

IF YOU ARE A USER, DO NOT OPEN ISSUES AGAINST THIS REPOSITORY. OPEN THE ISSUE ON HELLONEXT INSTEAD: https://cryptoblades.hellonext.co/

PLEASE DELETE THIS AND THE ABOVE TEXT BEFORE OPENING AN ISSUE

**Comment by seiyria** [comment]
This is intentional. If you want to test locally, the API might need to be put in an environment variable so it can be customized. I'll look into this.

**Comment by 2457123264** [comment]
Where the API?

**Comment by 2457123264** [comment]
> This is intentional. If you want to test locally, the API might need to be put in an environment variable so it can be customized. I'll look into this.

And how about this?
![image](https://user-images.githubusercontent.com/29721235/128008004-af150fe5-8df3-43c4-ad2d-42e911d587eb.png)

**Comment by seiyria** [comment]
That isn't intentional, but this issue is for the API. I'm not sure what you're doing or running into, but keep it on topic.

**Comment by 2457123264** [comment]
> This is intentional. If you want to test locally, the API might need to be put in an environment variable so it can be customized. I'll look into this.

Where the API?

**Comment by 2457123264** [comment]
> > This is intentional. If you want to test locally, the API might need to be put in an environment variable so it can be customized. I'll look into this.
> 
> Where the API?
back-end and the Access-Control-Allow-Origin
![image](https://user-images.githubusercontent.com/29721235/128018447-58b2a742-1434-4882-85fe-cbb4ca5cee54.png)

**Comment by seiyria** [comment]
What, specifically, are you asking for?

**Comment by 2457123264** [comment]
> What, specifically, are you asking for?

Cannot request interface for locally open project
The interface may be subject to cross domain restrictions

**Comment by seiyria** [comment]
Okay, I have just pushed a patch that lets you specify a local API URL in the `.env` file. _However_, for local development, you _probably_ do not need this.

**Comment by 2457123264** [comment]
> Okay, I have just pushed a patch that lets you specify a local API URL in the `.env` file. _However_, for local development, you _probably_ do not need this.

Right，Same result
Maybe I need our back-end request interface and return it to the front-end

**Comment by seiyria** [comment]
First off, what exactly are you trying to do that requires the backend? Most issues here do not require it. The CORS error is unimportant in these cases. Secondly, if you do need the backend, you will need to run a local copy of it, and change the URL in the .env file to match your local API URL.

**Comment by 2457123264** [comment]
> First off, what exactly are you trying to do that requires the backend? Most issues here do not require it. The CORS error is unimportant in these cases. Secondly, if you do need the backend, you will need to run a local copy of it, and change the URL in the .env file to match your local API URL.

Local operation interface error
I'm going to put the project under my own server
However, errors are reported where the interface is involved
Such as
![image](https://user-images.githubusercontent.com/29721235/128022515-4903b19c-4f9c-4f8c-a087-92440a29d882.png)

**Comment by 2457123264** [comment]
> First off, what exactly are you trying to do that requires the backend? Most issues here do not require it. The CORS error is unimportant in these cases. Secondly, if you do need the backend, you will need to run a local copy of it, and change the URL in the .env file to match your local API URL.

Local operation
Click 'Browse Characters'
An error occurred ‘inpage.js:1 MetaMask - RPC Error: Internal JSON-RPC error’

**Comment by 2457123264** [comment]
> > First off, what exactly are you trying to do that requires the backend? Most issues here do not require it. The CORS error is unimportant in these cases. Secondly, if you do need the backend, you will need to run a local copy of it, and change the URL in the .env file to match your local API URL.
> 
> Local operation
> Click 'Browse Characters'
> An error occurred ‘inpage.js:1 MetaMask - RPC Error: Internal JSON-RPC error’
![image](https://user-images.githubusercontent.com/29721235/128119371-2844e286-ca31-479d-a0d4-ce6a8f7b4a27.png)
