### ISSUE TITLE
timer on withdraw to show when it will lower to the next %

### ISSUE THREAD

**Issue by seiyria** [CryptoBlades/cryptoblades#579]

**Comment by sahilgaba97** [comment]
can i have a pull-request for this or anyone already looking into this already?

**Comment by seiyria** [comment]
@sahilgaba97 no one has claimed it, go for it!

**Comment by denzanitized93** [comment]
@seiyria you mean by this ticket is to add timer on tax % to show the next tick. and where do you want it to be displayed?

**Comment by seiyria** [comment]
@denzanitized93 probably a tooltip on it, with some dashed underline indicating that there's info there

**Comment by denzanitized93** [comment]
@seiyria ok noted.

**Comment by denzanitized93** [comment]
@seiyria i think this includes sol api to get tax timer. im assuming to return this on function _rewardsClaimTaxTimerStart[playerAddress].
but idk about sol :(

**Comment by seiyria** [comment]
@denzanitized93 I have no idea what this all entails. I had figured it was all available on the frontend, but if not, you'll want to ask around in #solidity to see if anyone can help figure it out.

**Comment by denzanitized93** [comment]
ok2 i will try to ask

**Comment by byyyyyyyyy** [comment]
anyone working in on this?

my suggestion on where to put the timer
![image](https://user-images.githubusercontent.com/88365848/128475379-45d22d32-b4a8-440e-b8c4-ee59f67fe0f2.png)

**Comment by Nyawmeowww** [comment]
> anyone working in on this?
> 
> my suggestion on where to put the timer
> 
> ![image](https://user-images.githubusercontent.com/88365848/128476021-c16333d9-c98f-4370-a33d-0f53298059de.png)

It's free if there's no assignees, so fire away

**Comment by denzanitized93** [comment]
![image](https://user-images.githubusercontent.com/63095831/128595912-6a34d303-2a39-4ee9-91c7-69f461d132ac.png)

Should I remove second? and just display h:m.
Currently I am using the secondsToDDHHMMSS util

**Comment by denzanitized93** [comment]
![image](https://user-images.githubusercontent.com/63095831/128595952-0b333b2a-0091-4093-96d9-00a871a43806.png)

@seiyria 
Should I remove the seconds or just display as it is.
Currently using the secondsToDDHHMMSS utility.
And I changed the tooltip to the whole span instead of the ? icon

**Comment by seiyria** [comment]
Seconds is fine! Looks good to me
