### ISSUE TITLE
text orientation on "you do not have stamina to do battle"

### ISSUE THREAD

**Issue by jeffyzxc** [CryptoBlades/cryptoblades#592]
![image](https://user-images.githubusercontent.com/25240940/128193545-0eef5a51-bceb-4b9a-8e01-7f7f158f7793.png)

**Comment by seiyria** [comment]
This should be a different flex direction.

**Comment by jeffyzxc** [comment]
can i work on it?

**Comment by seiyria** [comment]
sure

**Comment by jeffyzxc** [comment]
aight!!

**Comment by jeffyzxc** [comment]
Let me know if this okay. I will submit a PR. Thanks! :)

![image](https://user-images.githubusercontent.com/25240940/128200572-879320b9-7a04-4d0e-b722-a6acee5aa5c2.png)

**Comment by seiyria** [comment]
That looks fine to me!

**Comment by jeffyzxc** [comment]
great!
