### ISSUE TITLE
Weapon Grid Filter - x10 Forge

### ISSUE THREAD

**Issue by Nyawmeowww** [CryptoBlades/cryptoblades#595]
Remove the filter from the pop-up modal of x10 Forge (show forged weapons) when the player selects filter from the weapon-grid in Blacksmith.

Steps to replicate:
1. Select 5 ⭐ in `Stars` dropdown
2. Select Earth in `Element` dropdown
3. `Show reforged` and `Show favorite` as default.
4. Click `x10 forge`

Result:
Only 5 ⭐  weapons with Earth Element will be shown in the "show forged weapons" from the `x10 forge`. This shouldn't happen.

Expectation:
Show all newly forged weapons

**Comment by seiyria** [comment]
Adding to this, if possible, the grid should be more like:

```
x x x x
x - - x
x x x x
```

if possible. instead of what it is

**Comment by JoseMariani** [comment]
Error in gas límit, i cannot forget new weapon un X10 i have bnb and skill in my metamask

**Comment by Nyawmeowww** [comment]
Hi this is used by developers and for tracking purposes. You may use cryptoblades.hellonext.co for your concerns or you can direct it to #feedback-only/#bug-reporting-only thread on Discord.
