### ISSUE TITLE
Marketplace not showing listed Characters or Weapons

### ISSUE THREAD

**Issue by LordGoldThroneRoom** [CryptoBlades/cryptoblades#604]
Listing NFTs for Weapons or Characters is possible, and the transaction happens, but cannot see listed items, weather via searching ID or wallet address

**Comment by seiyria** [comment]
This is not for users to report bugs. Read the template you deleted or ignored.

**Comment by LordGoldThroneRoom** [comment]
I did read it, but as there is no where else to seek support where am I
supposed to report a bug like this?

**Comment by seiyria** [comment]
In discord, or elsewhere. This issue tracker is for our committed work. Additionally, chances are anything someone reports we already know about.
