### ISSUE TITLE
Buy shield transaction always fails

### ISSUE THREAD

**Issue by GarrettFleischer** [CryptoBlades/cryptoblades#611]
Like the title says, I press buy, confirm transaction, 3 seconds later it says transaction failed.
Tried on both Brave and Edge browsers.

**Comment by GarrettFleischer** [comment]
Transaction hash:
0x6345aa5ff1dcc0ad8b46b13cbc32e1b8ceef636ce97e1b99a5f8fcd9a35970ad

**Comment by seiyria** [comment]
this is not the place for users to report bugs.
