### ISSUE TITLE
The element icon on character is not centered. 

### ISSUE THREAD

**Issue by byyyyyyyyy** [CryptoBlades/cryptoblades#613]
Not sure if only on plaza but here's the screenshot. already have a fix on my local tho. 

![image](https://user-images.githubusercontent.com/88365848/128388740-b6a7edbf-2521-41d2-bb96-7cb7003de414.png)

**Comment by seiyria** [comment]
https://github.com/CryptoBlades/cryptoblades/pull/612

**Comment by byyyyyyyyy** [comment]
can i still get a pr? or was it done already?

**Comment by Nyawmeowww** [comment]
Yes. There's already a pull request for this.
