### ISSUE TITLE
add task to API to clean up items that are sold

### ISSUE THREAD

**Issue by seiyria** [CryptoBlades/cryptoblades#631]
this should check with the blockchain and delete anything that is currently priced at 0.

high level:

- for characters, weapons, and shields
- get count of items
- get pages of 10000
- iterate through all items, check price
- if 0, put in list
- use $in to remove items that are in list

**Comment by OPPandaDeFi** [comment]
I can give this a look this evening. This would go through, page by page, all items in the shop in one run?

**Comment by seiyria** [comment]
Yes. The idea is to go through everything and remove anything marked as sold. This shouldn't be super necessary but having it will be nice as it helps account for downtime in the API.

**Comment by seiyria** [comment]
can't close this just yet. the marketplace now uses web3 (because that was what was working, weirdly?), but the task is mostly there, the call to get final price needs to be updated. beyond that, should be close. will continue looking today.

**Comment by seiyria** [comment]
![image](https://user-images.githubusercontent.com/763609/129935127-57dc335b-412f-4b0c-a4b4-0c8931c7d85e.png)

as an update, this error pops up (somehow, it didnt when I was testing at first) when trying to call getFinalPrice using web3. no idea why or how.

**Comment by OPPandaDeFi** [comment]
Might be something with the provider and/or contract setup now that its switched to web3. Might need to migrate something else over. 

I can take a look tonight, if desired. Just let me know.

**Comment by seiyria** [comment]
It sounds like it was because of rate limiting. It's going to be a bit
touchy but I'll check it out later. Thanks for being proactive though!
