### ISSUE TITLE
SKILL was still deducted even though the transaction did not push through

### ISSUE THREAD

**Issue by dMac0000** [CryptoBlades/cryptoblades#635]
I was about to forge weapons 10x times but after I clicked the forge button and accepted it, I noticed that my BNB is not enough for the gas fee so I rejected it so that the process will not push through. But after few minutes, I noticed that my SKILL tokens were still deducted from my account even though the transaction did not proceed. And also, I did not receive the weapons that were forged if that is the reason the SKILLs were still deducted. What am I going to do or when will I get back my lost SKILL tokens? Thank you in advance for your response.
![SKILL](https://user-images.githubusercontent.com/88574029/128591702-73ea7696-fd71-4327-ad60-4845a9bcf940.PNG)
![SKILL 2](https://user-images.githubusercontent.com/88574029/128591719-a1a7aee4-e6b3-4ea3-9f49-5d0a8c554236.PNG)

**Comment by Lxous54** [comment]
I have the same issue, I hope Cryptoblades devs will resolve it.. I can't get into their Discord server to pass this complaint kinda sucks,

**Comment by KyLewis72** [comment]
Same issue. I wanted to try my luck since my gacha luck is really good, but there was nothing after confirming the request

**Comment by PhatLoijewelry** [comment]
im too , x10 weapons ....and I didn't get the weapon

**Comment by Nyawmeowww** [comment]
Hi! We are currently working on this issue. Rest assured that you didn't lose any skill in this process. The team is currently working on refunds. However, please refrain from opening issues in this repo. The **ISSUE TEMPLATE** should have explained everything for you when you created this thread. Thanks!

# ISSUE TEMPLATE
IF YOU ARE A USER, DO NOT OPEN ISSUES AGAINST THIS REPOSITORY. OPEN THE ISSUE ON HELLONEXT INSTEAD: https://cryptoblades.hellonext.co/

PLEASE DELETE THIS AND THE ABOVE TEXT BEFORE OPENING AN ISSUE
