### ISSUE TITLE
In 10x Forged i didnt get the swords but my skill get deduction

### ISSUE THREAD

**Issue by 131009813** [CryptoBlades/cryptoblades#637]
IF YOU ARE A USER, DO NOT OPEN ISSUES AGAINST THIS REPOSITORY. OPEN THE ISSUE ON HELLONEXT INSTEAD: https://cryptoblades.hellonext.co/

> 

PLEASE DELETE THIS AND THE ABOVE TEXT BEFORE OPENING AN ISSUE

**Comment by Nyawmeowww** [comment]
Hi! We are currently working on this issue. Rest assured that you didn't lose any skill in this process. The team is currently working on refunds. However, please refrain from opening issues in this repo. The **ISSUE TEMPLATE** should have explained everything for you when you created this thread. Thanks!

# ISSUE TEMPLATE
IF YOU ARE A USER, DO NOT OPEN ISSUES AGAINST THIS REPOSITORY. OPEN THE ISSUE ON HELLONEXT INSTEAD: https://cryptoblades.hellonext.co/

PLEASE DELETE THIS AND THE ABOVE TEXT BEFORE OPENING AN ISSUE
