### ISSUE TITLE
Skill approve usage

### ISSUE THREAD

**Issue by darkchoco14** [CryptoBlades/cryptoblades#642]
Hello i'm new here and wanted to know if there's something we can do about this process
If you do something with the usage of your skill there's a initial gas fee asking for the usage of skill?
Can we do something like a one time contract that always allow bsc to use the skill so that we don't have to pay for the gas fee of it.
So if there's something went wrong and the transaction failed we won't get charged always.

**Comment by seiyria** [comment]
This issue tracker is not for users to add issues to.
