### ISSUE TITLE
Create script to identify users who Forged but did not receive swords yet

### ISSUE THREAD

**Issue by devinep52** [CryptoBlades/cryptoblades#656]
1. Query blockchain for users who minted, but never received their swords
2. Write script to iterate over above users and mint them their swords

**Comment by Athelstan19** [comment]
please if you would consider adding a 5 star weapon to every user who were patiently waiting for their swords it will be greatly greatly appreciated. Thanks for your hard work guys. love you all.

**Comment by seiyria** [comment]
@Athelstan19 this is not the place for requests.
