### ISSUE TITLE
Ads

### ISSUE THREAD

**Issue by seiyria** [CryptoBlades/cryptoblades#661]

**Comment by Legend021** [comment]
How soon can I claim my rewards?

**Comment by seiyria** [comment]
@Legend021 this is not the place for this.

**Comment by Legend021** [comment]
Good day.

I'm sorry Sir. It's just we new players can't get into Discord and left
without any information. But thanks anyway.

**Comment by rayambler7** [comment]
Sample ads preview on fight results/waiting for fight results. (Google AdSense or BitMedia for Crypto-related ads)
![image](https://user-images.githubusercontent.com/88981394/129486218-d5578aa8-d8d3-4a2e-9b51-ce0a92a93772.png)
![image](https://user-images.githubusercontent.com/88981394/129486220-5341e7c8-35bc-4be1-b711-93ad77ed8f91.png)

Details posted here: https://cryptoblades.hellonext.co/b/Suggestions/p/google-adsense-or-crypto-ads-on-fight-results-waiting-fight-results

**Comment by Legend021** [comment]
Good day Sir,

This is great news. Thank you Sir for understanding. As I understand that
this is all still pre-implementation, can I have an approximate time of the
release of skill rewards. I won't leak it to anyone. It's just I am new to
crypto and heard about this game. I spent my savings intended for my
wedding and now I can't get my skill rewards. I just want to know Sir so I
can take other measures to secure the cash needed for my wedding on August
22. Again, I know this wasn't your fault, this is just so I'll know what to
do if the SKILL rewards won't be withdrawn before August 22. Thank you
again Sir and I apologize.

Sincerely,

Kevin
Cryptoblades Investor/Believer

**Comment by seiyria** [comment]
@Legend021 first off, again, this is not for users.

Second off you should not rely on this for income.

Thirdly, stop talking on random issues about off topic information.

**Comment by kevinunger** [comment]
Has anyone implemented the ads yet? If not, I'd like to do that.

**Comment by seiyria** [comment]
@kevinunger I think I did but I'm not sure if I did it correctly. Waiting for the next prod update to know for sure.

**Comment by Chriserus** [comment]
I think that the ads work as intended, should we close this issue? @seiyria

**Comment by seiyria** [comment]
Yup, they seem to.
