### ISSUE TITLE
User marketplace ads

### ISSUE THREAD

**Issue by crypto-smoke** [CryptoBlades/cryptoblades#663]
Allow users to purchase ad space on our site to advertise their market items. For v1 lets just have them input the item type and ID that is for sale and then display it for them to avoid too much overhead and additional work.

**Comment by bilbolPrime** [comment]
I can only see this as a mixture of solidity, redis caching and API. 

- Players purchases an advertisement slot for 1 item for x skill. The slot lasts for 1 week (arbitrary)
- The chain is scanned and market displays are synced to a database.
- Redis cache is updated with items that are still valid. Bought items or expired items are removed from cache.
- Front end calls API to get a random active listing and displays it with a quick purchase button. Completely random and all items have equal chance of showing.

Some tracking perhaps, on api side and db not solidity, to show how much an item was displayed to make sure everything is a go.

**Comment by Sellie96** [comment]
Not valid. Bazaar advertisements will be different.
