### ISSUE TITLE
Historical sales from marketplace

### ISSUE THREAD

**Issue by crypto-smoke** [CryptoBlades/cryptoblades#664]
A page that lets users see what recent sales were in the market. v1 can be a list, add filtering if its not too much work but thats OK to come later.

**Comment by seiyria** [comment]
Is this all sales or their sales? If theirs, we are tracking this but otherwise we're not

**Comment by ed3ath** [comment]
https://github.com/CryptoBlades/cryptoblades-api/tree/historical-sales

**Comment by Sellie96** [comment]
Closing issue as it is an api / Bazaar issue already seeing implementation on those repo's
