### ISSUE TITLE
Cookie consent banner for all sites

### ISSUE THREAD

**Issue by kevinunger** [CryptoBlades/cryptoblades#674]
We need a consent banner when using ads to comply with data-protection regulations like GDPR.

**Comment by seiyria** [comment]
We don't collect any data besides what Google analytics collects.

**Comment by kevinunger** [comment]
It's still needed under EU-Law, because services like analytics and adwords are collecting user data and using cookies from the users browser.

**Comment by kevinunger** [comment]
Don't have time to do that today. If someone else wants, go for it, please. The loading of google analytics in index.html must be disabled, before the user consents.
