### ISSUE TITLE
Customizable market tax display

### ISSUE THREAD

**Issue by seiyria** [CryptoBlades/cryptoblades#677]
Right now is a hard coded 15%, it should pull from the blockchain what the current value is

**Comment by Shivraj788** [comment]
Hey seiyria can you reduce the daily 7 fights to 2/3 and if anyone want to play 7 fight he need to farm herb in vilage of cbk so people dont be able to  play with multi account because farming is time consuming

**Comment by seiyria** [comment]
@Shivraj788 this is not the place for this.

**Comment by kcper** [comment]
It's already pulled from the blockchain.
In Market.vue
```
async loadMarketTaxes() {
      if(!this.characterMarketTax) {
        const tax = await this.getMarketTax(this.Characters.options.address) as string;
        this.characterMarketTax = this.convertMarketTax(tax);
      }
      if(!this.weaponMarketTax) {
        const tax = await this.getMarketTax(this.Weapons.options.address) as string;
        this.weaponMarketTax = this.convertMarketTax(tax);
      }
      if(!this.shieldMarketTax) {
        const tax = await this.getMarketTax(this.Shields.options.address) as string;
        this.shieldMarketTax = this.convertMarketTax(tax);
      }
    },
```
Or maybe you mean something else?

**Comment by seiyria** [comment]
@kcper thanks for the research. I will leave your comment since you did the work :D

**Comment by Chriserus** [comment]
Me and @kcper checked it the other day and it pulls data from the contract, so it works correctly, I'm closing this issue.
