### ISSUE TITLE
Add checkbox for "pay using staked SKILL only"

### ISSUE THREAD

**Issue by kevinunger** [CryptoBlades/cryptoblades#682]
When user chooses to do action "mint weapon" or "reforge weapon"...

*    When user selects "pay using staked SKILL only"...

    Then the action is performed
    And payment is deducted from user's staked SKILL (and *only* the staked SKILL), at a 20% discount

    ---

*    When user *does not* select "pay using staked SKILL only"...

    Then the action is performed
    And payment is deducted the standard way, but with staked SKILL as another fallback (such that the order is `IGO -> Unclaimed -> Wallet -> Staked` - `Staked` is added at the end)

**Comment by raymond-h** [comment]
Closed because PR is merged.
