### ISSUE TITLE
Concerns from code review of raid1.sol

### ISSUE THREAD

**Issue by brian-man** [CryptoBlades/cryptoblades#684]
I did an initial skim of raid1.sol in the raids branch and had some questions and concerns.  I'm recording them here so they don't get lost in Discord archival.

- [x] 1. Durability cost is incorrect/stale.
  - `durabilityCost = 20; // 48 mins each, or 16 hours`
  - From weapons.sol:
    - `uint256 public constant secondsPerDurability = 3000; //50 * 60`
  - It was updated from 48 to 50 here:
    - https://github.com/CryptoBlades/cryptoblades/pull/470
  - Fixed: https://github.com/CryptoBlades/cryptoblades/commit/795f0f6356980c355447799675d0e57d7f1b4035
- [x] 2. In doRaid() is it intended to always have a raid alive (1 queues 2 queues 3, etc.)?
  - Also is it intended that an empty raid can be killed and replaced?  (L135 isn't inside the if.)
  - The community can effectively reject a boss entirely, rather than being required to engage it before a new boss is offered.
  > By design for now.
- [x] 3. I thought the intended model was that stamina regen was deferred rather then consumed by the raid.
  - See `getFightDataAndDrainStamina` and `getFightDataAndDrainDurability` usage.
  > The `allowNegativeStamina` parameter on those functions are providing the desired results.
- [x] 4. xpReward parameter
  - `xpReward = 128 * 2; // 13 hour 20 min worth of fight xp, but we had double xp active on launch`
  - Shouldn't this:
    - (1) be assigned at raid start not as a constant
    - (2) be `game.fightXpGain() * 4`, since the `game` is already referenced?
  > Dan: I'd rather it be configurable so we dont have to redeploy if we want to change it quick.
- [x] 5. The `msg.sender` param to `getRandomSeed()` in `completeRaid()` is a constant.
  - Maybe instead of `getRandomSeed(msg.sender)` we use transaction count of the sender as the getRandomSeed param?
  - The point is that sending msg.sender is not really any more random than passing 0, when the sender is a constant.
  > Won't Fix.
- [x] 6. For `fight()`, ties goes to the player.  For raids apparently tie goes to the boss.  Intentional?
  - `uint8 outcome = roll > bossPower ? STATUS_WON : STATUS_LOST;`
  > Won't Fix for now.
- [ ] 7. My spidey sense tells me the distribution for `trinketWinner` is going to be "not provably fair" but I'm not a numbers guy so I can't show why.
  - `Raider memory trinketWinner = raidParticipants[raidIndex][seed % raidParticipants[raidIndex].length];`
  - Something about the distribution of the seed and/or "small numbers". I feel like raider with index 0 has an advantage, for example
- [x] 8. Recommend using `game.fightTraitBonus()` in `getPlayerFinalPower()`.
  - When/if we change that bonus we want the raid to have an automatic alignment with fight(), right?
  - `return uint24(ABDKMath64x64.divu(1075,1000).mulu(uint256(playerPower)));`
  > Dan: External calls to a contract will add cost.
- [x] 9. For "clever" players, the early bonus can be gamed by joining "anything" (L1) as early as possible and then later adding your "interesting" characters.  Not sure if we care but it's a bit distasteful from a fairness perspective, IMO.
  - Imagine, for example, that the first half is completely consumed by L1 and nobody with any real power actually gets the early bonus as a consequence.
  > Won't Fix.
- [x] 10. The `earlyMultiplier` logic in the for loop in `claimReward` looks expensive.
  > Won't Fix for now.
- [x] 11. Stale comment about dust.
  - `// dust is not implemented yet so we can expand with that later`
  > Fixed https://github.com/CryptoBlades/cryptoblades/commit/59e374981df893523c5268efbc287c2819bf28a8#diff-89753f4e3d26a52b7eb37a5bbfd0ab473ec1b8d82ca6b69a7ebc9e62198ca1bd
- [x] 12. Having trouble understanding this expression: `15 + comparedToAverage.mulu(85)`.
  - Is the intent "15-100 depending on comparedToAverage" where comparedToAverage is in the range [0,1]?
  > Confirmed.
- [x] 13. The rareRoll logic looks broken.
  - `if(rareRoll > 950) { uint mod = (seed / 10) % 20;`
  - For rareRoll in [951, 1000] integers ...
    - division => [95, 100] integers...
      - % => 15,16,17,18,19,0
  - So the following lines don't make much sense to me.
  > Reader error: The division and mod are applied to the `seed` not the `rareRoll`.
- [x] 14. Perhaps I misread, but my impression is that the seed passed to `distributeWeapon()` is based on `msg.sender` so if the same sender has multiple characters that win a given weapon level the sender will get some identical weapons.
  - Fixed https://github.com/CryptoBlades/cryptoblades/commit/f04dfb6b1631a79b6dace036ef13fe5f0068e69c
- [x] 14b. Also I'm not sure what the `/ 100` is for in `distributeWeapon()`.
  - "It's just entropy on the seed to avoid patterns. That same seed is already used for the loot chance rolls twice."
    - Considering this by-design then.
- [ ] 15. For several of the get functions, they are redundant as the mapping is already public.
  - `mapping(uint256 => uint256) public raidEndTime;`
  - `function getRaidEndTime(uint256 index) public view returns(uint256)`
  > https://github.com/CryptoBlades/cryptoblades/issues/1141
- [x] 16. We may not care because reads are "free", but from a good citizen / performance of nodes perspective, we should probably put the faster check first.
  - In `isEligibleForReward()`, the `raidStatus` check should come first.
  > https://github.com/CryptoBlades/cryptoblades/pull/693
- [x] 17. Similar to 16, except even more important: the in-contract checks are much faster/cheaper.
  - In `canJoinRaid()`, the `raidStatus` and `raidEndTime` checks should come before the characters and weapons contract calls. 
  > https://github.com/CryptoBlades/cryptoblades/pull/692
  - rejected / closed

**Comment by Sellie96** [comment]
Raids 1 is completed. Close
