### ISSUE TITLE
multi-coin marketplace & earning

### ISSUE THREAD

**Issue by seiyria** [CryptoBlades/cryptoblades#688]
@wintersummermint et al;

- [ ] add support for cashing out TBD tokens into SKILL
- [ ] change fight() from SKILL to TBD tokens
- [ ] the entire app will need a way to change what token you choose to earn, based on a list (tbd, given by kroge, hopefully retrievable from blockchain so it doesnt require updates). you will earn this token in place of skill, anywhere you currently do. ui-wise, in the app, it should require only a dropdown in settings, defaulting to SKILL. the dropdown should show the total reward amount in dollars you would get if you were to do something (0.01 skill per 40 stamina = X$ USD)
- [ ] in the app, the marketplace ui should be removed, and the link should instead have a link icon after it, leading to marketplace.cryptoblades.io (tbd) defaulting to `?token=skill`
- [ ] the marketplace will need to support multiple tokens. it should support a query parameter that dictates what token you use when searching the marketplace
- [ ] the marketplace will need a dropdown that lets a user change what token they are browsing by, and refresh the market accordingly
- [ ] there will need to be some way for other projects to get their nfts into our marketplace. when we go on chain, we could dictate that there be a specific api they must follow for their items to be listed, so all marketplaces conform to the same blockchain setup and require no extra work to incorporate

Other considerations, per @newb23:

As partnerships are forged, the ability for users to withdraw their earnings "directly" as a partner token will help to solidify that relationship.

Thought here is to add a "swap" function, that will convert unclaimed SKILL to partner token X, with a variable rate as determined by a contract setting. IE:

1. 1 Unclaimed SKILL = 1 SKILL.
1. User selects CHAIN as their claim token (1 SKILL is 5 CHAIN)
1. Contract looks up SKILL <> CHAIN conversion rate, adds whatever modifier (variable and local to the contract) and does a swap behind the scenes (User will receive 5 CHAIN + 20% "bonus" for using a partner token. Total 6 CHAIN.)
1. 1 Unclaimed SKILL is removed from their unclaimed skill pool/allotment
1. User receives 6 CHAIN

Other considerations, per @brian-man:

1.  Speaking for myself, I think the absolute simplest is to make the TBD currency the same as the gas currency.  This makes it easy for people to compare action cost (gas fee) with payouts; it also insulates game devs and players from market fluctuations of non-gas currencies relative to gas.  Lastly, and perhaps most importantly, it saves players gas having to convert back to gas (for future game interactions) if they choose gas as their "claim" currency. I intentionally say gas here because as multi-chain develops, the gas would/could expand from bnb, eth, btc, bch, etc. and the "simplest" (from the previous paragraph) just naturally translates.

**Comment by poshdan** [comment]
The marketplace contract was already designed to allow listing other NFTs, though their special properties are not included by deafult (like we do with weapons & characters). However, these can be looked up after the IDs are acquired (but sorting and filtering them ahead of time is very tricky to do)

However the skill pricing is hard coded, it's not trivial to expand it to other types, though i have some rough ideas that I can't confirm to actually work yet. We could opt to deploy different market contracts for each type, though that would create overhead in our contract updates. The upside would be filtering options specific to the external NFTs.

**Comment by seiyria** [comment]
@poshdan my intent is that we offload the work entirely onto the people who want to list on our marketplace: we import their abi, some small template of some sort linked to their app, and they follow our setup but for their market (the listing, filtering, etc, which would also be on them). then configuring their market is simple enough as putting all that info in a json file and iterating over it

**Comment by wintersummermint** [comment]
Thanks for info, I think this might change how the UI handle multi-coin display. I will coordinate this to Zhang, I currently have the update new marketplace but this are not yet considered criterias in the mockup

**Comment by wintersummermint** [comment]
> the entire app will need a way to change what token you choose to earn, based on a list (tbd, given by kroge, hopefully retrievable from blockchain so it doesnt require updates). you will earn this token in place of skill, anywhere you currently do. ui-wise, in the app, it should require only a dropdown in settings, defaulting to SKILL. the dropdown should show the total reward amount in dollars you would get if you were to do something (0.01 skill per 40 stamina = X$ USD)

This one confused, this is in current CB app right? the balance skill and options to display any token converted w/ USD amount is that correct? (we can create new issue for this)

**Comment by seiyria** [comment]
@wintersummermint that particular feature will apply to CB, yes. it is still part of this issue, since there's no reason to have it unless there is more than one token to view.

**Comment by brian-man** [comment]
> but sorting and filtering them ahead of time is very tricky to do)

@poshdan @kroge @seiyria 
I've been prototyping the filtering support in a standalone contract.  The general approach is described in this PR:
https://github.com/CryptoBlades/cryptoblades/pull/305

Specifically
>   generic mechanism to properly index, filter, and display any NFT.

**Comment by poshdan** [comment]
For reference, in #719 we were thinking of having the currencies be chosen on claim. A pre selection could happen on frontend (to show the amount ahead of claim) but as far as the contracts go, it would be most frictionless if we offered a list of rates for each token, and made that choice on claim instead of earning specific currencies directly.

**Comment by newb23** [comment]
> Regarding to above and notes in the description, this would still require enough SKILL in the rewards pool as it sounds like we treat it as a base currency to swap from. How about we give rewards with "in game" usd that can be swapped for chosen currency on claim? It would let us block swapping to and withdrawing of currencies wich pools are empty, including SKILL.
> 
> Earning in SKILL may be limited like it currently is, earning in "in game" usd won't be. But then there's a problem what happens when all reward pools are empty and someone sits with a bag of ingame usd.
> 
> Not sure if this solution does introduce more problems that it solves, but thought it's worth sharing. 

This is a valid concern, and what would like be the "safest" alternative would be to have its own contract pool to hold the currencies, SKILL and partner, and work out of that. That said, once the inflow/outflow issues with the reward contract are resolved, that would just add an additional contract to worry about, and I'd more likely a non-issue.

**Comment by poshdan** [comment]
The way I see it, though the unclaimed pool currently refers to SKILL, we can offer users to withdraw in another currency based on the ratios, so we'd never have to touch real skill tokens for that.
I do think a separate contract for rewards makes sense for security reasons and upgradability. We can either start tracking the new unclaimed rewards there OR add a function to the main contract that will subtract specifically from the unclaimed pool with privileges required, so we can both keep the old counter and let us pay out from another contract.

**Comment by kcper** [comment]
> The way I see it, though the unclaimed pool currently refers to SKILL, we can offer users to withdraw in another currency based on the ratios, so we'd never have to touch real skill tokens for that.

That means we would have to reward with unclaimed SKILL even when SKILL reward pool is empty. So sometimes it will be covered by real SKILL and sometimes not. I think it's fine, but seems weird that you might have x unclaimed SKILL and be unable to claim it.

**Comment by poshdan** [comment]
> > The way I see it, though the unclaimed pool currently refers to SKILL, we can offer users to withdraw in another currency based on the ratios, so we'd never have to touch real skill tokens for that.
> 
> That means we would have to reward with meaningful amounts of unclaimed SKILL even when SKILL reward pool is empty. So sometimes it will be covered by real SKILL and sometimes not. I think it's fine, but seems weird that you might have x unclaimed SKILL and be unable to claim it.

Well, you can claim it in another currency if you want, or wait until you can claim it in skill.
The main difference I see here compared to choosing the currency ahead of time, is that if your targeted rewards are empty, you no longer have a choice to still get something. (until it is refilled)

That makes me realise though, choosing currency on claim won't work well with our planned earning formulas. We have to give a percentage of the pool so we never owe more than we can give, but then we have to track it per-currency (requiring pre-choosing). Perhaps we could track only skill, but "refund" the owed skill in payout calculations for claims that happen in another currency. I may have to run some simulations on this.

**Comment by newb23** [comment]
> That makes me realise though, choosing currency on claim won't work well with our planned earning formulas. We have to give a percentage of the pool so we never owe more than we can give, but then we have to track it per-currency (requiring pre-choosing). Perhaps we could track only skill, but "refund" the owed skill for payout calculations for claims that happen in another currency. I may have to run some simulations on this.

I am not privy to the planned earning formulas, as obvious, I hope, by the recent shenanigans. If this is indeed the case, would it be more beneficial to hold off on an attempt at an implementation based on the conversation here, #719, and in the #multi-farm channel? I don't mind doing the work if there's even a chance at it being used, but if it's going to be a hard, "Negative, Ghost Rider." no need put in the time.

**Comment by Sellie96** [comment]
Multifarm was completed closing issue
