### ISSUE TITLE
Add raiders/boss power bar

### ISSUE THREAD

**Issue by kcper** [CryptoBlades/cryptoblades#714]
Under raid info add raiders power bar showing raiders power / (raiders power + boss power) percentage which is victory chance.
![image](https://user-images.githubusercontent.com/9114200/131255876-814a7c41-9269-4198-b600-6f0a00b571d4.png)

PS. I like this kind of animated progress bar
https://bootstrap-vue.org/docs/components/progress#animated-backgrounds

**Comment by seiyria** [comment]
The progress bar changing color based on state (25%, 50%, 75%, 90+%) I think would be excellent!
