### ISSUE TITLE
Add support for Unclaimed SKILL to be withdrawn as a token type of user's chosing

### ISSUE THREAD

**Issue by newb23** [CryptoBlades/cryptoblades#719]
As partnerships are forged, the ability for users to withdraw their earnings "directly" as a partner token will help to solidify that relationship.

Thought here is to add a "swap" function, that will convert unclaimed SKILL to partner token X, with a variable rate as determined by a contract setting. IE: 

1. 1 Unclaimed SKILL = 1 SKILL. 
2. User selects CHAIN as their claim token 
    - (1 SKILL is 5 CHAIN)
3. Contract looks up SKILL <> CHAIN conversion rate, adds whatever modifier (variable and local to the contract) and does a swap behind the scenes
     - (User will receive 5 CHAIN + 20% "bonus" for using a partner token. Total 6 CHAIN.)
4. 1 Unclaimed SKILL is removed from their unclaimed skill pool/allotment
5. User receives 6 CHAIN

**Comment by bilbolPrime** [comment]
Assigning this to posh as well as big guns are probably needed on this one, at least for guidance.

Do we have everything we need to push this forward or is this on hold until further info / metrics are available?

If this is on hold then we can clear all assignee to avoid confusion

**Comment by Sellie96** [comment]
Multi Farm implementation
