### ISSUE TITLE
Node

### ISSUE THREAD

**Issue by Bognar791** [CryptoBlades/cryptoblades#724]
How are you?
What is node.js version for this project?
I am using 14.17 but npm install showing errors..
I want to know that version is correct for this project.

**Comment by seiyria** [comment]
If you don't post the error, there is no help I can give. Additionally, this tracker is not the place for user support. However,  most of us use node@latest and npm@5 (for lockfile v1).

**Comment by Bognar791** [comment]
[image: image.png]
Compile contract error.

**Comment by Bognar791** [comment]
> Compilation warnings encountered:

    project:/contracts/shields.sol:123:9: Warning: This declaration shadows an existing declaration.
        uint256[] memory tokens = new uint256[](balanceOf(owner));
        ^---------------------^
project:/contracts/shields.sol:59:5: The shadowed declaration is here:
    Shield[] private tokens;
    ^---------------------^

project:/contracts/ChainlinkRandoms.sol:66:9: TypeError: Wrong argument count for function call: 3 arguments given but expected 2.
        requestRandomness(keyHash, fee, VRF_MAGIC_SEED);
        ^---------------------------------------------^

Compilation failed. See above.
Truffle v5.4.8 (core: 5.4.8)
Node v16.8.0
npm ERR! code 1
npm ERR! path D:\Work\Projects\CryptoContract\cryptoblades
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c npm run contract:prepare && lerna exec -- npm install

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Smart\AppData\Local\npm-cache\_logs\2021-09-02T06_20_27_363Z-debug.log
