### ISSUE TITLE
Npm install (compile error)

### ISSUE THREAD

**Issue by Bognar791** [CryptoBlades/cryptoblades#725]
I am using node v16.
I cloned and run npm install, I saw this error.
![Screenshot_1](https://user-images.githubusercontent.com/69195263/131830740-8da7fe2e-b995-414c-9de3-975e0abbbed7.png)
(url)

**Comment by Nhegg** [comment]
mine is v14.17.5 and it works pretty well..

**Comment by seiyria** [comment]
Okay, when I said "this is not for support" that does not mean open another issue.
