### ISSUE TITLE
Market filters broken

### ISSUE THREAD

**Issue by bilbolPrime** [CryptoBlades/cryptoblades#730]
Any filter that is not Any on stars will result in an empty listing. 
![image](https://user-images.githubusercontent.com/25177987/132129924-e9634f61-d75b-4f42-b3f3-6f34ae7ab01b.png)

Any filter that is not any element will result in very little results.
![image](https://user-images.githubusercontent.com/25177987/132129908-7bd7dd20-cfec-4fb1-a16a-17b0ec034ec8.png)

**Comment by metrocoding** [comment]
brows nft weapons 4 stars low to the high list is not showing correctly.
<img width="1104" alt="Screen Shot 2021-09-06 at 2 50 35 AM" src="https://user-images.githubusercontent.com/46874334/132143604-dd71d25e-4026-4172-b2bb-ab8e078635a8.png">

**Comment by seiyria** [comment]
@metrocoding this is not for user comment.
