### ISSUE TITLE
Land sale

### ISSUE THREAD

**Issue by kcper** [CryptoBlades/cryptoblades#739]
- [ ] Add land sale items in skill shop's 'Specials' section: T1, T2, T3 land
- [ ] Tier 1 land - buy a land in random location
- [ ] Tier 2 land - popup a map made of 50x50 chunks -> select a chunk -> popup confirmation containing chunk coordinates, element, land tier and buy button -> buy land in a random location of that chunk
- [ ] Tier 3 land - same as tier 2
- [ ] Chunks highlighted on hover
- [ ] Each user can buy only 1 land
- [ ] Only one tier 3 available per chunk
- [ ] Only 1mil total lands can be bought and all tier 3 lands need to be part of that list
- [ ] extra: checkbox in map modal to show chunk population, if enabled highlight chunks in green/yellow/red based on amount of lands sold in the chunk

Up to date map can be found in `#lore` discord channel.

**Comment by bilbolPrime** [comment]
Added solidity support for feature:

ChunkId = x coordinate + 50 * y coordinate; coordinates started at (0, 0)

**BlackSmith:**
- cbkLandSale: reference to the CBKLandSale contract
- purchaseT1CBKLand(uint256 paying): purchase a tier 1 land
- purchaseT2CBKLand(uint256 paying, uint16 chunkId): purchase a tier 2 land
- purchaseT3CBKLand(uint256 paying, uint16 chunkId): purchase a tier 3 land
- getCBKLandPrice(uint8 tier): gets price of land in wei

**CBKLandSale:**

- salesAllowed(): check if land can be purchased.
- getAllowedLandOffset(): variable used to check if a chunk can sell T2 land.
- checkIfChunkAvailable(uint8 tier, uint16 chunkId): check if chunk is available for tier. Should be only called when user selects a chunk for T2 or T3 purchase or before a T1 purchase is requested. If T1 purchase, chunkId is a dummy variable.
- checkChunkReserved(uint16 chunkId): check if chunk is reserved
- checkChunkEstimatedPopulation(uint16 chunkId): _projected_ chunk population. Should NOT be called for every chunk. APIs to be added.
- getAvailableLand(): returns (available T1, available T2, available T3)
- getAvailableLandPerChunk(): returns available land per chunk
- getSoldLand(): returns (sold T1, sold T2, sold T3)
- getPurchase(): returns purchase if any, (purchased tier, chunkId or stamp if T1)


Will work on APIs next.

Code on 739-land-sale and draft PR opened #746

**Comment by bilbolPrime** [comment]
Comment updated with solidity changes

Further testing and possible optimization to be made

**Comment by bilbolPrime** [comment]
Black = Zone
Grey = chunk
![image](https://user-images.githubusercontent.com/25177987/134299632-bfde951c-0c75-4bf4-8407-8f9d5b139da0.png)

**Comment by bilbolPrime** [comment]
@KennyUTN you are handling this one right?
If you can't do it please unassign yourself

**Comment by Chriserus** [comment]
Is @KennyUTN doing a frontend part of this? Or should I go in and do it, @bilbolPrime ?

**Comment by bilbolPrime** [comment]
@Chriserus 
Please use getReservedChunksIds to show the reserved chunks. Returns array of chunk ids
Also sale is now disabled by default, you need to enable it if you deploy a fresh chain

**Comment by bilbolPrime** [comment]
@Chriserus we have a new type of claimable land; a land which was minted but doesn't have a chunkid assigned yet

The get inside NFTLand contract has been extended to return reseller address 
```function get(uint256 id) public view returns (uint256, uint256, uint256, uint256, address)```

Also a function has been introduced to CBKLandSale to change chunkId
```function changeLandChunkId(uint256 landId, uint256 assignedChunkid)```

You can use the existing function to get available chunks
```function getChunksOfReseller(address reservedFor) ```

You can tell a land can claim a chunk if it has a reseller and chunkId 0.
The flow would be as follows:
- Get land data
- Get chunk ids reserved for the reseller returned by the get 
- Allow the user to pick a chunk (if T2 or T3); 1 T3 per chunk still applies.
- Call changeLandChunkId with landId and selected chunk (for T1 the selected chunk can be sent as anything and will not be taken into consideration by chain; round robin will apply)

**Comment by Chriserus** [comment]
By when should we have it live? Do we have any date? As I committed to CBK Landing Page work and will continue to work on it on Monday

**Comment by bilbolPrime** [comment]
I think this can wait some days as they would get the NFT from sale. We will ask in tomorrow's meeting.

**Comment by brian-man** [comment]
@bilbolPrime @Chriserus Should this be closed? No updates since October.

**Comment by Sellie96** [comment]
Land sale completed. Close
