### ISSUE TITLE
Who the fuck are you, exactly?  Just another user of git hub....

### ISSUE THREAD

**Issue by macguyversmusic** [CryptoBlades/cryptoblades#758]
posted in good faith because an associate reported losing money in a game and when i googled the name i was led to your github page and it concerns me that some people without reading or knowing will find those links.

> matters to me and my associates who have had to listen to countless people beg for help to recover funds from scams 
RESPONSE

Who the fuck are you, exactly? Why should I be inclined to care about your situation, especially when you barge in here and make assumptions without understanding?

So, for specific clarity:

> 1.What terms are breached by them please for clarity

We. Do. Not. Have. A. License. So. They. Cannot. Use. Our. Code.

Was that easier to understand?

> Can you show us clauses from the licence that are provably broken? evidence??

See above.

> Is this illegal?

See above.

> How do crypto blades users benefit from these takedown notices?

Why does this matter, exactly?

> How will these notices help the cryptoblades gamers??? people with money still in SKILL.

Why does this matter, exactly?

_Originally posted by @seiyria in https://github.com/CryptoBlades/cryptoblades/issues/740#issuecomment-925193708_

**Comment by seiyria** [comment]
Do not open issues, especially when it's just copying text.
