### ISSUE TITLE
Shield Features

### ISSUE THREAD

**Issue by Nyawmeowww** [CryptoBlades/cryptoblades#759]
As stated, Shield have the following properties:

1. **Element**
-  Fire, Earth, Lightning, Water
2. **Star**
- 1, 2, 3, 4, 5
3. **Tier**
- I, II, III
4. **Skin**
- _No available data_

# Templar's Will Feature Specification

## **UPGRADE**
* Upgrade is measured in level. 
* An upgrade will occur once a shield reaches every 10 levels of completed _Quests_ upgrading its _Tier_, called a breakthrough.
* An upgrade every 10 levels will cost a given amount of SKILL.
* Different _Tier_ will have bonus stats.

## **ENCHANT**
* Players can spend dust to change/roll the stats of the desired equipment. These of course will continue to be our core stats (STR, DEX, CHA, INT).

## **PRAYER**
* Spend souls to randomly upgrade a 3-star Shield to a 4-star shield.
* After doing a specific number of prayer, it will guarantee a level up

# Legendary Defender Feature Specification

## **SPECIAL ABILITY**
* Spend souls to re-roll the base trait of the shield.

# Shield Features Documentations
**Docx FIle**
[Shield.docx](https://github.com/CryptoBlades/cryptoblades/files/7215260/Shield.docx)

**PNG File**
![image](https://user-images.githubusercontent.com/31758395/134460842-77c05be9-0890-4ec5-8c1a-04e3b458676f.png)

**Comment by Sellie96** [comment]
Keep open this documentation needs rebringing up

**Comment by seiyria** [comment]
needs to be redone with template, then this issue can be closed

**Comment by MrBaptista69** [comment]
Feature has been created, #1741
