### ISSUE TITLE
Adjust earnings calculator to new payout formula

### ISSUE THREAD

**Issue by kcper** [CryptoBlades/cryptoblades#768]
Earnings calculator still uses old formula. It needs to be adjusted to base it's calculations on the new payout formula and current payouts (changing every hour).

**Comment by poshdan** [comment]
Issue is as relevant as ever. We recently removed the calculator, it is time to add it back (with a warning that the allowance may not be available during the full hour!)

**Comment by poshdan** [comment]
I believe PR #850 has achieved this task. Closing
