### ISSUE TITLE
API Enhancements / bug fixes

### ISSUE THREAD

**Issue by bilbolPrime** [CryptoBlades/cryptoblades#778]
- [ ] Throttling startup full sync
- [x] Reconnect market listener automatically if disconnected
- [ ] Full sync at most once per 24 hours or on demand
- [ ] Partial syncs
- [ ] Do not show private sales
- [ ] Sync banned accounts

**Comment by bilbolPrime** [comment]
Reconnection (basic version) https://github.com/CryptoBlades/cryptoblades-api/pull/25 and https://github.com/CryptoBlades/cryptoblades-api/pull/26

**Comment by bilbolPrime** [comment]
Integrated OKex and other fixes for stable integration
https://github.com/CryptoBlades/cryptoblades-api/pull/27
https://github.com/CryptoBlades/cryptoblades-api/pull/28
https://github.com/CryptoBlades/cryptoblades-api/pull/29

**Comment by Sellie96** [comment]
API v2 revamp is ongoing and specced on that repo. Closing this issue
