### ISSUE TITLE
Implementation of Trinkets

### ISSUE THREAD

**Issue by MrBaptista69** [CryptoBlades/cryptoblades#792]
Implementation of the Trinkets as it has been discussed in Discord.

Propositions
In my opinion the initial idea of keeping things simple would be better:
- 1 type of trinket
- applied to weapon adds a random of X possible weapon bonuses
- applied to character adds a random of Y possible character bonuses
- no need to have X = Y
- bonuses are different for weapons/characters, but all we need to do is to pick a random%(X or Y) and assign a corresponding bonus based on nft type (trinket doesn't know what bonus it provides so we just need to implement the burning function)
The bonuses ideas sound good. I'd want to see some earnings boost too, applicable to character and weapon, 5% wouldn't hurt us and we could make it very rare to get. This just seems like the most desired thing to get, could boost trinket value even more and we'd probably make it back from bigger market fees.I was trying to think if this approach results in any limitations to future trinkets extensions, but don't see any.Thing to consider is if we want to allow using multiple trinkets on one nft, I'd say we do.

**Comment by seiyria** [comment]
will be put back in using the template using more updated information
