### ISSUE TITLE
Add sash to market pages for banned sellers

### ISSUE THREAD

**Issue by brian-man** [CryptoBlades/cryptoblades#815]
The "SOLD" sash shown on item is implemented by checking for a zero price as an indicator for a listed item no longer being available.

Similarly, we should add a sash for items that are not available for purchase (but not updated in the API back-end yet).

The contract calls looking something like:

seller_address = ...getSellerOfNftID(nft_address, nft_id)...
is_seller_banned = ...isUserBanned(seller_address)...

**Comment by brian-man** [comment]
@Nyawmeowww Any update on this?

**Comment by Nyawmeowww** [comment]
I have unassigned this for new-market development

**Comment by Nyawmeowww** [comment]
Although, I'm not sure if this is still a priority?
