### ISSUE TITLE
Skill balance Tooltip "withdrawable" should be updated

### ISSUE THREAD

**Issue by brian-man** [CryptoBlades/cryptoblades#827]
The tooltip for the "Total Balance" switched (I think) from "Unclaimed" to "Withdrawable" (or maybe it was always "Withdrawable")?  Anyway...

Given that clicking the Withdraw button will not actually withdraw the full amount, can we make the tooltip better?

Ideally it should show something like "+ Withdrawable 0.19 / 2.94 Skill" (assuming you haven't claimed today yet).

**Comment by brian-man** [comment]
![image](https://user-images.githubusercontent.com/36871683/139949757-53cdde92-6c63-4682-90c3-b846a2f0acb2.png)

**Comment by kcper** [comment]
This is outdated with the current claiming system (Treasury),
