### ISSUE TITLE
Staking for LAND (no date, just earn while you stake)

### ISSUE THREAD

**Issue by MrBaptista69** [CryptoBlades/cryptoblades#833]
IF YOU ARE A USER, DO NOT OPEN ISSUES AGAINST THIS REPOSITORY. OPEN THE ISSUE ON HELLONEXT INSTEAD: https://cryptoblades.hellonext.co/

PLEASE DELETE THIS AND THE ABOVE TEXT BEFORE OPENING AN ISSUE

**Comment by kcper** [comment]
Done #889
