### ISSUE TITLE
Extend combat.vue with new pay formula mechanics

### ISSUE THREAD

**Issue by poshdan** [CryptoBlades/cryptoblades#840]
1. Show a hint that explains how the hourly allowance works (we release a certain amount of the reward pool every hour, and if it's drained the earnings will be zero until the next hour)
2. Add a timer that counts down to the next hourly update. CryptoBlades.vars(6) has the last update timestamp in a unix style number with an accuracy down to the second. You'd get that value, and subtract the current time from it, then display the remaining time. There's no guarantee the update happens exactly on the hour so, if the timer could say "allowance update any moment now.." instead of going negative, that would be ideal.
3. Show the expected skill earned per 40 stamina (CryptoBlades.vars(5)) and the average power (CryptoBlades.vars(4)).
4. If you showed USD values that would be *chef kiss*. Giving users an idea about gas cost would be otherworldly. We don't really have a good reference point to obtain the latter, but I'm open to discussion, it would help users figure out their breakeven point.
5. Please add a confirmation modal on clicking fight, if the expected earning (CryptoBlades.getTokenGainForFight(monster)) from the target is 0. Make it say that xp will still be rewarded

**Comment by Chriserus** [comment]
Regarding point 4, for showing USD values maybe you can use CurrencyConverter component

**Comment by poshdan** [comment]
Done with #855
