### ISSUE TITLE
Add frontend lockout to additional Shield purchases

### ISSUE THREAD

**Issue by newb23** [CryptoBlades/cryptoblades#849]
Currently, you are able to attempt to buy multiple shields from the marketplace. Though this ultimately fails if you attempt to do so, a safety barrier (locking/disabling the goofy button with a popup saying you already minted one) should be added to the store page to prevent "wasted" gas.

EX: https://testnet.bscscan.com/tx/0x2fa51afb53a9f223c6fdad842ce9e5dd97710eb6609fe197d9d3fed55eddf85e

**Comment by poshdan** [comment]
Left notes in discord but I figured I'll copy them here.
A good way to check if the user had already purchased a shield would be to run this function of the Promos contract:
promos.getBit(userAddress,8)
The returned bool is whether the user had bought a shield, so we'd disable the button on true.
