### ISSUE TITLE
Move merchandise backend service to the api project

### ISSUE THREAD

**Issue by kcper** [CryptoBlades/cryptoblades#852]
There was a backend/index.js service added on merchandise front-end branch (https://github.com/CryptoBlades/cryptoblades/tree/MerchFrontend/backend).
We need to move it to the api project (https://github.com/CryptoBlades/cryptoblades-api) and call appropriately.

**Comment by ed3ath** [comment]
Will start working on it.

**Comment by ed3ath** [comment]
https://github.com/CryptoBlades/cryptoblades-api/pulls

**Comment by Chriserus** [comment]
@kcper It should be probably closed
