### ISSUE TITLE
Add ability to transfer nft via frontend

### ISSUE THREAD

**Issue by heki-ru** [CryptoBlades/cryptoblades#870]
**safeTransferFrom** for weapons and characters, possibly other nft in future

**Comment by kevinunger** [comment]
Add this here or on the market page?
Market -> List NFTs -> Show Weapon/Char -> select nft -> transfer button pops up on the button row
Think the option in the SS is better.

![image](https://user-images.githubusercontent.com/5601589/144483220-75ff14ed-db51-432e-9f0a-a44029514603.png)
![image](https://user-images.githubusercontent.com/5601589/144483283-f6bba1b8-727b-4d72-b2e4-9d131f63f155.png)

**Comment by kevinunger** [comment]
Current state:
Select 'Transfer' in the dropdown on weapons or characters.
![image](https://user-images.githubusercontent.com/5601589/144534194-d639e371-b990-4e46-898a-96800932f2c1.png)
![image](https://user-images.githubusercontent.com/5601589/144534229-30db9918-eb03-4388-982a-586ff889d4bc.png)
![image](https://user-images.githubusercontent.com/5601589/144534247-4c2ca5f7-08f5-4d35-aa5f-26b2dd4b8737.png)
![image](https://user-images.githubusercontent.com/5601589/144534290-0a61abdf-2e71-4f07-8e9f-95bc065e3a24.png)
![image](https://user-images.githubusercontent.com/5601589/144534409-fb4f3493-ac66-4469-a499-48f593fe626a.png)

If successful, current chars/weapons are fetched and modal closes.

**Comment by heki-ru** [comment]
![image](https://user-images.githubusercontent.com/20730021/144688814-dbfbb2de-04a4-44d4-9383-0ec624cb9b2c.png)
Hi @kevinunger can you check please, it looks like rename is missing now (on mainnet)

**Comment by kevinunger** [comment]
@heki-ru Yeah, that's a css issue somehow. Got a fix here https://github.com/CryptoBlades/cryptoblades/issues/894
