### ISSUE TITLE
Navigation bar is no longer mobile friendly

### ISSUE THREAD

**Issue by Sellie96** [CryptoBlades/cryptoblades#884]
Since the addition of treasury the navigation bar isn't fully accessible due to being too long.

Navigation bar could probably do with a revamp and making more mobile accessible.

Some devices are okay currently, but in the future they won't be.

![image](https://user-images.githubusercontent.com/60218956/144434359-89d92c1f-54ed-4263-9760-a2602ca4ffb5.png)

**Comment by kevinunger** [comment]
@Sellie96 What about doing something like this?:

![image](https://user-images.githubusercontent.com/5601589/144466543-d526c823-e657-4f94-aa5a-66cfbbfbd733.png)

Mobile view:
![image](https://user-images.githubusercontent.com/5601589/144466679-44eaaa04-0490-4aa8-a0b4-e7192fb8bb6d.png)
![image](https://user-images.githubusercontent.com/5601589/144466714-c536506c-d87a-4111-8a25-984661d6047c.png)

Easy fix for now ( in navbar.vue)
```
    <b-navbar target="navbar-toggle-collapse" class="main-nav" toggleable="sm" type="dark" variant="dark">
      <b-navbar-brand href="#" class="nav-logo">
        <img src="../assets/logo_Text_Source.png" class="logo d-inline-block align-top" alt="Logo">
      </b-navbar-brand>


      <b-navbar-toggle target="navbar-toggle-collapse">
        <template #default="{ expanded }">
          <b-icon v-if="expanded" icon="chevron-bar-up"></b-icon>
          <b-icon v-else icon="chevron-bar-down"></b-icon>
        </template>
      </b-navbar-toggle>

      <b-collapse id="navbar-toggle-collapse" is-nav>
        <view-links :is-nav="false" class="view-links"></view-links>
      </b-collapse>
    ```
