### ISSUE TITLE
Raid cost missing

### ISSUE THREAD

**Issue by Sellie96** [CryptoBlades/cryptoblades#900]
![image](https://user-images.githubusercontent.com/60218956/144857803-bb735844-3288-4d59-903c-a55c59fa5eed.png)

There is no indication that a raid costs skill (Currently 0.01 hardcoded).

Leading to confusion on whether a raid costs skill leading to contract error or why skill is disappearing. 

Quick fix to add the skill cost to either after the and or onto the signup button.

**Comment by kevinunger** [comment]
@Sellie96 
There is already an indicator. I'm not sure why it's missing in your screenshot. Rpc or MM issue?
![image](https://user-images.githubusercontent.com/5601589/146343124-dc3d4595-3696-402a-9bbd-05f0a37ed5ef.png)

**Comment by Sellie96** [comment]
This was reported to me by a few users, then I double checked in live myself all the same issue. I'll have another look and close the issue if it has resolved itself cheers @kevinunger
