### ISSUE TITLE
Idle Characters

### ISSUE THREAD

**Issue by seiyria** [CryptoBlades/cryptoblades#910]
You should be able to have an "idle character" garrison. These characters would not be part of your team, and would not recover stamina. 

You should be able to buy characters from the market or recruit new characters, even if your team is full. These characters would go to your "garrison". You could also choose to swap someone out of your main party and push them into reserve when buying or recruiting a character (or just send them to reserve, the default action).

This is important for #492, and should be done beforehand.

**Comment by brian-man** [comment]
@seiyria Anything remaining work needed to close this issue?

**Comment by seiyria** [comment]
nope, this is done
