### ISSUE TITLE
NFTStorage should not allow for stamina regen for chars / weapons

### ISSUE THREAD

**Issue by seiyria** [CryptoBlades/cryptoblades#911]
required for #910

NFTStorage should not allow character stamina or weapon durability regeneration, whether it resets timestamps on retrieval or zeroes them out doesn't matter, it just needs to not regen stamina while stored

**Comment by brian-man** [comment]
Option 1: NFTStorage should not allow character stamina or weapon durability regeneration

Option 2: NFTStorage should not allow character stamina regeneration
(Adds consistency across CBC/CBW.)

Optino 3: When extracted an NFT from NFTStorage, "use" attribute (character stamina, weapon durability, etc.) should be set to zero.

**Comment by kcper** [comment]
Should we close this based on recent discussions?

**Comment by seiyria** [comment]
Yes!
