### ISSUE TITLE
add google analytics events

### ISSUE THREAD

**Issue by seiyria** [CryptoBlades/cryptoblades#93]
- [x] click forge button
- [x] click reforge button
- [x] click recruit button
- [x] click combat button
- [x] page views for individual pages
- [x] click sell on market

an ideal solution would use document.on('click') to filter out all buttons so any button click is registered. might need additional work from there.

**Comment by wintersummermint** [comment]
<img width="1127" alt="Screen Shot 2021-06-28 at 4 29 03 PM" src="https://user-images.githubusercontent.com/9636557/123604991-f6c27880-d82d-11eb-95d3-6df5bfbde2fc.png">
Hey I got problem on udpated my PR, it doesnt recognize my fork anymore

**Comment by wintersummermint** [comment]
Ok, tried to get PR out seems working : https://github.com/CryptoBlades/cryptoblades/pull/133
