### ISSUE TITLE
PvP Contract revamp

### ISSUE THREAD

**Issue by RafaelVidaurre** [CryptoBlades/cryptoblades#945]
Rewrite the PvP Contract incorporating everything we've learned from the first iteration, this should greatly improve performance, reliability and maintainability.

Work here will be covered by tests, at first we will only test the essentials (as an alternative to manually testing against the frontend, which is slower for us)

TODOs:

- [x] Correct cooldowns approach
- [x] Port and adapt previous state structure
- [x] Add new state variables for player queues
- [x] `enterArena`
- [x] `leaveArena`
- [x] `requestOpponent`
- [x] `prepareDuel`
- [x] `performDuels` 
- [ ] improve test coverage

**Comment by Sellie96** [comment]
Going to close this issue PVP has been released and from your subtasks looks like it should have been done anyway.
