### ISSUE TITLE
Buying Land with KING is not displayed correctly

### ISSUE THREAD

**Issue by Nyawmeowww** [CryptoBlades/cryptoblades#974]
Image for reference:

![image](https://user-images.githubusercontent.com/31758395/147940598-b01898ed-d763-45ec-a0ee-8015fb34caa0.png)

**Comment by kevinunger** [comment]
https://github.com/CryptoBlades/cryptoblades/blob/1a68a4d7b16072331dd01b291b75cf6cddfc88d4/frontend/src/components/smart/NftList.vue#L951-L955
is returning a wrong?, large number for KING. `this.t1Landprice` here is `9897188175831208000` SKILL and `115792089237316195423570985008687907853269984665640564038535246804227652059136` KING 
@Chriserus  any idea why?

**Comment by Chriserus** [comment]
I checked, it's not frontend fault, somethings wrong with price bot, I suppose. I talked about it with @poshdan few days back. Locally it works fine. Probably oracle problem?
